### ISSUE TITLE
Error in get_via_csv()

### ISSUE THREAD

**Issue by emhart** [jennybc/googlesheets#114]
Trying to run your basic example:
```R 
> gap_key <- "1HT5B8SgkKqHdqHJmn5xiuaC04Ngb7dG9Tv94004vezA"
> copy_ss(key = gap_key, to = "Gapminder")
Successful copy! New sheet is titled "Gapminder".
Identifying info is a googlesheet object; googlesheets will re-identify the sheet based on sheet key.
Sheet identified!
sheet_title: Gapminder
sheet_key: 18cTmSgAs96lLN8-MeDCdw9DB4Ap-aHmWn-zumhthji4
> out <- get_via_csv(copy_ss)
Error: ss %>% inherits("googlesheet") is not TRUE 
```

I get the same error trying some other sheets as well.  Here's  a `sessionInfo()` dump:

```
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.4.1        googlesheets_0.1.1 XML_3.98-1.1       twitteR_1.1.8      gender_0.5.0.9000  devtools_1.7.0    

loaded via a namespace (and not attached):
 [1] assertthat_0.1  bit_1.1-12      bit64_0.9-4     bitops_1.0-6    DBI_0.3.1       digest_0.6.8    evaluate_0.5.5 
 [8] formatR_1.0     genderdata_0.1  httpuv_1.3.2    httr_0.6.1      jsonlite_0.9.14 knitr_1.9       lazyeval_0.1.10
[15] magrittr_1.5    parallel_3.1.3  plyr_1.8.1      R6_2.0.1        Rcpp_0.11.5     RCurl_1.95-4.5  rjson_0.2.15   
[22] stringr_0.6.2   tools_3.1.3     xml2_0.1.0     
```

**Comment by jennybc** [comment]
I think we're talking about the example in the README? The code is this:

```
gap_key <- "1HT5B8SgkKqHdqHJmn5xiuaC04Ngb7dG9Tv94004vezA"
copy_ss(key = gap_key, to = "Gapminder")
gap <- register_ss("Gapminder")
gap
```

I'd describe this as: copy, register, print for sanity check (then consume). In your code, you attempt to consume data from the `copy_ss()` function itself, hence the error.

You could streamline this a bit, following the example from `get_via_csv()`, where you capture the result from `copy_ss()` and then consume:

```
gap_key <- "1HT5B8SgkKqHdqHJmn5xiuaC04Ngb7dG9Tv94004vezA"
gap_ss <- copy_ss(key = gap_key, to = "gap_copy")
oceania_csv <- get_via_csv(gap_ss, ws = "Oceania")
str(oceania_csv)
oceania_csv
```

I'd describe this as: copy + register, consume.

(BTW I am actively working to make the interface less clunky! Would love to get any other feedback from you.)

**Comment by emhart** [comment]
Thanks Jenny, that clears it up.  Is it possible to make the register part transparent to the user?  If I have a sheet called "mySheet", right now I would access the data as follows:
```
ms <- register_ss("mySheet")
out <- get_via_csv(ms)
```

Is there any reason you couldn't just call consume the data directly via the name? e.g. `get_via_csv("mySheet")` ?

**Comment by jennybc** [comment]
You suggestion is exactly what I'm aiming for in the "make it less clunky" project. I'm working on it! Thanks for the suggestion.

You wouldn't want such a streamlined workflow all the time because sometimes you need to, eg. loop over worksheets, in which case you need the registration object to direct traffic. Or read, write, read, etc. from same sheet.

But if you are doing a quick read from a single sheet, YES, registration could be hidden from the user.

**Comment by jennybc** [comment]
Let me also point out you could already do this:

```
out <- "mySheet" %>%
  register_ss() %>%
  get_via_csv()
```
