### ISSUE TITLE
Create fake stable URL for the Gapminder example sheet

### ISSUE THREAD

**Issue by jennybc** [jennybc/googlesheets#119]
Consider adding a function to, e.g., make a copy of that example sheet into user's Google Drive.

**Comment by jennybc** [comment]
Current leading strategy: use a *persistent uniform resource locator* as suggested by @gavinsimpson.

http://en.wikipedia.org/wiki/Persistent_uniform_resource_locator

https://purl.oclc.org/docs/index.html

**Comment by jennybc** [comment]
@gavinsimplson Have you ever actually created a PURL? I have registered with purl.org and have successfully logged in. The [FAQ](https://purl.org/docs/faq.html) says:

> 3.2 How do I create a PURL?
> If you are not a registered user of the PURL resolver on which you want to create a PURL, you must become one. You are then able to create PURLs in domains of which you are a writer.
To create a PURL, point your Web browser to a PURL resolver, for example, OCLC's PURL resolver, and follow the resolver's instructions for creating a PURL. PURL resolvers provide a form for you to fill out to create a PURL. (This form should provide you with a default public domain in which you are allowed to create PURLs, so you don't have to go fishing for one.)
> 3.8 Can I create a subdomain?
> Yes. Anyone can create a subdomain.
> 3.9 How do I create a subdomain?
> If you are not a registered user of the PURL resolver on which you want to create a subdomain, you must become one. You are then able to create subdomains in domains of which you are a writer.
To create a subdomain explicitly, point your Web browser to a PURL resolver, for example, OCLC's PURL resolver, and follow the resolver's instructions for creating a subdomain.

But I have not found it to be true that [1] the PURL creation form provides a default public domain; or [2] the domain administration tab provides any way to create a subdomain.

Am I missing something obvious? I cannot find a way to create a PURL.

**Comment by jennybc** [comment]
Yes, this describes my experience exactly: [Creating new PURLs seems impossible](https://groups.google.com/forum/#!topic/persistenturls/TDlLl943K_o).

**Comment by jennybc** [comment]
It looks like there are long-standing problems re: neglect and "un-lovedness" with purl.org. So now I'm looking at this: <https://w3id.org>.

**Comment by jennybc** [comment]
I will try working with redirects from <https://w3id.org>:

https://github.com/perma-id/w3id.org/tree/master/people/jennybc

I went with browser URLs for Gapminder and the mini version and now need to create the infrastructure here in the package.

**Comment by gavinsimpson** [comment]
@jennybc This (the PURL registration) used to work, but I also tested this last night and I couldn't make it work now - no way to add new top-level domains. I've emailed the organisation that operates the PURL service to enquire about its status, but I would think this is now defunct and in maintenance mode now only allowing people to modify existing PURLs and expand their own existing TLDs.

**Comment by jennybc** [comment]
I do have the ability to park my own `.htaccess` somewhere and do redirects for myself. But it seems like a good idea to go with an outside organization. Too bad purl.org seems defunct. This feels like a pretty importance piece of web infrastructure!
