### ISSUE TITLE
Add support for appending a row of data to a sheet

### ISSUE THREAD

**Issue by daattali** [jennybc/googlesheets#130]

**Comment by jennybc** [comment]
Wrap this:

https://developers.google.com/google-apps/spreadsheets/#adding_a_list_row

**Comment by daattali** [comment]
I'm sure you've tested it enough, but verified working on my end on a shiny server as well

**Comment by jennybc** [comment]
Well I didn't test it much, so this is very nice to hear! I'm about to do a little timing study. Is it indeed faster in the context you showed me?

**Comment by daattali** [comment]
It is Indeed faster , it took about 5-6 sec previously, now it's ~3

**Comment by jennybc** [comment]
With these sorts of performance improvements, you could add *dozens* of rows in a reasonable amount of time. :joy:
