### ISSUE TITLE
extract_key_from_url fails when sheet belongs to a Google Apps for Work domain

### ISSUE THREAD

**Issue by wholtz** [jennybc/googlesheets#131]
I am using Google Sheets in a corporate environment through Google Apps for Work along with our own domain name. When I publish a Google sheet I get a URL like this:
https://docs.google.com/a/example.com/spreadsheets/d/SOME_KEY_VALUE_HERE/pubhtml
If I call gs_url with this, I get the message:
Authentication will be used.
Sheet-identifying info appears to be a browser URL.
googlesheets will attempt to extract sheet key from the URL.
Putative key: https:
Authentication will be used.
Error in gs_lookup(., "sheet_key", verbose) : 
  "https:" doesn't match sheet_key of any sheet returned by gs_ls() (which should reflect user's Google Sheets home screen).

It appears this form of URL is not currently supported by extract_key_from_url. I am able to access the sheet via gs_key.

**Comment by jennybc** [comment]
This should be an easy fix. So I take it "example.com" is just a placeholder, right? I just want to know what sort of characters can appear there for regular expression reasons.

**Comment by wholtz** [comment]
Yes, my company's domain name actually appeared where "example.com" is.

**Comment by jennybc** [comment]
Please try the code below with **your** actual browser URL as `ex_url` and confirm you get `SOME_KEY_VALUE_HERE` (or your actual key, if that's what you feed it)? If this works, I'll make the addition in master.

```
ex_url <- "https://docs.google.com/a/example.com/spreadsheets/d/SOME_KEY_VALUE_HERE/pubhtml"

url_start <- "https://docs.google.com/a/[[:ascii:]]+/spreadsheets/d/"

ex_url %>% stringr::str_replace(url_start, '') %>%
  stringr::str_split_fixed('[/&#]', n = 2) %>%
  `[`(, 1)
```

**Comment by wholtz** [comment]
That gives the error:
Error in sub("https://docs.google.com/a/[[:ascii:]]+/spreadsheets/d/",  : 
  invalid regular expression 'https://docs.google.com/a/[[:ascii:]]+/spreadsheets/d/', reason 'Unknown character class name'

I'm not sure where the [:ascii:] class is supposed to be coming from. I replaced it with [:print:] and then it successfully returned my key value. Thanks for your quick help!

**Comment by jennybc** [comment]
They both work for me, but OK we'll go with `[:print:]`! I'll address this and close via a commit later this afternoon.
