### ISSUE TITLE
Testing on RStudio Server

### ISSUE THREAD

**Issue by mattwg** [jennybc/googlesheets#136]
As of 2022-02-03, the googlesheets package has been archived on CRAN.
I'm closing all issues and pull requests prior to archiving this GitHub repo.

Learn more at:

<https://github.com/jennybc/googlesheets#readme>

**Comment by jennybc** [comment]
Yes we are working in a branch that has some extra functions to assist with authentication in these settings. You're correct that it currently does not work. In the branch, we've been targeting authentication within an app on a Shiny Server but I think the underlying problem is the same or similar. So we will check if the Shiny solution solves this problem or can be easily extended to do so. Look for an update on this issue soon.

@jzhaoo Will you look at the new "web app" auth flow with this in mind? Maybe the functions should be named differently, i.e. not so Shiny-specific? BTW @daattali is already running an RStudio server on DO so would probably be willing to test for you. Or you can put one up for us in the account we opened today.

**Comment by daattali** [comment]
Yup, here to help if needed.  What account did you open today? BTW that convo with Carl Boettiger  last week about authenticating from a server was not fruitful for me -- even after our back and forth I still couldn't authenticate. I forgot to follow up the following day, not sure if it's been fixed since then or not.

**Comment by mattwg** [comment]
Great. Let me know if you want me to help testing. We have Shiny Server and RStudio on the same boxes. 
Matt

**Comment by jzhaoo** [comment]
@jennybc I've set up DO (in a new account) and placed a shiny app onto the Shiny Server.
but Google doesn't seem to support public IP addresses for redirect_uris.

http://stackoverflow.com/questions/14238665/can-a-public-ip-address-be-used-as-google-oauth-redirect-uri
`Invalid parameter value for 
redirect_uri: Raw IP addresses not allowed: http://198.199.104.244/shiny/gs-explorer/`.

I'm guessing I'll need a domain name for the redirect_uri to work ... @daattali maybe you can help test on Shiny server?

**Comment by jennybc** [comment]
@jzhaoo @daattali yes please do work together to see how far you can get before @jzhaoo leaves. @jzhaoo you'll need to make this easy for @daattali, e.g. tell him which branch to install from and which app to test . Either from Shiny Server running inside his DO droplet or from RStudio server (in which case, maybe just test googlesheets running in a script or R console, but using the web app auth flow?).

**Comment by daattali** [comment]
@jzhaoo I'm not sure what I should do, as @jennybc said I'll need specific instructions. It'd be easiest if we meet and debug this in-person

**Comment by jzhaoo** [comment]
@daattali Can you please try this first?

1. From [this branch](https://github.com/jennybc/googlesheets/tree/shiny-oauth2-login), theres an app in inst/shiny-examples/gs-explorer, place it in srv/shiny-server/gs-explorer/ in your droplet. Im assuming the app will be reached at `http://daattali.com/shiny/gs-explorer/`.

2. Install the necessary libraries:

```
sudo su - -c "R -e \"devtools::install_github('jennybc/googlesheets', ref = 'shiny-oauth2-login)\""`
sudo su - -c "R -e \"install.packages('dplyr', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -e \"install.packages('plyr', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -e \"devtools::install_github('rstudio/DT')\""
```

3.  Let me know when its done and I'll add the url (http://daattali.com/shiny/gs-explorer/) as a redirect_uri to Google Dev Console, and hopefully it works.

**Comment by daattali** [comment]
your app is available at http://daattali.com/shiny/gs-explorer/

**Comment by jennybc** [comment]
I just tried to authorize the app and got this (but perhaps I should not be surprised because I doubt @jzhaoo has added the redirect_uri):
![gs-explorer-auth-error](https://cloud.githubusercontent.com/assets/599454/7894922/a6e4fa04-0629-11e5-9e8b-4485b52af97d.png)

**Comment by jzhaoo** [comment]
@jennybc  Try now, I just added it to Google dev console. It works for me. But ignore the "All Sheets" tab for now, try playing around with "Pick a spreadsheet". Thanks @daattali.

**Comment by jennybc** [comment]
HEY IT WORKS for me too! :tada:

Thanks @daattali for doing your part!

@jzhaoo Well done! Before you vanish on your trip, I hope you'll be able to document this. I gather our current sol'n requires that the "installed app" be on a server with a domain name. So that needs to be clearly spelled out. Also, please try to put this to work from RStudio Server (not necessarily related to Shiny) and/or leave me good instructions about where I should pick that project up. Finally, I suspect the functions you've added in `gs_shiny.R` may not be specific to *Shiny*, so maybe they should be renamed / redocumented to reflect that?

**Comment by daattali** [comment]
Awesome :)  Kinda weird that google requires you to have a domain name.  Can I remove from my server or do you want to keep around for a few days for testing?

**Comment by jennybc** [comment]
I guess I don't have strong feelings either way. Hopefully @jzhaoo will weigh in. Her official appointment w/ me is done and she's about to be away for 2 weeks, so she's quickly wrapping up loose ends and handing back off to me. We'll get it off your server soon either way. OK?

**Comment by MarkEdmondson1234** [comment]
Hi, I just stumbled across this but an interested observer, as looking to integrate googlesheets into Shiny.  The issue about Google needing a domain name you'll find is further confounded if running on shinyapps.io, as that has recently updated to running on an internal iframe within the domain, so code may break if its expecting a domain name in a normal Shiny server environment.  

I have this hack around that you may find useful, used within a Shiny server.R file:

```
  ## get the apps URL as default
shinyServer(function(input, output, session) {

  appURL <- reactive({
    if(!is.null(session)){
      pathname <- session$clientData$url_pathname
      ## hack for shinyapps.io
      if(session$clientData$url_hostname == "internal.shinyapps.io"){
        split_hostname <- strsplit(pathname, "/")[[1]]
        hostname <-  paste(split_hostname[2],"shinyapps.io", sep=".")
        pathname <- paste0("/",split_hostname[3],"/")
        
      } else {
        hostname <- session$clientData$url_hostname
      }
      
      paste0(session$clientData$url_protocol,
             "//",
             hostname,
             ifelse(hostname == "127.0.0.1",
                    ":",
                    pathname),
             session$clientData$url_port)
    } else {
      NULL
    }
  })

})
```

**Comment by jennybc** [comment]
Thanks @MarkEdmondson1234! This thing you say about the iframe is news to me. How recent is that? I  will need to check if this affects our functions to make the package work in Shiny and the apps we are currently including (and have deployed) .... will do next week.

**Comment by MarkEdmondson1234** [comment]
It was from around 5th June, when the new RStudio branding went live - from the shinyapps forum: https://groups.google.com/forum/#!topic/shinyapps-users/jHIx723wFzs

**Comment by jennybc** [comment]
OK my Shiny work leading up to useR and CRAN release came *after* that, so I was already living in that world. I should still endeavor to understand this better though.

**Comment by MarkEdmondson1234** [comment]
I can't get the googlesheets Shiny example to work here: https://jennybc.shinyapps.io/20_gs-explorer - it may be this issue.

**Comment by sunitj** [comment]
Hi Jenny et. al.
Great package! Thank you so much!

Just wondering if there are any updates on this? Is there a recommended way of authentication while using RStudio Server?

**Comment by jennybc** [comment]
I haven't come back to this specific thing yet but am actively working on clearing issues. I have to do some other things first.... but will get to this.

**Comment by nwstephens** [comment]
Thanks for this extremely useful package. I've recommended it multiple times to our customers. 
I was asked recently to look into how OAuth tokens could be generated easily from RStudio Server. The best solution I came up with was setting the <code>httr_oob_default</code> option to <code>true</code> before generating a token.

<code>options(httr_oob_default=TRUE)</code>

I wrote a detailed explanation on how to [generate an OAuth token from inside RStudio Server](https://support.rstudio.com/hc/en-us/articles/217952868). The solution requires you to manually copy and paste the URL and the access code between RStudio Server and the browser. It's far from ideal, but may be the best way for now.

**Comment by daattali** [comment]
Thanks for letting us know @nwstephens , this sort of information saves hours and hours of frustration to many of us. I haven't tried your solution yet but I wanted to preemptively thank you for making this available so that I can check that document next time I have to deal with this issue

**Comment by nwstephens** [comment]
Very much obliged, Dean. Thanks for your useful post about persistent data storage. I was just talking to a customer who uses googlesheets to log certain events in Shiny Server. I think this is all extremely useful. Note that I tested my solution on AWS. Let me know if you get a different experience on DO or some other network.

**Comment by MichaelChirico** [comment]
Thanks @nwstephens, certainly made progress with your article!

However, I'm still stuck... whenever I copy/paste the authorization code I'm given from the page I'm given after setting `options(httr_oob_default = TRUE)`, I get met with the same message as before:

> Error in curl::curl_fetch_memory(url, handle = handle) : 
>  Problem with the SSL CA cert (path? access rights?)

As such I resorted to running `gs_auth()` on my local machine, successfully (and also checked to be sure I could access the sheet I'm after), and attempting to upload my token:

```
tt = gs_auth()
saveRDS(tt, 'my_token.rds')
```

[manual upload step 😱 ]

Then `gs_auth(token = 'my_token.rds')`, however, once again:

> Error in curl::curl_fetch_memory(url, handle = handle) : 
>  Problem with the SSL CA cert (path? access rights?)

What might be causing this issue?

[not sure if I should open a new issue here...]

**Comment by jennybc** [comment]
This sounds like it might be something more general about the environment, i.e. not specific to googlesheets.

@MichaelChirico what are you trying to do? Especially, read or write? The successor package googlesheets4 is coming along and the unattended auth flows are much better ...

**Comment by MichaelChirico** [comment]
Just reading, for the task at hand. You may be right about the environment... any known gotchas to be aware of? The basics are:

<details>
```
sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.3 LTS

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
 [1] LC_CTYPE=en_US.UTF-8      
 [2] LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8      
 [8] LC_NAME=C                 
 [9] LC_ADDRESS=C              
[10] LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8
[12] LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets 
[6] methods   base     

other attached packages:
 [1] glue_1.3.0         googlesheets_0.3.0
 [3] config_0.3         sf_0.7-1          
 [5] magrittr_1.5       jsonlite_1.5      
 [7] purrr_0.2.5        httr_1.3.1        
 [9] readr_1.1.1        DBI_1.0.0         
[11] lubridate_1.7.4    tidyr_0.8.2       
[13] dbplyr_1.2.2       stringr_1.3.1     
[15] sparklyr_0.9.2     dplyr_0.7.8       

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.0       cellranger_1.1.0 pillar_1.3.0    
 [4] compiler_3.5.1   later_0.7.5      bindr_0.1.1     
 [7] class_7.3-14     r2d3_0.2.2       base64enc_0.1-3 
[10] tools_3.5.1      digest_0.6.18    packrat_0.4.9-3 
[13] tibble_1.4.2     nlme_3.1-137     lattice_0.20-35 
[16] pkgconfig_2.0.2  rlang_0.3.0.1    shiny_1.2.0     
[19] rstudioapi_0.8   curl_3.2         yaml_2.2.0      
[22] bindrcpp_0.2.2   e1071_1.7-0      spData_0.2.9.4  
[25] hms_0.4.2        htmlwidgets_1.3  classInt_0.2-3  
[28] rprojroot_1.3-2  grid_3.5.1       tidyselect_0.2.5
[31] forge_0.1.0      R6_2.3.0         units_0.6-1     
[34] backports_1.1.2  promises_1.0.1   htmltools_0.3.6 
[37] assertthat_0.2.0 mime_0.6         xtable_1.8-3    
[40] httpuv_1.4.5     stringi_1.2.4    lazyeval_0.2.1  
[43] broom_0.5.0      crayon_1.3.4
```
</details>

**Comment by jennybc** [comment]
Maybe @jeroen could offer a quick opinion 🙏

**Comment by nwstephens** [comment]
@MichaelChirico Are you making this connection on RStudio Server Pro by chance? The error says you are having problems with your SSL cert.

**Comment by nwstephens** [comment]
There are several discussions on this error message already. Most encourage you to update your packages, check openssl, and make sure your internet connection is working.

**Comment by jennybc** [comment]
@MichaelChirico Just in general, I'd encourage you to read with googlesheets4. If you have trouble, I am very motivated to hear about it and fix. The new API (+ the new design) offer several ways to make auth aspects less fiddly. I realize your current problem may have its origins elsewhere.

**Comment by jeroen** [comment]
@MichaelChirico do you have this problem only for `googlesheets` or for any https connection? Does this work?

```
req <- curl::curl_fetch_memory("https://google.com")
```

It looks like a problem with your local libcurl installation. What operating system and version of R do you use? Are you perhaps using anaconda?

**Comment by MichaelChirico** [comment]
🤦‍♂️  why yes, in fact `which curl` is on the `conda` path... see `Details` in my post above for my `sessionInfo()`... (`curl::curl_fetch_memory("https://google.com")` fails with the same error so I guess this is not a `googlesheets` problem anyway...). Much thanks @jeroen!

Thanks @jennybc, will try migrating now.
