### ISSUE TITLE
Updating a registered spreadsheet when a new worksheet is added

### ISSUE THREAD

**Issue by mrdwab** [jennybc/googlesheets#138]
Hopefully I'm not missing anything in the docs, but, let's assume that I register a spreadsheet as "mySheet", and then later use something like `gs_ws_new(mySheet, ws_title = "This Is New", input = head(iris))` to add a new worksheet, it would be nice if the registered spreadsheet also gets updated to reflect the addition of this new sheet without me having to re-register it.

**Comment by jennybc** [comment]
The spreadsheet `mySheet` is an R object, so we cannot edit it "in place" when you execute something like `gs_ws_new(mySheet, ws_title = "This Is New", input = head(iris))`. **However**, inside `gs_ws_new(…)`, we do re-register or update the sheet's registration and that is what we return. So you want to have a workflow that looks like this:

```
mySheet <- gs_ws_new(mySheet, ws_title = "This Is New", input = head(iris))
```

That is, store the return value from spreadsheet-editing functions and then continue your work. All the examples in the official help files model this workflow.

Does this help?

**Comment by mrdwab** [comment]
Ahh. I missed that. Yes. That works for me :-) Thanks!
