### ISSUE TITLE
Error in gs_gap_key() : could not find function "get0"

### ISSUE THREAD

**Issue by lawwu** [jennybc/googlesheets#144]
I tried using the sample code to pull in the Gapminder googlesheet:

```
gs_gap() %>% 
  gs_copy(to = "Gapminder")
```
 and ran into this error:

```
Error in gs_gap_key() : could not find function "get0"
```

Anyone else see a similar issue?

**Comment by jennybc** [comment]
What version of R do you have? What happens when you just type `get0` in the R console? It's a base function, so it's odd you don't have it ...

**Comment by jennybc** [comment]
@lawwu Yeah, this is related to your R version. I will do something about this (see #147) but the solution for you in the meantime is to update R.
