### ISSUE TITLE
Renaming a spreadsheet

### ISSUE THREAD

**Issue by smithjd** [jennybc/googlesheets#145]
I don't see a way to rename an existing spreadsheet.  gs_ws_rename() renames a worksheet, but I'd like to rename the spreadsheet itself.

This is a fabulous package, by the Way

**Comment by jennybc** [comment]
Thanks @smithjd. You are correct -- it's not there. Bu easily could be. I'll add it.

**Comment by jennybc** [comment]
Note to self: <https://developers.google.com/drive/v2/reference/files/patch>
