### ISSUE TITLE
"old" Google spreadsheets

### ISSUE THREAD

**Issue by beanumber** [jennybc/googlesheets#148]
Is this a known bug related to the spreadsheet being of the "old" format?

```
> hiv.key <- "pyj6tScZqmEfbZyl0qjbiRQ"
> hiv <- gs_key(hiv.key) %>%
+ gs_read(ws = "Data")
Authentication will not be used.
Worksheets feed constructed with public visibility
Accessing worksheet titled "Data"
Error in gsheets_GET(this_ws$exportcsv, to_xml = FALSE, use_auth = !ss$is_public) : 
  Not expecting content-type to be:
text/html; charset=UTF-8
```

**Comment by jennybc** [comment]
I'm not sure if this is a problem related to being an "old" sheet. But it is a peculiar Sheet. I can read it, but only when I specify some limits.

```
> the_key <- "pyj6tScZqmEfbZyl0qjbiRQ"
> ss <- the_key %>% gs_key(lookup = FALSE)
Authentication will not be used.
Worksheets feed constructed with public visibility
> ss
                  Spreadsheet title: indicator hiv estimated prevalence% 15-49
                 Spreadsheet author: gapdata
  Date of googlesheets registration: 2015-07-07 20:03:53 GMT
    Date of last spreadsheet update: 2013-05-02 10:06:07 GMT
                         visibility: public
                        permissions: rw
                            version: new

Contains 6 worksheets:
(Title): (Nominal worksheet extent as rows x columns)
Data: 276 x 34
About: 24 x 6
Footnotes: 20 x 6
Settings: 20 x 6
Download: 20 x 6
v: 20 x 6

Key: pyj6tScZqmEfbZyl0qjbiRQ
Browser URL: https://docs.google.com/spreadsheets/d/pyj6tScZqmEfbZyl0qjbiRQ/
> ss %>% gs_read()
Accessing worksheet titled "Data"
 Show Traceback
 
 Rerun with Debug
 Error in gsheets_GET(this_ws$exportcsv, to_xml = FALSE, use_auth = !ss$is_public) : 
  Not expecting content-type to be:
text/html; charset=UTF-8 > ss %>% gs_read(range = cell_limits(c(1, 1), c(276, 34)))
Accessing worksheet titled "Data"
Source: local data frame [275 x 34]

   Estimated.HIV.Prevalence.....Ages.15.49.      X1979 X1980 X1981 X1982 X1983
1                                  Abkhazia         NA    NA    NA    NA    NA
2                               Afghanistan         NA    NA    NA    NA    NA
3                     Akrotiri and Dhekelia         NA    NA    NA    NA    NA
4                                   Albania         NA    NA    NA    NA    NA
5                                   Algeria         NA    NA    NA    NA    NA
6                            American Samoa         NA    NA    NA    NA    NA
7                                   Andorra         NA    NA    NA    NA    NA
8                                    Angola 0.02652787    NA    NA    NA    NA
9                                  Anguilla         NA    NA    NA    NA    NA
10                      Antigua and Barbuda         NA    NA    NA    NA    NA
..                                      ...        ...   ...   ...   ...   ...
Variables not shown: X1984 (dbl), X1985 (dbl), X1986 (dbl), X1987 (dbl), X1988
  (lgl), X1989 (lgl), X1990 (dbl), X1991 (dbl), X1992 (dbl), X1993 (dbl), X1994
  (dbl), X1995 (dbl), X1996 (dbl), X1997 (dbl), X1998 (dbl), X1999 (dbl), X2000
  (dbl), X2001 (dbl), X2002 (dbl), X2003 (dbl), X2004 (dbl), X2005 (dbl), X2006
  (dbl), X2007 (dbl), X2008 (dbl), X2009 (dbl), X2010 (dbl), X2011 (dbl)
> ss %>% gs_read(range = cell_limits(c(1, 1), c(276, 34))) %>% View
Accessing worksheet titled "Data"
```

It's very sparsely populated and I am unable to visit it in the browser. What do you know about how it was created?

**Comment by beanumber** [comment]
Nice workaround!

This is the first data set listed in Gapminder: HIV prevalence 
http://spreadsheets.google.com/pub?key=pyj6tScZqmEfbZyl0qjbiRQ&gid=0

**Comment by jennybc** [comment]
Well, you're right, it appears to be an "old" Sheet. For now, hopefully my workaround gets you moving. Am currently on vacation but will take a closer look at why it's hard to read from upon my return.

**Comment by swiftsam** [comment]
Don't interrupt your vacation, but I wanted to add that I'm getting this same error on a very simple and [newly created sheet](https://docs.google.com/spreadsheets/d/1ql5JFrg3mqEy_Kcd1bPXr2699nQWVY8dQXpd0mytcjc/edit#gid=0)

```
> library(googlesheets)
> packageVersion("googlesheets") 
[1] ‘0.1.0.9000’
> 
> sheet <- gs_key("1ql5JFrg3mqEy_Kcd1bPXr2699nQWVY8dQXpd0mytcjc")
Authentication will not be used.
Worksheets feed constructed with public visibility
Error in gsheets_GET(x) : Not expecting content-type to be:
text/html; charset=UTF-8
> 

```

**Comment by jennybc** [comment]
OK yes I get same error with the package and yet can view it in the browser. It's is also not an old sheet. Can you double check it is __published to the web__? Merely being __public on the web__ is not sufficient for API access. I am going to make a new function to test for this! Please see this comment for the distinction:

https://github.com/jennybc/googlesheets/issues/126#issuecomment-118751652

**Comment by swiftsam** [comment]
Ah, publishing to the web solved my problem.  Thanks for the quick fix and sorry to clutter this issue with a different problem!

**Comment by jennybc** [comment]
No problem. I obviously need to write a very specific test for this and then give an informative message :)

**Comment by martinjhnhadley** [comment]
Hi - I have a slightly different example of swiftsam's issue with a new sheet. Evaluating the following directly within RStudio works:

```
dummyProjectDataKey <- "1AKtr1r3MXHyLR8tE3DKBmy6qMuJOsiXd-HyJ0VEPzPk"
dummyProjectDataObject <- googlesheets::gs_key(dummyProjectDataKey)
dummyProjectData <- gs_read(dummyProjectDataObject)
barplot(dummyProjectData$Budget, names.arg = dummyProjectData$Project)
```

However, if I use knit.r to generate a HTML file from a .rmd containing this code I get the same error:

```
Error in gsheets_GET(x) : Not expecting content-type to be:
text/html; charset=UTF-8
```

**Comment by jennybc** [comment]
@martinjhnhadley I got one comment via email, but now don't see it here. Did you delete it and leave the one above (about advice in #126 solving your problem)? Just want to make sure we're all good.

**Comment by martinjhnhadley** [comment]
@jennybc I edited the comment above to say I found the solution to my issue. I was referring to a previous issues thread where you were addressing someone's issue with register_ss but of course I then discovered your "Great Renaming" and that "public on the web" is different from "published on the web". 

Conclusion: we're all good and thanks :)

**Comment by jennybc** [comment]
I haven't struggled with an Old Sheet for a while, so perhaps they are scarce enough I can ignore them. Fingers crossed.
