### ISSUE TITLE
Link to open-cpu?

### ISSUE THREAD

**Issue by vnijs** [jennybc/googlesheets#150]
As of 2022-02-03, the googlesheets package has been archived on CRAN.
I'm closing all issues and pull requests prior to archiving this GitHub repo.

Learn more at:

<https://github.com/jennybc/googlesheets#readme>

**Comment by jennybc** [comment]
Thanks for the kind words!

Re: feasibility of calling R from a Google Sheet, I have no idea. I assume that would involve Google Apps Scripting? Will be interested to see if @jeroenooms sees a possible connection ...

https://developers.google.com/apps-script/guides/sheets
