### ISSUE TITLE
Provide access to formulas and raw (not formatted) numbers

### ISSUE THREAD

**Issue by jennybc** [jennybc/googlesheets#152]
http://stackoverflow.com/questions/31520605/read-cell-values-without-formatting-into-r-with-googlesheets

**Comment by jennybc** [comment]
in the course of answering that question, I made this Sheet:

https://docs.google.com/spreadsheets/d/19lRTCJDf9BYz9JepHx7y6u8vcxGbFpVSfIuxXnWpsL0/

register it like so:

```r
ss <- gs_title("commas-and-percents")
```

**Comment by jennybc** [comment]
The definitive way to address this is probably to consult `inputValue` (where formulas show up) and `numericValue` (where unformatted numbers show up) in the `cell` node of the `entry` nodes. Which means it's connected to formulas and #18.

**Comment by jennybc** [comment]
@EricGoldsmith I know you care about this because of your stackoverflow question. Here is rather raw cell feed data from [the Sheet mentioned above](https://docs.google.com/spreadsheets/d/19lRTCJDf9BYz9JepHx7y6u8vcxGbFpVSfIuxXnWpsL0/).

```
Source: local data frame [16 x 7]

    cell cell_alt   row   col       cell_text      inputValue numericValue
   (chr)    (chr) (int) (int)           (chr)           (chr)        (chr)
1     A1     R1C1     1     1          Number          Number           NA
2     B1     R1C2     1     2  Number_wFormat  Number_wFormat           NA
3     C1     R1C3     1     3         Percent         Percent           NA
4     D1     R1C4     1     4 Percent_wFormat Percent_wFormat           NA
5     A2     R2C1     2     1          123456          123456     123456.0
6     B2     R2C2     2     2         123,456      =R[0]C[-1]     123456.0
7     C2     R2C3     2     3          0.1234          0.1234       0.1234
8     D2     R2C4     2     4          12.34%      =R[0]C[-1]       0.1234
9     A3     R3C1     3     1          123457          123457     123457.0
10    B3     R3C2     3     2         123,457      =R[0]C[-1]     123457.0
11    C3     R3C3     3     3          0.2345          0.2345       0.2345
12    D3     R3C4     3     4          23.45%      =R[0]C[-1]       0.2345
13    A4     R4C1     4     1          123458          123458     123458.0
14    B4     R4C2     4     2         123,458      =R[0]C[-1]     123458.0
15    C4     R4C3     4     3          0.3456          0.3456       0.3456
16    D4     R4C4     4     4          34.56%      =R[0]C[-1]       0.3456
```

right now I am returning `cell_text` (the "literal value" described below). But the XML element attributes also contain `inputValue` and, optionally, `numericValue`. I'm going to ponder what to return and/or what choices to expose in `gs_read_cellfeed()`. But feel free to express on opinion here too. That goes for anyone listening or stumbling across this.

From the official API docs, here's a description of [where info is in the cell feed](https://developers.google.com/google-apps/spreadsheets/data#work_with_cell-based_feeds):

> The `inputValue` attribute of a cell entry always contains the value that a user would otherwise type into the Google Sheets user interface to manipulate the cell (i.e. either a literal value or a formula). To set a formula or a literal value on a cell, provide the text of the formula or value as the inputValue attribute. Remember that formulas must start with = to be considered a formula. If a cell contains a formula, the formula is always provided as the `inputValue` when cell entries are returned by the API.
>
> The `numericValue` attribute of a cell entry, when present, indicates that the cell was determined to have a numeric value, and its numeric value is indicated with this attributed.
>
> The literal value of the cell element is the calculated value of the cell, without formatting applied. If the cell contains a formula, the calculated value is given here. The Sheets API has no concept of formatting, and thus cannot manipulate formatting of cells.

**Comment by jennybc** [comment]
@jrsosen48 Do you care to weigh in here? Your issue (#18) and this one are clearly converging.

**Comment by jennybc** [comment]
@jrosen48 Do you care to weigh in here? Your issue (#18) and this one are clearly converging.

**Comment by EricGoldsmith** [comment]
Patterning after the existing parameters for `gs_read_cellfeed()`, perhaps:

`return_formats` - logical; for numeric values, indicates whether to return values with cell formatting applied (TRUE), or only the numeric value (FALSE)
`return_formulas` - logical; indicates whether to return the text of any cell formulas

**Comment by jennybc** [comment]
@EricGoldsmith You can now install from the `formulas` branch and try out the new ability to get data without numeric formatting applied.

You can read a [draft vignette](https://github.com/jennybc/googlesheets/blob/formulas/vignettes/formulas-and-formatting.md) and/or just try it out.

``` r
## devtools::install_github("jennybc/googlesheets@formulas")
library(googlesheets)
suppressMessages(library(dplyr))
## a sheet I've created w/ formatting and formula challenges
## subsitute your own sheet here?
ffs <- gs_key("19lRTCJDf9BYz9JepHx7y6u8vcxGbFpVSfIuxXnWpsL0", lookup = FALSE)
#> Worksheets feed constructed with public visibility
## go look at it?
## gs_browse(ffs)

## prove you can consume it the normal way
(ffs_read_csv <- gs_read_csv(ffs, verbose = FALSE))
#> No encoding supplied: defaulting to UTF-8.
#> Source: local data frame [5 x 5]
#> 
#>   Number Number_wFormat Character     Formulas Formula_wFormat
#>    (int)          (chr)     (chr)        (chr)           (chr)
#> 1 123456        654,321       one       Google        3.18E+05
#> 2 345678         12.34%        NA 1,271,591.00          52.63%
#> 3 234567       1.23E+09     three           NA            0.22
#> 4     NA          3 1/7      four         $A$1      123,456.00
#> 5 567890          $0.36      five           NA         317,898

## consume all of it but strip numeric formatting before type conversion
ffs %>% gs_read(literal = FALSE, verbose = FALSE)
#> Source: local data frame [5 x 5]
#> 
#>   Number Number_wFormat Character  Formulas Formula_wFormat
#>    (int)          (dbl)     (chr)     (chr)           (dbl)
#> 1 123456   6.543210e+05       one    Google    3.178978e+05
#> 2 345678   1.234000e-01        NA 1271591.0    5.263144e-01
#> 3 234567   1.234568e+09     three        NA    2.173942e-01
#> 4     NA   3.141593e+00      four      $A$1    1.234560e+05
#> 5 567890   3.600000e-01      five        NA    3.178978e+05

## consume some of it and get a data frame
ffs %>%  gs_read(range = cell_cols("D:E"), literal = FALSE, verbose = FALSE)
#> Source: local data frame [5 x 2]
#> 
#>    Formulas Formula_wFormat
#>       (chr)           (dbl)
#> 1    Google    3.178978e+05
#> 2 1271591.0    5.263144e-01
#> 3        NA    2.173942e-01
#> 4      $A$1    1.234560e+05
#> 5        NA    3.178978e+05

## consume some of it and make an atomic vector
ffs %>%
  gs_read_cellfeed(range = cell_cols(2), verbose = FALSE) %>%
  gs_simplify_cellfeed(literal = FALSE)
#>           B2           B3           B4           B5           B6 
#> 6.543210e+05 1.234000e-01 1.234568e+09 3.141593e+00 3.600000e-01
```

**Comment by EricGoldsmith** [comment]
This looks good to me. Thanks for implementing.

**Comment by jennybc** [comment]
@EricGoldsmith Have you actually tried it? Or are you looking at what I showed above. No hard feelings either way, but I'm just curious. Still some work to do before I will merge it in, so input now is most welcome!

**Comment by EricGoldsmith** [comment]
Yes, I actually tried it :-) Numbers with various formatting applied (e.g. comma separators, percentage, etc.) are being read correctly with the `literal = FALSE` argument.
