### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by kenarab** [jennybc/googlesheets#154]
I have installed googlesheets in my computer. But when I try to install it on an Ubuntu server machine, the package don't seems to load.

```
install.packages("googlesheets")
also installing the dependencies 'colorspace', 'RColorBrewer', 'dichromat', 'munsell', 'labeling', 'assertthat', 'R6', 'Rcpp', 'magrittr', 'lazyeval', 'DBI', 'BH', 'digest', 
'gtable', 'reshape2', 'scales', 'proto', 'jsonlite', 'mime', 'curl', 'stringi', 'cellranger', 'dplyr', 'ggplot2', 'httr', 'plyr', 'stringr', 'tidyr', 'XML', 'xml2'
```

But when I want to use it:
```
> library("googlesheets")
> authorize()
Error: could not find function "authorize"
```
Or executing my own, the same:
```
Error in self$loadSpecification() : could not find function "register_ss"
```

I tried executing it as a superuser but it doesn't works. Any idea? Didn't see the problem anywhere in the web.

Best, Alejandro.

**Comment by jennybc** [comment]
There is no function called `authorize()` or `register_ss()`. There was A Great Renaming of things several months ago. Please see the current README or vignette for a good intro to the name scheme and usage.

Where did you find these functions? I'd like to try to update those materials.

Thanks for the report and let me know if troubles continue.

**Comment by kenarab** [comment]
ok! That's was the problem.
authorized=> gs_auth()
register_ss=>gs_url()  in my case.

Making the migration of code.

Thnks!

2015-07-31 16:00 GMT-03:00 Jennifer (Jenny) Bryan <notifications@github.com>
:

> There is no function called authorize() or register_ss(). There was A
> Great Renaming of things several months ago. Please see the current README
> or vignette for a good intro to the name scheme and usage.
>
> Where did you find these functions? I'd like to try to update those
> materials.
>
> Thanks for the report and let me know if troubles continue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jennybc/googlesheets/issues/154#issuecomment-126785365>
> .
>



-- 
 alejandro baranek
@ken4rab <https://twitter.com/ken4rab>
qbotics <http://qbotics.tumblr.com/> | surferinvaders
<http://surferinvaders.tumblr.com> | algebraic-soundscapes
<http://imaginary.org/content/algebraic-soundscapes> | surfer-shuffle
<http://imaginary.org/program/surfer-shuffle>

**Comment by jennybc** [comment]
Great! Closing this.

But would really love to know where you saw `authorize()` and `register_ss()` so I can suggest an update. Maybe it will save someone else same frustration.

**Comment by jennybc** [comment]
Oh I see, maybe you wrote some code a while back and are just firing it up again and having to update to new names? If so, just ignore above request.

**Comment by kenarab** [comment]
Exactly:

I made the implementation in April and in my machine didn't update the
package to official CRAN, but when implemented in a server, the problem
appeared. I thought it was a problem of privileges. As I had authorize in
the documentation of googlesheets didn't take into account the possibility
of an outdated code.

Best, Ale.

2015-07-31 18:51 GMT-03:00 Jennifer (Jenny) Bryan <notifications@github.com>
:

> Oh I see, maybe you wrote some code a while back and are just firing it up
> again and having to update to new names? If so, just ignore above request.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jennybc/googlesheets/issues/154#issuecomment-126821603>
> .
>



-- 
 alejandro baranek
@ken4rab <https://twitter.com/ken4rab>
qbotics <http://qbotics.tumblr.com/> | surferinvaders
<http://surferinvaders.tumblr.com> | algebraic-soundscapes
<http://imaginary.org/content/algebraic-soundscapes> | surfer-shuffle
<http://imaginary.org/program/surfer-shuffle>
