### ISSUE TITLE
export of functions in R/permissions.R

### ISSUE THREAD

**Issue by mwhitaker** [jennybc/googlesheets#155]
Hi Jenny,

Thanks for a great package! Any reason why the functions in permissions.R are not exported? I'd find it really useful to be able to set and edit permissions on sheets. As far as I can tell via googlesheets::: they work fine.

Many thanks,
Michael

**Comment by jennybc** [comment]
Thanks @mwhitaker!

The only reason is that I hadn't really figured out what sort of interface to put on them. Yes they do work. I even have them under testing. I'm happy to work towards exporting that functionality. What sorts of things do you want to do? That would be helpful to know.

The original reason for creation is to expost some of that functionality when creating a new Sheet, i.e. make it possible to create and set desired permissions all at once.

**Comment by mwhitaker** [comment]
I have a number of clients that receive automated reports generated in R and I am considering sharing these reports via Google Sheets (as opposed to sending csv or pdf files). I keep my client list in a sheet/spreadsheet and it would be easier and less error-prone to manage permissions via googlesheets when clients are added or deleted, rather than through the Drive UI. The client list is quite dynamic, so I have to automate the permissions.

I did modify some of your permissions functions in order to create and set permissions on **folders** in Drive. That way I could add pdf reports *and* googlesheets, which inherent the permissions of the folder. This may be beyond the scope of googlesheets and I am still not sure what a good process is for managing sheets that are shared with lots of people.

In any case, the permission functions have been really helpful in letting me try out some approaches.
