### ISSUE TITLE
Error in tag$name : object of type 'closure' is not subsettable

### ISSUE THREAD

**Issue by samhalluk** [jennybc/googlesheets#158]
Hi jennybc,

Really like the googlesheets package. I'm trying to adapt your shiny auth functions to work with an app I'm building that pulls some basic profile information from the users google account. However even when using your gs_webapp_get_token function() I'm debugging and as I'm about to exit the function i get an error `Error in tag$name : object of type 'closure' is not subsettable`.

I appreciate that this is error occurs when a function is indexed but I am completely lost to where the tag$name is being mentioned in the gs_webapp_get_token...seems like a shiny function `tags` to me...

If you have any ideas to why this is happening they would be very much appreciated!

**Comment by jennybc** [comment]
Hi @samhalluk,

Just so I'm clear, are you having trouble building an app that uses `googlesheets`? Or are you building an app that doesn't use `googlesheets` but does something google-y and you're using our auth functions as inspiration?

Either way, is the code for this app on github somewhere?

**Comment by samhalluk** [comment]
Hi Jenny,

I started by using your your package but wanted to get to grips with what the functions actually did to understand the Oauth dance. Using your package and when I use the functions manually (as inspiration i.e. without attaching googlesheets) I'm getting this error. It could be such a trivial problem hah!  Here is the code I'm using I mainly based it on your gs-explorer example and mark edmondson's last issue too.

```
#ui.r
library(shiny)
library(shinyBS)

shinyUI(fluidPage(
  uiOutput("loginButton"),
  uiOutput("logoutButton"),
  bsTooltip("loginButton","Clicking this actionLink will call the gs_webapp_auth_url() function"),
  bsTooltip("logoutButton","Logging out will direct you to the original url and also the token can be revoked!"),
  uiOutput("info")
  
))



# This is the server logic for a Shiny web application.
# You can find out more about building applications with Shiny here:
#
# http://shiny.rstudio.com
#

library(shiny)
library(httr)
library(shinydashboard)
library(shinyBS)
library(jsonlite)

#server.r

#Just contains the options credentials to store id secret and redirect url in the environment
source("auth.r")

shinyServer(function(input, output, session) {

  message("New Shiny Session- ", Sys.time())
 


  
  ## Make a button to link to Google auth screen
  ## If auth_code is returned then don't show login button
  output$loginButton <- renderUI({
    if(is.null(isolate(access_token()))) {
      actionLink("loginButton",
                   label = a("Authorize App", href = gs_webapp_auth_url()),icon = icon("google-plus-square"))
      
    } else {
      return()
    }
  })
  
  
  
  output$logoutButton <- renderUI({
    if(!is.null(access_token())) {
      # Revoke the token too? use access_token$revoke()
      actionLink("logoutButton",
                   label = a("Logout of google",
                             href = uri),icon=icon("caret-square-o-left"))
    } else {
      return()
    }
  })
  
  
  
  ## Get auth code from return URL
  access_token  <- reactive({
    ## gets all the parameters in the URL. The auth code should be one of them.
    pars <- parseQueryString(session$clientData$url_search)
    
    if(length(pars$code) > 0) {
      ## extract the authorization code
      gs_webapp_get_token(auth_code = pars$code)
    } else {
      NULL
    }
  })
  

  output$info <- renderUI({
    if(!is.null(access_token())) {
      # Revoke the token too? use access_token$revoke()
      textOutput("info")
      output$info<-renderText({"The access_token() function in server.R is used to extract the authorization code in the url for use when asking google for a token"})
    } else {
      return()
    }
  })
  
  
 
  
})    


```

So if you run it with your own credentials the app works fine! It's just this error that's causing the token to be incorrectly stored so I can't make my own API calls.
