### ISSUE TITLE
gs_edit_cells() succeeds but does not appear [value restriction?]

### ISSUE THREAD

**Issue by chartgerink** [jennybc/googlesheets#159]
Upon trying to write data to a new worksheet, it does not work if I try to write an entire data.frame (84 rows, 4 columns). It does work if I select at most 23 of the rows (96 values). The console does say it is successful when I try to write the entire data.frame to the worksheet.

`> gs_url(link) %>% gs_edit_cells(ws = "coding",
+                                input = dat,
+                                anchor = "A1", byrow = TRUE)
Sheet-identifying info appears to be a browser URL.
googlesheets will attempt to extract sheet key from the URL.
Putative key: 1OXMHv6lal_GiMneW4xHa2wvG4BzTyD41zcCnmfF6PUY
Authentication will be used.
Sheet successfully identifed: "#icanhazpdf"
Range affected by the update: "A1:D85"
Worksheet "coding" successfully updated with 340 new value(s).`

Is there a restriction on how many values can be written back to GSheets?

**Comment by jennybc** [comment]
I'm going to take a look at various issue here soon but can't today. I haven't tried anything myself yet or even revisited my own code!

Are you perhaps falling off the edge of the sheet? Is is stopping when it hits the current max number of rows or columns? And maybe I handle the need to resize more elegantly when you're uploading the entire data.frame vs editing some cells in place? That would be helpful to know.

**Comment by chartgerink** [comment]
Hi Jenny,

Thanks for the reply. The dataframe is not larger than the sheet (both rows and columns), so I do not really know where this problem originates from. I will find another way to write my data back in batches for now.

Chris

**Comment by jennybc** [comment]
If it possible to share anything that helps me reproduce privately (jenny@stat.ubc.ca), I'm willing to dig deeper. You could share the Sheet and/or data. Otherwise, I don't have much to go on re: troubleshooting.

**Comment by chartgerink** [comment]
Of course, my apologies. You can find the sheet i was using [here](https://docs.google.com/spreadsheets/d/1OXMHv6lal_GiMneW4xHa2wvG4BzTyD41zcCnmfF6PUY/edit?usp=sharing) with the following code.

```if(!require(devtools)){install.packages('devtools')}
if(!require(magrittr)){install.packages('magrittr')}
if(!require(curl)){install.packages('curl')}
if(!require(googlesheets)){install_github('jennybc/googlesheets')}
library(devtools)
library(magrittr)
library(curl)
library(googlesheets)


link = "https://docs.google.com/spreadsheets/d/1OXMHv6lal_GiMneW4xHa2wvG4BzTyD41zcCnmfF6PUY/edit?usp=sharing"
dat <- gs_url(link) %>% gs_read_csv(ws = "raw")

# Remove all missing `firsturl` (August 19, 2015; remark 1)
missing.firsturl <- grep("ifttt.com/missing_link", dat$firsturl)
dat$firsturl[missing.firsturl] <- NA

# Remove duplicates (August 18, 2015; remark 2)
dat <- dat[!duplicated(dat$twt), ]
# Remove retweets (August 18, 2015; remark 3)
dat <- dat[!grepl(pattern = "RT @.*: .*", dat$twt), ]

# Remove all tweets that are no request (August 18, 2015; remark 3)
dat <- dat[dat$request == 1, ]
# Remove the $request
dat <- dat[, -dim(dat)[2]]

gs_url(link) %>% gs_edit_cells(ws = "coding",
                               input = dat,
                               anchor = "A1", byrow = TRUE)
