### ISSUE TITLE
make gs_add_row() less stupid

### ISSUE THREAD

**Issue by jennybc** [jennybc/googlesheets#160]
To append a new row via the list feed, a header row of variable names must be present.

Right now, `gs_add_row()` is such a thin wrapper that it also will not work unless this is true. I.e. you cannot just starting adding rows to a blank sheet.

`gs_add_row()` should detect the lack of header row and just do something sensible.

**Comment by trinker** [comment]
Is there a way to add rows to a blank sheet other than with `gs_add_row`?

**Comment by jennybc** [comment]
Well, there's `gs_ws_new()` if you're willing to create a new sheet. And you can upload data at that time as well.

But if you've already got a blank sheet sitting there, no, at this point you'd need to use `gs_edit_cells()` to populate a header row, then have at it with `gs_edit_cells()` or `gs_add_row()`.
