### ISSUE TITLE
Understand where the "copy / paste token" auth flow comes from

### ISSUE THREAD

**Issue by jennybc** [jennybc/googlesheets#164]
I've gotten vague references to this from users in the past but those folks had bigger problems/questions... However now I see this unfamiliar auth flow mentioned in @andrie's [blog post about `googlesheets`](http://blog.revolutionanalytics.com/2015/09/using-the-googlesheets-package-to-work-with-google-sheets.html):

> The package neatly handles handshaking with Google to get access to your authorisation token. It automatically opens a web browser where you log in to your Google account. Google then presents you with a token that you simply paste into your R session command line, and from there everything just works.

What is he talking about with pasting of the token at the R command line?!? For me, I just authorize the app to do certain things and get a terse message to go back to R.

In what scenario(s) does this happen? Is it an auth flow built into `httr`? I suppose it must be ...
cc @hadley

**Comment by jennybc** [comment]
Am learning this happens when `httpuv` not installed and out-of-band authentication happens....

**Comment by andrie** [comment]
Yes, agreed. I had a message saying `httpuv not installed, defaulting to ...` some default I can't remember the name of. Perhaps you could include `httpuv` as an Imports?
