### ISSUE TITLE
Write up token storage and activation for non-interactive use

### ISSUE THREAD

**Issue by jennybc** [jennybc/googlesheets#165]
Just fired this off in an email reply. Maybe develop into a vignette?

Q: Is there a way to automatically retrieve or permanently store the authorization token?  For instance, if I had the code in a script that I wanted to source, would I be able to do that without manually visiting the authorization site and copy/pasting the token back into R?

Answer:

Interactively:

``` r
library(googlesheets)
# do something that will verify you are in or will get you into an authorized state, such as gs_ls()
# save the current token explicitly to file like so:
token <- gs_auth()
saveRDS(token, file = “googlesheets_token.rds”)
```

Then put this file wherever you need to. But treat it with care, it carries a token with the authority to do certain stuff on Google Drive on your behalf and it’s not, like, encrypted, or anything. For example, do not put it on GitHub; within a GitHub repo, you should list `googlesheets_token.rds` in `.gitignore`.

In a script, bring that token into force and you should be good to go:

``` r
gs_auth(token = "googlesheets_token.rds”)
```

Or, more, quietly:

``` r
suppressMessages(gs_auth(token = "googlesheets_token.rds", verbose = FALSE))
```

**Comment by jennybc** [comment]
Done in 837fed540fd6bdb24386b1de15139daf252f8d75

**Comment by rkrug** [comment]
This works perfectly, but is there a way of storing the token in an environmental variable? The scenario would be to run code on travis-ci which than could use the token as an encrypted environmental variable to authenticate.

**Comment by jennybc** [comment]
FYI this package is very much in "maintenance mode" and I'm actively working on its successor [googlesheets4](https://github.com/tidyverse/googlesheets4), which is supported by the [gargle](https://github.com/r-lib/gargle) package for handling auth (and other things) across multiple Google APIs.

In general, NO this OAuth token is not well suited to storage in an env var because, at the very least, it consists of two pieces of information, an access token and a refresh token. Not to mention all sort of other info (OAuth endpoint, OAuth app, etc.).

For non-interactive use, you are much better off to use a service account token and, in the new gargle-supported world, that workflow will be strongly encouraged (over gymnastics with OAuth tokens, which remains *possible*).
