### ISSUE TITLE
R Markdown, gs_url, private sheet

### ISSUE THREAD

**Issue by hardin47** [jennybc/googlesheets#166]
I'm trying to use the gs_url command to download a googlesheet.  The problem is that I have to interactively authenticate the googlesheet.  But I want to use the command within an R Markdown file (which needs to run independently of any interactivity from the user).  Is there any work around to this?  Thanks for any help!!  It's the second command that won't work.

drinks_url = "https://docs.google.com/spreadsheets/d/1KYMUjrCulPtpUHwep9bVvsBvmVsDEbucdyRZ5uHCDxw/edit?hl=en_GB#gid=0"

drinks = gs_url(drinks_url, visibility="private")

**Comment by jennybc** [comment]
I recently explained this for someone else via email and have parked the info in #165. I intend to turn it into a vignette or something. But please see if those instructions work for you in the meantime. They did for the other guy :)

PS The whole thing runs more smoothly if you have `httpuv` installed, in that the initial Google authentication is less interactive re: copying and pasting a token. If you have no idea what I'm talking about, that means you already have `httpuv` installed and you can ignore this PS.

**Comment by hardin47** [comment]
Yes, that worked!  Thank you so much for the help.  Love you googlesheets package.  It has really revolutionized how I can teach.  I'm finally able to get my students to really interact with dynamic data on a regular basis.

-Jo

--
Jo Hardin
Professor & Chair, Department of Mathematics
Pomona College
610 N. College Ave.
Claremont, CA 91711
909-607-8717
jo.hardin@pomona.edu<mailto:jo.hardin@pomona.edu>
http://research.pomona.edu/johardin<http://pages.pomona.edu/~jsh04747>

**Comment by jennybc** [comment]
Great!

BTW I'd love to hear more about how you are using `googlesheets` in the classroom. Either here or via email (jenny@stat.ubc.ca) or ... if you're course is online, I could check out a link.

**Comment by hardin47** [comment]
Hi, again,

I’m now working from my PC and having even worse problems.  It won’t let me authenticate even interactively (so I can’t do gs_auth()).  Any thoughts about using a PC?

> token <- gs_auth()
Error in gdrive_GET("https://www.googleapis.com/drive/v2/about") :
  client error: (401) Unauthorized
> drinks_url = "https://docs.google.com/spreadsheets/d/1KYMUjrCulPtpUHwep9bVvsBvmVsDEbucdyRZ5uHCDxw/edit?hl=en_GB#gid=0"
> drinks = gs_url(drinks_url, visibility="private")
Sheet-identifying info appears to be a browser URL.
googlesheets will attempt to extract sheet key from the URL.
Putative key: 1KYMUjrCulPtpUHwep9bVvsBvmVsDEbucdyRZ5uHCDxw
Authentication will be used.
Error in gsheets_GET(the_url) : client error: (401) Unauthorized

Thanks a million!!!

-Jo

p.s.  As soon as I get this assignment finished and written up, I promise to send it to you!

**Comment by hardin47** [comment]
Ok, I’m not sure how it got fixed.  I just kept trying various things.  So sorry to bug you about this.  It is all good for now!

Jo Hardin
Professor & Chair, Department of Mathematics
Pomona College
610 N. College Ave.
Claremont, CA 91711
909-607-8717
jo.hardin@pomona.edu<mailto:jo.hardin@pomona.edu>
http://research.pomona.edu/johardin<http://pages.pomona.edu/~jsh04747>


From: Johanna Hardin
Sent: Monday, September 07, 2015 4:08 PM
To: 'jennybc/googlesheets'
Subject: RE: [googlesheets] R Markdown, gs_url, private sheet (#166)

Hi, again,

I’m now working from my PC and having even worse problems.  It won’t let me authenticate even interactively (so I can’t do gs_auth()).  Any thoughts about using a PC?

> token <- gs_auth()
Error in gdrive_GET("https://www.googleapis.com/drive/v2/about") :
  client error: (401) Unauthorized
> drinks_url = "https://docs.google.com/spreadsheets/d/1KYMUjrCulPtpUHwep9bVvsBvmVsDEbucdyRZ5uHCDxw/edit?hl=en_GB#gid=0"
> drinks = gs_url(drinks_url, visibility="private")
Sheet-identifying info appears to be a browser URL.
googlesheets will attempt to extract sheet key from the URL.
Putative key: 1KYMUjrCulPtpUHwep9bVvsBvmVsDEbucdyRZ5uHCDxw
Authentication will be used.
Error in gsheets_GET(the_url) : client error: (401) Unauthorized

Thanks a million!!!

-Jo

p.s.  As soon as I get this assignment finished and written up, I promise to send it to you!

**Comment by jennybc** [comment]
Glad it worked out. Because tokens are, by default, automatically cached, it means if the process goes off the rails in the middle, it is possible to cache an *invalid* token. Which is possibly what you experienced.

In future, if you don't seem to be authenticated, but you are also not being presented with the option to re-authenticate, do `gs_auth(new_user = TRUE)` to force a fresh authentication sequence and retrieve a shiny new token.

**Comment by hardin47** [comment]
Yes, I'm sure that is what happened (because I had to also do some closing/restarting of Rstudio, etc.).  Good to know the gs_auth(new_user = TRUE)  trick.

Thanks, Jo

--
Jo Hardin
Professor & Chair, Department of Mathematics
Pomona College
610 N. College Ave.
Claremont, CA 91711
909-607-8717
jo.hardin@pomona.edu<mailto:jo.hardin@pomona.edu>
http://research.pomona.edu/johardin<http://pages.pomona.edu/~jsh04747>

**Comment by jennybc** [comment]
When you're on auto-pilot and all is well, the token is cached in current working directory to a file called `.httr-oauth`. It can be rather invisible -- by design! -- but it also means if you get into a weird state it can be hard to get out. So `gs_auth(new_user = TRUE)` is the equivalent of power-cycling with respect to your Google authentication. Under the hood, it deletes the `.httr-oauth` file, which forces authentication to begin anew. Possibly more than you wanted to know :grimacing:.

**Comment by hardin47** [comment]
Thanks again for all your help.  The assignment is at:

http://pages.pomona.edu/~jsh04747/courses/math154/Math154_HW2_viz.pdf
--
Jo Hardin
Professor & Chair, Department of Mathematics
Pomona College
610 N. College Ave.
Claremont, CA 91711
909-607-8717
jo.hardin@pomona.edu<mailto:jo.hardin@pomona.edu>
http://research.pomona.edu/johardin<http://pages.pomona.edu/~jsh04747>

**Comment by lawwu** [comment]
I seem to be running into a similar issue with the error:
Error in gdrive_GET("https://www.googleapis.com/drive/v2/about") : 
  client error: (403) Forbidden

I also get a similar error when I try to run:
gs_auth(new_user = TRUE)

The output I get from running gs_auth is
Removing old credentials ...
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Authentication complete.
Error in gdrive_GET("https://www.googleapis.com/drive/v2/about") : 
  client error: (403) Forbidden

Does this have to do with firewall issues? 
I can still successfully authenticate with google sheets with a cached .httr-oauth token that I generated a month ago if I'm in an interactive mode though.

**Comment by hardin47** [comment]
Another thing I figured out...  if you do gs_auth(new_user=TRUE) in the console, you must do it within the same directory where your markdown file lives.

**Comment by jennybc** [comment]
Yes @hardin47 's point about working directory is EXTREMELY IMPORTANT.

I've just written a vignette with all the gory details of token management. You don't need to read the whole thing but there are a couple of sections near the front that deal with your scenarios, I think:

https://github.com/jennybc/googlesheets/blob/master/vignettes/managing-auth-tokens.md

However, I'm still puzzled by some of what you two report above with 403 errors after what appears to be successful authentication. I will look into it further. If these problems go away w/ real discipline around working directory and `gs_auth(new_user = TRUE)`, please let me know so I can stop worrying.

**Comment by KaneMerrillR** [comment]
I CANNOT tell you how thankful I am to have found this. I was struggling with the same problem and using gs_auth(new_user=TRUE) allowed me to solve the problem. Thank you so much for this!

**Comment by lawwu** [comment]
@jennybc I still happen to be running into the issue I raised back in October. I'm needing to save the token in an .rds file for non-interactive use (cron job) but I run into this error when I try to run this line of code:


> token <- gs_auth(new_user = TRUE)
Removing old credentials ...
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Authentication complete.
Error in gdrive_GET("https://www.googleapis.com/drive/v2/about") : 
  client error: (403) Forbidden
> token <- gs_auth()
Error in gdrive_GET("https://www.googleapis.com/drive/v2/about") : 
  client error: (403) Forbidden

Am I missing something?

**Comment by jennybc** [comment]
Will I confirm my understanding of the above?

You submit `token <- gs_auth(new_user = TRUE)` and are kicked into the browser. You see a screen asking your permission for us to do Sheet and Drive stuff. You accept. You get a message about successful authentication and you can return to R.

But back in R ... you immediately start seeing these 403 errors from the Drive API?

If any of that is not accurate, please correct me.

Is there any chance you have an unusual relationship with Google and somehow use Sheets but not Drive? From the errors, I can tell the problem is when I go to retrieve some info on you as a Drive user. I don't even know if such weirdness is possible.

You might also want to just reinstall `googlesheets` from GitHub, as I've recently changed how I specify the scopes for the Drive API and there's some chance that will help.

**Comment by lawwu** [comment]
You exactly described my situation. It's very odd because the .httr-oauth file is generated successfully but for some reason R just isn't able to save it to a named variable.

I tried again this morning after rebooting. I tried clearing cookies/browsing history. I also tried reinstalling googlesheets. Is the version from github version 0.1.0.9001?

**Comment by jennybc** [comment]
Did you try re-installing `googlesheets` from GitHub? That would be interesting.

What happens when you visit: <https://drive.google.com/drive/my-drive>? Please make sure you're logged in as the relevant Google user (look in upper right corner). Can you work with Google Drive normally from the browser?

**Comment by lawwu** [comment]
I ran those two lines and here's what came back:
```
> devtools::install_github("jennybc/googlesheets")
Downloading GitHub repo jennybc/googlesheets@master
from URL https://api.github.com/repos/jennybc/googlesheets/zipball/master
Installing googlesheets
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore CMD INSTALL  \
  '/private/var/folders/3w/048fn6bj1jx1qnkkgv4lnrsm0000gp/T/RtmpSN8fDz/devtools24525d8d5e4/jennybc-googlesheets-2894d77'  \
  --library='/Library/Frameworks/R.framework/Versions/3.2/Resources/library' --install-tests 

* installing *source* package ‘googlesheets’ ...
** R
** inst
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (googlesheets)
Reloading installed googlesheets
> devtools::session_info("googlesheets")
Session info ----------------------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.2.3 (2015-12-10)
 system   x86_64, darwin13.4.0        
 ui       RStudio (0.99.878)          
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/Los_Angeles         
 date     2016-02-15                  

Packages --------------------------------------------------------------------------------------------------------------------------------------------------
 package      * version    date       source                               
 assertthat     0.1        2013-12-06 CRAN (R 3.2.0)                       
 BH             1.58.0-1   2015-05-21 CRAN (R 3.2.0)                       
 cellranger     1.0.0      2015-06-20 CRAN (R 3.2.0)                       
 curl           0.9.5      2016-01-23 CRAN (R 3.2.3)                       
 DBI            0.3.1      2014-09-24 CRAN (R 3.2.0)                       
 dplyr        * 0.4.3      2015-09-01 CRAN (R 3.2.0)                       
 googlesheets * 0.1.0.9001 2016-02-15 Github (jennybc/googlesheets@2894d77)
 httr         * 1.1.0      2016-01-28 CRAN (R 3.2.3)                       
 jsonlite     * 0.9.19     2015-11-28 CRAN (R 3.2.2)                       
 lazyeval       0.1.10     2015-01-02 CRAN (R 3.2.0)                       
 magrittr       1.5        2014-11-22 CRAN (R 3.2.0)                       
 mime           0.4        2015-09-03 CRAN (R 3.2.0)                       
 openssl        0.9.1      2016-01-18 CRAN (R 3.2.3)                       
 plyr         * 1.8.3      2015-06-12 CRAN (R 3.2.0)                       
 R6             2.1.2      2016-01-26 CRAN (R 3.2.3)                       
 Rcpp           0.12.3     2016-01-10 CRAN (R 3.2.3)                       
 readr          0.2.2      2015-10-22 CRAN (R 3.2.0)                       
 stringi        1.0-1      2015-10-22 CRAN (R 3.2.0)                       
 stringr        1.0.0      2015-04-30 CRAN (R 3.2.0)                       
 tidyr          0.4.1      2016-02-05 CRAN (R 3.2.3)                       
 XML            3.98-1.3   2015-06-30 CRAN (R 3.2.0)                       
 xml2           0.1.2      2015-09-01 CRAN (R 3.2.0)      
```   


I also did visit https://drive.google.com/drive/my-drive. Confirming that I can open different sheets and docs with my corporate Google account. When R pops me into Google Chrome to do the authentication I do need to select which Google account to use but I am selecting the correct corporate account.

Odd huh?

**Comment by jennybc** [comment]
> correct corporate account

I do wonder if the behaviour of such an account differs from whatever the rest of us have. Like maybe the endpoint I use to look up display name, etc. simply does not work?

Do you have a second **non-corporate** account? Or are you willing to make one? It would be very interesting to see if you have the same problem with it.

**Comment by lawwu** [comment]
I think you're on to something. I tried with my personal Google account without any hiccups.

```
> library(googlesheets)
> token <- gs_auth(new_user = TRUE)
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Authentication complete.
```

**Comment by lawwu** [comment]
And this token also works in a cron that I just ran... it must be an issue with a corporate google domain.

**Comment by jennybc** [comment]
I'm glad we identified the problem!

I will provide a solution -- I don't absolutely require the user info and that is the call that is causing your errors. I can probably make this non-fatal.

Can you provide any more info on the problematic account? Then I can at least document what we've learned. It doesn't sound exotic -- I'm sure I will encounter this again.

**Comment by lawwu** [comment]
The problematic account is registered with a google account under the domain payoff.com - is there any additional info you need?

**Comment by jennybc** [comment]
I'm just trying to read up on this *type* of account and so far can't identify any known issues for, say, "google api corporate account" or "google api enterprise account". So I was wondering if I'm using the wrong vocabulary.
