### ISSUE TITLE
Error in gsheets_POST when using gs_add_row

### ISSUE THREAD

**Issue by martinjhnhadley** [jennybc/googlesheets#168]
I'm having difficulty using `gs_add_row` when used with pre-existing Google Sheets, I always get the following error:

```Error in gsheets_POST(lf_post_link, XML::toString.XMLNode(new_row)) : 
      client error: (405) Method Not Allowed```

I followed the tutorial in your README.md as follows:

    library(googlesheets)
    library(dplyr)
    df.colnames <- c("Project Short Name","Project Start Date","Proj Stuff")
    my.df <- data.frame(a = "cannot be empty", b = "cannot be empty", c = "cannot be empty")
    colnames(my.df) <- df.colnames
    ## Create a new workbook populated by this data.frame:
    mynewSheet <- gs_new("mynewsheet", input = my.df, trim = TRUE)
    ## Append Element
    mynewSheet <- mynewSheet %>% gs_add_row(input = c("a","b","c"))
    mynewKey <- mynewSheet$sheet_key

Rows are added successfully, I even get the cheery message `Row successfully appended.`

I now provide `mynewKey` to `gs_key`, as I would if this were a new sheet I were working with and attempt to add a new row using `gs_add_row` (Note: before evaluating these lines, I navigate to the Google Sheet and make it public to the web):

    myExistingWorkbook <- gs_key(mynewKey, visibility = "public")
    ## Attempt to gs_add_row
    myExistingWorkbook <- myExistingWorkbook %>% gs_add_row(input = c("a","b","c"), ws="Sheet1", verbose = TRUE)

    Error in gsheets_POST(lf_post_link, XML::toString.XMLNode(new_row)) : 
      client error: (405) Method Not Allowed


Things that I have tried:

1) Published the Google Sheet to the web (as per https://github.com/jennybc/googlesheets/issues/126#issuecomment-118751652)

2) Enabled the sheet as editable to the public

# Note

I'm still unsure of best manners regarding Github Issues and SE, I do not want to appear to be spamming you but would like to help anybody else having similar problems by cross-positing - and also to advertise your package. Please do advise if you have any opinions on the matter.

My SE question on the same is here: http://stackoverflow.com/q/32537882/1659890

**Comment by jennybc** [comment]
I'll talk a look at this sometime this weeekend.

Can you give me the key or URL to a Sheet where you've had this problem and where I can write? So, it should be something I can destroy, but you've said above you've tried making the sheet editable to the public, so let me be your editing public :)

Is there any info at all about the Sheet that might be relevant? Was it an old Sheet and then got converted to a new one? How did it come into existence? I feel like I've seen a couple other Sheets that exhibit strange behvavior, counter to the docs, and I wonder what they have in common.

**Comment by martinjhnhadley** [comment]
Thanks for reply.

This is the sheet I'm actually targeting - https://docs.google.com/spreadsheets/d/1I6Z94prfJrmSSmD_mwqazkp8Qx8AUmmsp9hAW6bF8yQ/edit?usp=sharing

It's only got "viewable by anyone" permissions, as it is already linked into a workflow or two. I've made a duplicate of it with edit permissions for anyone - https://docs.google.com/spreadsheets/d/1gt560Hqhj48B1w_R24MXpYVbBww9Dh5sCrJA8pgQ2o8

The sheet I'll be targeting is "Delete Request". I created this document in the web interface some time in the last three weeks (so not an old sheet), as far as I can tell I've not done anything unusual with it.

**Comment by martinjhnhadley** [comment]
I've got another example of the issue I reported, hopefully described better this time:

```
desktopItems.GSheet <- gs_new("Desktop Items Data (v1)", ws = "RStudio-Uploads", input = desktopItems.df, trim = TRUE)
## This works:
gs_add_row(desktopItems.GSheet, ws = "RStudio-Uploads", input = c("2","2","2","4"))
## Navigate to Sheet and make it 1) Published to the web
newKey <- desktopItems.GSheet$sheet_key
## This doesn't work, note the newkey is "1qhF89Ig_xyy489PrgUF1QQlyOlAgRpm94z3eGayFZM4"
gs_add_row(gs_key(newKey, visibility = "public"), ws = "RStudio-Uploads", input = c("2","2","2","4"))
## Make the sheet publically editable:
gs_add_row(gs_key(newKey, visibility = "public"), ws = "RStudio-Uploads", input = c("2","2","2","4"))
## Add another row using the existing connection to the desktopItems.GSheet, this continues to work:
gs_add_row(desktopItems.GSheet, ws = "RStudio-Uploads", input = c("9","9","9","9"))
```

The error message I get is always:

```
Error in gsheets_POST(lf_post_link, XML::toString.XMLNode(new_row)) : 
  client error: (405) Method Not Allowed
```

**Comment by jennybc** [comment]
I'm going to try to spend today clearing some issues, hopefully including this one. Thanks for the second, detailed report.

**Comment by jennybc** [comment]
When you register a Sheet and plan downstream editing, it's important to register with `visibility = "private"`, otherwise you will get the 405 error you see above.

So please try statements like this: `gs_key(newKey, visibility = "private")`.
