### ISSUE TITLE
Attempt to read public spreadsheet fails: "not expecting content-type to be: text/html; charset=UTF-8"

### ISSUE THREAD

**Issue by Matherion** [jennybc/googlesheets#171]
When I run:

```R
test <- gs_url('https://docs.google.com/spreadsheets/d/1Hl-QtmQh7tvhLN9r-DIgPdlyMwrVBFBzSHnecf5BLG8/edit?usp=sharing',
               visibility="public");
```

I get:

```R
Sheet-identifying info appears to be a browser URL.
googlesheets will attempt to extract sheet key from the URL.
Putative key: 1Hl-QtmQh7tvhLN9r-DIgPdlyMwrVBFBzSHnecf5BLG8
Authentication will not be used.
Worksheets feed constructed with public visibility
Error in gsheets_GET(x) : Not expecting content-type to be:
text/html; charset=UTF-8
```

If I try to read the same sheet without the `visibility='public'` argument, it works fine (assuming my account actually has access to this sheet).

If I try to copy `gs_gap()`, I get the same result:

```R
test <- gs_key('1Hl-QtmQh7tvhLN9r-DIgPdlyMwrVBFBzSHnecf5BLG8',
               visibility="public", lookup=FALSE);
```

I'm not sure what happens. I can't choose encoding in Google Sheets - nor specify the encoding to be expected to the `gs_url` and `gs_key` functions. I have the feeling I'm missing something stupid. So sorry if this is actually not a bug. I'll gladly repost this question plus the answer at Stack Exchange or Crossvalidated to prevent repetition by somebody else :-)

PS: thank you, this package is just what we need to make some tools to monitor their work accessible to clinical psychologists!!!

**Comment by jennybc** [comment]
Thanks for the report.

FWIW the error about "Not expecting content-type to be: text/html; charset=UTF-8" is not reporting an encoding problem. Rather, it means we got some sort of error page back, instead of data.

Are 100% sure this Sheet is "published to the web" and not "public on the web"? I have more follow up questions but will have to come back later this morning to ask them. But there's one thing to check right now.

Also, that key above in your second example is correct for the sample Gapminder sheet:

``` r
library(googlesheets)
library(magrittr)
gs_gap_key()
#> [1] "1BzfL0kZUz1TsI5zxJF1WNF01IxvC67FbOJUiiGMZ_mQ"
test <- gs_gap_key() %>% 
  gs_key()
#> Authentication will not be used.
#> Worksheets feed constructed with public visibility
```

**Comment by Matherion** [comment]
Ah. That's indeed clear from https://developers.google.com/google-apps/spreadsheets/worksheets#sheets_api_urls_visibilities_and_projections, and it becomes clear there that this is clearly some weird Google thing.

And this solves it - the spreadsheet has to be both public and published. Thank you!!!

I've re-asked at crossvalidated (both to make it easier for people to find googlesheets, and to make it easier for people to find this specific question/answer). Would you like to repeat your answer there, or shall I?

(You could also consider telling people that's a likely cause of the error in the help file, until Google fixes it (which can take years, sometimes :-/ ) . . .)

In any case, thank you very much, and my apologies for the stupid question (i.e. one that had probably been prevented by careful examination of the documentation...)

**Comment by jennybc** [comment]
No worries. Go ahead and post this answer if you've posted a question anywhere. I need to make this particular thing easier to diagnose. You are hardly the first to stumble into it. Please close this too if we're done. Glad it works.

**Comment by Matherion** [comment]
Ok, will answer. Thank you a lot!
