### ISSUE TITLE
authentication in a cron job

### ISSUE THREAD

**Issue by lawwu** [jennybc/googlesheets#174]
Has anyone successfully used the googlesheets package in a cron job? 

I've saved the .httr-auth token in my working directory but am getting an error:

Error: oauth_listener() needs an interactive environment.
Execution halted

Is there a way to force R to use an interactive environment?

**Comment by jennybc** [comment]
I am working on a vignette that explains auth token management. I think it will answer this question. You are not alone :)

**Comment by lawwu** [comment]
i can't wait! btw, thanks for an awesome package.

**Comment by jennybc** [comment]
Please have a look and see if this helps. I'd appreciate any feedback:

https://github.com/jennybc/googlesheets/blob/master/vignettes/managing-auth-tokens.md

**Comment by jennybc** [comment]
I hope that we have straightened all of this out. I know you've gotten auth working from a cron job, though not with your ideal account, which is corporate/enterprise. I know about that problem and will see how much we can do even when Google user info can't be obtained via API. That discussion occurs in https://github.com/jennybc/googlesheets/issues/166#issuecomment-184485354.

**Comment by lawwu** [comment]
@jennybc Yes everything looks like it's working now. I'll let you know if I turn up anything on my end regarding the corporate account.

**Comment by jennybc** [comment]
@lawwu Would you email me so I can dig further into this? I have follow up questions from someone on the inside. I'm jenny@stat.ubc.ca.

**Comment by WoodyWD** [comment]
@jennybc Hi Jenny, I would like to thank you for this great package first. I also run into an error when I try to set up a cron in Rstudio Server with a corporate google account. I upload the .rds file to the server and It works in the first hour. But after that, I got the error say:

Auto-refreshing stale OAuth token.
Error in refresh_oauth2.0(self$endpoint, self$app, self$credentials, self$params$user_params,  : 
 unused argument (self$params$use_basic_auth)
Calls: gs_auth ... VERB -> request_perform -> <Anonymous> -> refresh_oauth2.0
Execution halted

Is there any method to solve this problem?

**Comment by jennybc** [comment]
This can be complicated (cron job + running on RStudio Server). But for starters ... this part of the message:

> unused argument (self$params$use_basic_auth)

smells like a problem with `httr`, which is a package `googlesheets` uses to carry out authentication. So the first thing I would try is making sure that `httr` is up-to-date.

But also already suspect that RStudio Server is another (or the actual) hurdle. You might want to read this article:

https://support.rstudio.com/hc/en-us/articles/217952868

**Comment by WoodyWD** [comment]
@jennybc Thank you so much Jenny, it works!

**Comment by lawwu** [comment]
Ditto the above, @WoodyWD was able to solve the problem we were trying to solve a few months ago @jennybc.

**Comment by jennybc** [comment]
@WoodyWD can you clarify "it works!" because I'd like to know so I can heartily recommend to others! Are you referring to the linked article?

**Comment by WoodyWD** [comment]
@jennybc Based on your suggestions, I just update the 'httr' package and library it before running the code. I set up the cron to run every 30 mins and it keeps working for 5 hours (only got one error once says http 500 error, i think it's not caused by the package). It also works fine to automating update the data in google sheets.

**Comment by jennybc** [comment]
@WoodyWD OK glad to hear it was that simple. Fingers crossed that it stays fixed.
