### ISSUE TITLE
Doesn't get content-type for a request and gs_read() crash

### ISSUE THREAD

**Issue by brolin** [jennybc/googlesheets#175]
As of 2022-02-03, the googlesheets package has been archived on CRAN.
I'm closing all issues and pull requests prior to archiving this GitHub repo.

Learn more at:

<https://github.com/jennybc/googlesheets#readme>

**Comment by jennybc** [comment]
Will you double check the Sheet you are trying access is **published to the web** and not merely "public on the web"?

**Comment by jennybc** [comment]
I suppose it is also possible this is linked to an encoding problem that's on the radar (#151).

**Comment by brolin** [comment]
can't i get a sheet that it is not public but i have access to write it? It works the last couple of weeks.

I changed the publishing setting of the sheet and neither worked

Thanks @jennybc  for your fast response. I will follow the encoding issue

**Comment by jennybc** [comment]
Can you translate this error message for me?

> Error in if (!(req$headers$`content-type` %in% ok_content_types)) { : 
  argumento tiene longitud cero
Además: Warning message:
In strsplit(rawToChar(raw), "\r?\n") :
  string de entrada 1 es inválida en este locale

And, yes, you can definitely access private Sheets -- sorry if I was confusing. I didn't realize that's what we were talking about here and I get the other question about once per day :)

Before you attempt to read the Sheet, will you confirm you are in authorized state with `gs_user()`? And `reporte_actividades` is definitely a successfully registered `googlesheet`?

**Comment by jennybc** [comment]
If encoding is the problem, you could also try accessing both the Sheet and worksheets within in non-character ways, i.e. identify the Sheet by key and the worksheet by positive integer index.

**Comment by brolin** [comment]
Sure my english help for the confusion.

My complete code is
```
> require(googlesheets)
> gs_auth()
> reporte_actividades <- gs_title("Malla de Información de las organizaciones.xlsx")
> reporte_actividades %>% gs_read("EL Limonar")
```
And the error saids somethig like:

Error in if (!(req$headers$content-type %in% ok_content_types)) { :
**argument have length zero**
**Also**: Warning message:
In strsplit(rawToChar(raw), "\r?\n") :
**input string 1 is invalid in this locale**

I get the same error when access the sheets by the index number

Thanks

**Comment by jennybc** [comment]
OK thanks that is informative. I now think you are another instance of #151.

FWIW Google Docs is completely down right now for us here -- can you access it? Where are you?

**Comment by brolin** [comment]
Thanks, 
yes, here too was inaccesible for a while. I'm in Medellín - Colombia.

**Comment by jennybc** [comment]
Some encoding problems here trace back to `xml2`, which has just gotten a fix (https://github.com/hadley/xml2/issues/54).

Would you be willing to install `xml2` from GitHub and see if your problem remains? It might be fixed now.

``` r
devtools::install_github("hadley/xml2")
devtools::install_github("jennybc/googlesheets")
## then try to register and read your Sheet again
```

But then again, it might not.

I have another person with a problematic Sheet that cannot be read with `gs_read()` but can be read with `gs_read_listfeed()` and `gs_read_cellfeed()`. See [this comment](https://github.com/jennybc/googlesheets/issues/151#issuecomment-147281745).

Can you export your Sheet to csv or tsv from the browser?

Can you tell me what you see in the browser when you do *File > Spreadsheet settings* and look at Locale and Display Language?

**Comment by brolin** [comment]
I reinstalled both packages, but without success.

I can read the sheets with gs_read_listfeed() and gs_read_cellfeed().

I can export from the browser.

I see when do File > Spreadsheet setting .. the locale is empty and the
language is spanish.

I change the locale to Colombia with no success.

I made a hack writing a function in my script with the next code and works
fine. I don't have any verifications but works meanwhile

my_gs_read <- function(ws, sheetIndex, user_session_info) {
    stopifnot(inherits(ws, "googlesheet"))
     req <- httr::GET(ws$ws$exportcsv[sheetIndex])
    req %>%
        httr::content(type = "text/csv", na.strings = c("", "NA"),encoding
= "UTF-8") %>%
        dplyr::as_data_frame() %>%
        dplyr::as.tbl()
}


Thanks!!

**Comment by jennybc** [comment]
@brolin OK that's all very interesting. Thanks for the info. You can at least consume the data in various ways now. I will continue to figure out why some of these sheets don't immediately work with `gs_read()` / `gs_read_csv()`. Given that `my_gs_read()` works for you, maybe it IS something I'm doing ....
