### ISSUE TITLE
Reading sheets uses rounded numbers

### ISSUE THREAD

**Issue by Deleetdk** [jennybc/googlesheets#178]
I spent about 30 minutes tracking down a pesky bug that turned out to be due to this package using the rounded numbers when reading from sheets. I looked and did not see a parameter to avoid using rounded numbers. Generally, one does not want to use rounded numbers for any further calculation.

Here's a public, published sheet with some example data.
https://docs.google.com/spreadsheets/d/1nFNwV0QUYJdP-ZL5v-aCcu6acehnhw1T_xE8dk_lkjA/edit#gid=0

Notice that Google Drive treat the numbers as identical, e.g. if one uses = to test for equality.

Is this a limitation of reading data from Google Drive? E.g. if it imports the data using export as CSV, the CSV has the rounded numbers too.

Am I missing something? :)

-Emil

**Comment by jennybc** [comment]
I can get you the full numbers. See #152 for the general issue. I even have this basically implemented in a local branch. The question is how to change `gs_read()` and `gs_read_cellfeed()` to expose the new choices. It's not quite as simple as "raw numbers vs. rounded". I will push the experimental branch up this weekend and alert the people who care and maybe you can play with it and help figure out how to change the functions for users!

As you've detected, right now I have all readers match the functionality of csv export. But the underlying XML holds full numbers, formulas, etc.

**Comment by Deleetdk** [comment]
Thanks for the fast answer. :)

**Comment by Deleetdk** [comment]
@jennybc is there any update to this issue? I have to import a data sheet for a large meta-analysis from Google Sheets. However, for easy reading, we rounded the numbers in the sheet. This causes the meta-analysis to also use rounded numbers.

**Comment by jennybc** [comment]
I am closing in on this issue. I had other things I needed to clean up first but have made good progress recently. I will make formulas and other stuff available via the cell feed available in the next ... week? I'm doing a community call about googlesheets next Wednesday, which is proving highly motivating 😬. It might start out in a branch where those of you who care can try it out and provide some feedback.

**Comment by jennybc** [comment]
@Deleetdk  You can now install from the `formulas` branch and try out the new ability to get data without numeric formatting applied. Rounding, in your case.

You can read a [draft vignette](https://github.com/jennybc/googlesheets/blob/formulas/vignettes/formulas-and-formatting.md) and/or just try it out. I've taken it for a spin w/ your demo sheet.

``` r
## devtools::install_github("jennybc/googlesheets@formulas")
library(googlesheets)
suppressMessages(library(dplyr))
## your sheet
key <- extract_key_from_url("https://docs.google.com/spreadsheets/d/1nFNwV0QUYJdP-ZL5v-aCcu6acehnhw1T_xE8dk_lkjA")
ss <- gs_key(key, lookup = FALSE)
#> Worksheets feed constructed with public visibility
## go look at it?
## gs_browse(ss)

## consume it the default way = with rounding
ss %>% gs_read(verbose = FALSE)
#> No encoding supplied: defaulting to UTF-8.
#> Source: local data frame [26 x 2]
#> 
#>    Rounded Unrounded
#>      (dbl)     (dbl)
#> 1    0.368 0.3677147
#> 2    0.368 0.3681386
#> 3    0.368 0.3675039
#> 4    0.368 0.3677305
#> 5    0.368 0.3683773
#> 6    0.368 0.3676500
#> 7    0.368 0.3675398
#> 8    0.371 0.3709216
#> 9    0.372 0.3724826
#> 10   0.374 0.3737459
#> ..     ...       ...

## consume it w/o numeric formatting
ss %>% gs_read(literal = FALSE, verbose = FALSE)
#> Source: local data frame [26 x 2]
#> 
#>      Rounded Unrounded
#>        (dbl)     (dbl)
#> 1  0.3677147 0.3677147
#> 2  0.3681386 0.3681386
#> 3  0.3675039 0.3675039
#> 4  0.3677305 0.3677305
#> 5  0.3683773 0.3683773
#> 6  0.3676500 0.3676500
#> 7  0.3675398 0.3675398
#> 8  0.3709216 0.3709216
#> 9  0.3724826 0.3724826
#> 10 0.3737459 0.3737459
#> ..       ...       ...
```

**Comment by Deleetdk** [comment]
Looks good! I am unable to install the branch, however:

```
library(devtools)
#try with branch name
install_github("jennybc/googlesheets", ref = "formulas")
#>Downloading GitHub repo jennybc/googlesheets@formulas
#>from URL https://api.github.com/repos/jennybc/googlesheets/zipball/formulas
#>Error in curl::curl_fetch_memory(url, handle = handle) : 
#>  Problem with the SSL CA cert (path? access rights?)
#maybe try with commit SHA
install_github("jennybc/googlesheets", ref = "5db5e95d0d1c6725c16e9a0c4b84a80dc7409a79")
#>Downloading GitHub repo jennybc/googlesheets@5db5e95d0d1c6725c16e9a0c4b84a80dc7409a79
#>from URL https://api.github.com/repos/jennybc/googlesheets/zipball/5db5e95d0d1c6725c16e9a0c4b84a80dc7409a79
#>Error in curl::curl_fetch_memory(url, handle = handle) : 
#>  Problem with the SSL CA cert (path? access rights?)
```

Am I doing something wrong? I tried restarting R. [It seems to be a non-R specific problem](https://www.google.com/search?q=Problem+with+the+SSL+CA+cert+%28path%3F+access+rights%3F%29&ie=utf-8&oe=utf-8).

**Comment by jennybc** [comment]
I **can** install from this branch. So perhaps this is a `devtools` or `curl` problem. Maybe re-install one or both of those?

Alternatively, there are also some new lightweight packages for installing from github. You could try with one of them:

  * https://github.com/leeper/ghit
  * https://github.com/mangothecat/remotes

**Comment by jennybc** [comment]
OK, it looks likely that you need to restart R and update `httr` and `curl`. See [this issue](https://github.com/hadley/devtools/issues/1079) over on `devtools`:

``` r
install.packages(c("curl", "httr"))
```

**Comment by Deleetdk** [comment]
I closed RStudio down entirely, opened again, updated all packages, closed, opened, then installed your package. This time it worked.

I get this warning though:

```
Ignoring these arguments that don't work with this read function:
skip
```

Many datasets contain meta-data in the first few rows, so `skip` is good to have. One can still remove the lines afterwards oneself.

Otherwise, the change works for me. My numbers now have more digits.

**Comment by jennybc** [comment]
Can you show me your exact code? `skip` will only work when we read via csv, so I suspect this means you are somehow invoking another read method, while also specifying `skip`. I'd love to see what you're trying to do to see if the docs or arguments need to change.

**Comment by Deleetdk** [comment]
I am loading this dataset using authentication. The file is public, but not 'published'.
https://docs.google.com/spreadsheets/d/1nIwCydodOVQea0ny0YS4L68ifuUUD6sxkfvF2ZfyG2A/edit#gid=195242602

I load it with:

```
#get spreadsheet
g_sheet = gs_url(x = "https://docs.google.com/spreadsheets/d/1nIwCydodOVQea0ny0YS4L68ifuUUD6sxkfvF2ZfyG2A/edit?ts=56af8a54#gid=195242602")

#load sheet
d_admix = gs_read(g_sheet, ws = 1, skip = 3, na = c("", "NA", "NR"), literal = F)
```

**Comment by jennybc** [comment]
OK yes `literal = FALSE` will always force usage of the cell feed. In this case, you can specify the cells you want using `range = ...` and exclude the first 3 rows that way. Maybe something like `range = cell_limits(c(4, 1), c(NA, NA))` will work?

**Comment by Deleetdk** [comment]
I tried:

`d_admix = gs_read(g_sheet, ws = 1, skip = 3, na = c("", "NA", "NR"), literal = F, range = cell_limits(c(4, 1), c(NA, NA)))`

But:

```
Accessing worksheet titled 'Data new'.
Error in stop_for_content_type(req, expected = "application/atom+xml; charset=UTF-8") : 
  Expected content-type:
application/atom+xml; charset=UTF-8
Actual content-type:
application/binary
```

**Comment by jennybc** [comment]
You've still got `skip` in there FWIW. But that's not the main problem here.

API access via the cell feed (which is what's happening here) absolutely requires the sheet be "published". Merely "public" is not enough.

But in case we are miscommunicating ... can you read from this worksheet with a very plain `gs_read()` call, i.e. with no cell specification or parsing arguments? That would be interesting an informative test.

But this looks more like a permission issue.

**Comment by jennybc** [comment]
BTW @Deleetdk `skip` now works the way you expected it to work, for all read functions (0db39f46a4d49be1d8d545410a2c7785fe0c93a7).
