### ISSUE TITLE
Formula support

### ISSUE THREAD

**Issue by jennybc** [jennybc/googlesheets#18]
I'm not sure if or when we want to handle this. We're clearly not doing so right now. But you can get and edit formulas via the API. Right now, we seem to assume "contents is contents".

From the [API docs on the cells feed](https://developers.google.com/google-apps/spreadsheets/#working_with_cell-based_feeds):

> The inputValue attribute of a cell entry always contains the value that a user would otherwise type into the Google Sheets user interface to manipulate the cell (i.e. either a literal value or a formula). To set a formula or a literal value on a cell, provide the text of the formula or value as the inputValue attribute. Remember that formulas must start with = to be considered a formula. If a cell contains a formula, the formula is always provided as the inputValue when cell entries are returned by the API.

> The numericValue attribute of a cell entry, when present, indicates that the cell was determined to have a numeric value, and its numeric value is indicated with this attributed.

> The literal value of the cell element is the calculated value of the cell, without formatting applied. If the cell contains a formula, the calculated value is given here.

**Comment by jennybc** [comment]
from twitter: "Is there any way to import formulas (specifically HYPERLINK) along with content?"

**Comment by jrosen48** [comment]
I asked a SO question about this here: http://stackoverflow.com/questions/31293347/import-google-spreadsheet-with-formula-into-r 

I think this would be a useful feature. After reading the excerpt from the API docs on the cells feed, does it sound like you can extract a formula from a cell, or enter the inputValue? 

I ran into an issue when simply trying to extract a formula from a cell (instead of the literal value). I had to use a Google Apps Script function to do so:

    function myFunction() {
      var formulas = SpreadsheetApp.getActiveRange().getFormulas();
      var toPut = SpreadsheetApp.getActiveRange().offset(0, 1, SpreadsheetApp.getActiveRange().getNumRows(), 1);
      var extracted = [];
      for(var index in formulas){
        var array = formulas[index];
        for(var formulaIndex in array){
          Logger.log("f:" + array[formulaIndex]);
      extracted.push([array[formulaIndex].substring(array[formulaIndex].indexOf('"')+1, array[formulaIndex].lastIndexOf('"'))]);
    }
  }

  toPut.setValues(extracted);
}

function onOpen(e){

        SpreadsheetApp.getUi().createMenu("Testing").addItem("myFunc", 'myFunction').addToUi();
    }

**Comment by jennybc** [comment]
Hi @jrosen48 

I am on vacation right now with poor / nonexistent internet access. But I will work on this when i get back in ~1.5 weeks.

Yes I can definitely access the formulas. Here's where I've made some previous notes to myself to come back to this:

https://github.com/jennybc/googlesheets/blob/97db8cc6c6c156b02a682cbfd1e4dd6fd7d54eff/R/gs_read_cellfeed.R#L123-L128

Now that I've found someone who cares, it seems worth doing!

**Comment by jrosen48** [comment]
Thank you @jennybc, that sounds great!

**Comment by jennybc** [comment]
Just coming back to this @jrosen48 and have already put my hands on the formula. So don't despair. Tackling this will solve another issue (#152) as well.

**Comment by jrosen48** [comment]
Great!

**Comment by jennybc** [comment]
Merged into #152 now. Closing.
