### ISSUE TITLE
Error "Worksheet ____ not found."

### ISSUE THREAD

**Issue by Myfanwy** [jennybc/googlesheets#180]
I'm having trouble with both the gs_read() and the gs_read_csv() functions not identifying a registered spreadsheet.  The following is an output from my console:

``` 
> library(googlesheets)
> suppressMessages(library(dplyr))

> Healy <- gs_title("healyNE")
Sheet successfully identifed: "healyNE"

> d <- Healy %>%  gs_read_csv("healyNE")
Error in gs_ws(ss, ws, verbose) : Worksheet healyNE not found.

> dd <- Healy %>% gs_read("Healy_NE")
Error in gs_ws(ss, ws, verbose) : Worksheet Healy_NE not found.

```

When I try these functions with the Gapminder sample spreadsheet, everything works fine.  Any idea what I'm doing wrong?  I can't seem to find my typo, although that's probably what it is...

Thanks so much!
Myfanwy

**Comment by jennybc** [comment]
It sounds like you don't have a worksheet named "Healy_NE" or "healyNE" in this Google Sheet.

From `gs_title("healyNE")`, it appears the Sheet itself is titled "healyNE" and that you've successfully registered it.

You can print the registered object or use `gs_ws_ls()` to see a listing of the worksheet names. Pick one of those to specify as `ws = ` in functions that operate on worksheets. Or use a positive integer.

Try stuff like this but for your Sheet:

``` r
library(googlesheets)
gs_gap()
#>                   Spreadsheet title: test-gs-gapminder
#>                  Spreadsheet author: rpackagetest
#>   Date of googlesheets registration: 2015-10-26 15:30:41 GMT
#>     Date of last spreadsheet update: 2015-04-22 18:27:11 GMT
#>                          visibility: public
#>                         permissions: rw
#>                             version: new
#> 
#> Contains 5 worksheets:
#> (Title): (Nominal worksheet extent as rows x columns)
#> Africa: 625 x 6
#> Americas: 301 x 6
#> Asia: 397 x 6
#> Europe: 361 x 6
#> Oceania: 25 x 6
#> 
#> Key: 1BzfL0kZUz1TsI5zxJF1WNF01IxvC67FbOJUiiGMZ_mQ
#> Browser URL: https://docs.google.com/spreadsheets/d/1BzfL0kZUz1TsI5zxJF1WNF01IxvC67FbOJUiiGMZ_mQ/
gs_ws_ls(gs_gap())
#> [1] "Africa"   "Americas" "Asia"     "Europe"   "Oceania"
```

**Comment by Myfanwy** [comment]
Hi Jenny,

I'm sorry - I was confusing the name of the spreadsheet document with the name of the worksheet - the integer caller worked fine.  That's what I get for trying to learn new things after 11pm.  Thank you so much!

Best,
Myfanwy
