### ISSUE TITLE
Implement resumable upload

### ISSUE THREAD

**Issue by dcabanillas** [jennybc/googlesheets#183]
As of 2022-02-03, the googlesheets package has been archived on CRAN.
I'm closing all issues and pull requests prior to archiving this GitHub repo.

Learn more at:

<https://github.com/jennybc/googlesheets#readme>

**Comment by jennybc** [comment]
I've uploaded ~2,000 rows. The API is really quite slow. I don't think it's the `googlesheets` package that's the problem (?).

What exactly happens? Is there an error or just it just incredibly slow?

I don't think you are exceeding any hard, documented limit on a Sheet. It would be worth trying `gs_upload()`, where you upload a local file in one of these formats: .xls, .xlsx, .csv, .tsv, .txt, .tab, .xlsm, .xlt, .xltx, .xltm, .ods.

**Comment by dcabanillas** [comment]
I believe that the gs_upload is limited to 5mb. Right?

It is too strange to me, with Java API Google Drive I have upload the same
file. It has around 12 MB.

best

On Sat, Oct 31, 2015 at 11:28 PM, Jennifer (Jenny) Bryan <
notifications@github.com> wrote:

> I've uploaded ~2,000 rows. The API is really quite slow. I don't think
> it's the googlesheets package that's the problem (?).
>
> What exactly happens? Is there an error or just it just incredibly slow?
>
> I don't think you are exceeding any hard, documented limit on a Sheet. It
> would be worth trying gs_upload(), where you upload a local file in one
> of these formats: .xls, .xlsx, .csv, .tsv, .txt, .tab, .xlsm, .xlt, .xltx,
> .xltm, .ods.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jennybc/googlesheets/issues/183#issuecomment-152778283>
> .
>



-- 
bye
--david

**Comment by jennybc** [comment]
We're using this:

https://developers.google.com/drive/v2/reference/files/insert

You could use the API explorer at the bottom of the page to see if you can upload your file, without using `googlesheets` as the intermediary.

**Comment by jennybc** [comment]
More relevant documentation:

https://developers.google.com/drive/web/manage-uploads

which suggests this method is best for things 5MB or smaller, though it's not a hard limit. For larger files, it looks like one should use the "resumable upload" protocol, which we have NOT implemented (yet?).

Is the upload something you need to do a lot within a `googlesheets` workflow? If not, maybe you could upload the data once through some other means and then carry on.

**Comment by dcabanillas** [comment]
The problem is that i'm working with RAdwords and I have the variables at
memory, The ideal will be to use RGoogleSheet to upload this variables in a
direct way.

Best.

On Sun, Nov 1, 2015 at 5:53 PM, Jennifer (Jenny) Bryan <
notifications@github.com> wrote:

> More relevant documentation:
>
> https://developers.google.com/drive/web/manage-uploads
>
> which suggests this method is best for things 5MB or smaller, though it's
> not a hard limit. For larger files, it looks like one should use the
> "resumable upload" protocol, which we have NOT implemented (yet?).
>
> Is the upload something you need to do a lot within a googlesheets
> workflow? If not, maybe you could upload the data once through some other
> means and then carry on.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jennybc/googlesheets/issues/183#issuecomment-152843671>
> .
>



-- 
bye
--david

**Comment by jennybc** [comment]
So, at the moment, I think you're best bets are:

  * Chunk it up yourself, i.e. use `gs_new()` and `gs_edit_cells()` to send it in smaller pieces. Yes I realize that is annoying.
  * Write it to file and use `gs_upload()`. But now I see how that may not be ideal if file > 5GB. In which case you could upload to Google Drive in the browser, if it's a very occasional thing.

I think we've arrived at this conclusion, yes?

I should implement the "resumable upload" protocol for `gs_upload()`.

**Comment by dcabanillas** [comment]
If you could implement the resumable upload it will be great.

Thanks a lot.

On Sun, Nov 1, 2015 at 6:46 PM, Jennifer (Jenny) Bryan <
notifications@github.com> wrote:

> So, at the moment, I think you're best bets are:
>
>    - Chunk it up yourself, i.e. use gs_new() and gs_edit_cells() to send
>    it in smaller pieces. Yes I realize that is annoying.
>    - Write it to file and use gs_upload(). But now I see how that may not
>    be ideal if file > 5GB. In which case you could upload to Google Drive in
>    the browser, if it's a very occasional thing.
>
> I think we've arrived at this conclusion, yes?
>
> I should implement the "resumable upload" protocol for gs_upload().
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jennybc/googlesheets/issues/183#issuecomment-152848345>
> .
>



-- 
bye
--david

**Comment by jennybc** [comment]
https://developers.google.com/drive/v3/web/manage-uploads#resumable
