### ISSUE TITLE
Editing public sheets

### ISSUE THREAD

**Issue by prpatil** [jennybc/googlesheets#185]
As of 2022-02-03, the googlesheets package has been archived on CRAN.
I'm closing all issues and pull requests prior to archiving this GitHub repo.

Learn more at:

<https://github.com/jennybc/googlesheets#readme>

**Comment by jennybc** [comment]
Yes I need to rationalize the verbs and the use of `use_auth` has a lot of room for improvement! I'll look into your specific question. Honestly I can't work on this (and other issues) much or at all until my teaching ends in early December.

**Comment by prpatil** [comment]
Gotcha, thanks for the quick response!
