### ISSUE TITLE
Error in  gs_key()

### ISSUE THREAD

**Issue by BkrmDahal** [jennybc/googlesheets#186]
![capture](https://cloud.githubusercontent.com/assets/11886819/11493273/cf1a3e62-981e-11e5-9598-a763af7e1928.PNG)
while i try to run gs_key() i get this error, Error in curl::curl_fetch_memory(url, handle = handle) : 
Timeout was reached. may be error is on curl package but everything was working fine till yesterday.
This has made all my codes useless.

**Comment by jennybc** [comment]
I suspect this is an intermittent thing separate from this package. Just today I got a similar curl connection timeout -- doing something totally unrelated with the GitHub API. I tried the thing again later in the day and it worked.

Can you try again? Best case this is is/was just a temporary Google or network issue.

**Comment by BkrmDahal** [comment]
Thanx  jennybc.. This package saves me a lot of time and make all my reporting fully automatic. :-).. Problem was  with our server..thanx for quick reply and packages...

**Comment by jennybc** [comment]
Yay. 🙂
