### ISSUE TITLE
readr::locale unused arguments error

### ISSUE THREAD

**Issue by kmkmjohnson** [jennybc/googlesheets#192]
When running gs_read(), getting the following error:

Error in readr::read_csv(x, readr::locale(encoding = encoding), ...) : 
  unused argument (na.strings = c("", "NA"))

Worked fine for months. This error is new in the last few days without any changes to my script or the spreadsheet (other than some new rows added to the data).

Running googlesheets 0.1.0, readr 0.2.2

**Comment by jennybc** [comment]
Can you give me a full `devtools::session_info()` or `sessionInfo()`? I'm especially interested in some other package versions, such as `httr`.

**Comment by dalewsteele** [comment]
Same new issue for me on all platforms.  Haven't test carefully, but seems to occur with most recent versions of installed from github.

`> r2_pubmed <- gs_title("r2_pubmed_tracking") %>% gs_read(ws=1)`

`Sheet successfully identifed: "r2_pubmed_tracking"
Accessing worksheet titled "Sheet1"
Error in readr::read_csv(x, readr::locale(encoding = encoding), ...) : 
  unused argument (na.strings = c("", "NA"))`

Current sessionInfo() below ...

```
> sessionInfo()
R version 3.2.3 (2015-12-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.3 LTS

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] stringr_1.0.0           googlesheets_0.1.0.9000 dplyr_0.4.3             MASS_7.3-45            

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.3      assertthat_0.1   cellranger_1.0.0 R6_2.1.2         jsonlite_0.9.19  DBI_0.3.1        magrittr_1.5    
 [8] httr_1.1.0       stringi_1.0-1    lazyeval_0.1.10  curl_0.9.5       xml2_0.1.2.9000  tools_3.2.3      readr_0.2.2.9000
[15] parallel_3.2.3   openssl_0.9.1  
```

**Comment by kmkmjohnson** [comment]
My sessionInfo():
R version 3.2.3 (2015-12-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] googlesheets_0.1.0

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.3      dplyr_0.4.3      assertthat_0.1   cellranger_1.0.0 R6_2.1.2        
 [6] jsonlite_0.9.19  DBI_0.3.1        magrittr_1.5     httr_1.1.0       stringi_1.0-1   
[11] curl_0.9.5       lazyeval_0.1.10  xml2_0.1.2       tools_3.2.3      readr_0.2.2     
[16] stringr_1.0.0    parallel_3.2.3   openssl_0.9.1

**Comment by zkamvar** [comment]
Just to throw in my chips since I never formally brought up an issue, this was the problem I tried to fix with my pull request: #191 

my `devtools::session_info()`:

```
Session info --------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.2.3 (2015-12-10)
 system   x86_64, darwin13.4.0        
 ui       RStudio (0.99.862)          
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/Los_Angeles         
 date     2016-02-01                  

Packages ------------------------------------------------------------------------------------------------
 package      * version date       source        
 assertthat     0.1     2013-12-06 CRAN (R 3.2.0)
 cellranger     1.0.0   2015-06-20 CRAN (R 3.2.0)
 curl           0.9.5   2016-01-23 CRAN (R 3.2.3)
 DBI            0.3.1   2014-09-24 CRAN (R 3.2.0)
 devtools       1.10.0  2016-01-23 CRAN (R 3.2.3)
 digest         0.6.9   2016-01-08 CRAN (R 3.2.3)
 dplyr          0.4.3   2015-09-01 CRAN (R 3.2.0)
 googlesheets * 0.1.0   2015-07-05 CRAN (R 3.2.0)
 httr           1.1.0   2016-01-28 CRAN (R 3.2.3)
 lazyeval       0.1.10  2015-01-02 CRAN (R 3.2.0)
 magrittr     * 1.5     2014-11-22 CRAN (R 3.2.0)
 memoise        1.0.0   2016-01-29 CRAN (R 3.2.3)
 R6             2.1.2   2016-01-26 CRAN (R 3.2.3)
 Rcpp           0.12.3  2016-01-10 CRAN (R 3.2.3)
 readr          0.2.2   2015-10-22 CRAN (R 3.2.0)
 stringi        1.0-1   2015-10-22 CRAN (R 3.2.0)
 stringr        1.0.0   2015-04-30 CRAN (R 3.2.0)
 xml2           0.1.2   2015-09-01 CRAN (R 3.2.0)
```

**Comment by frenkiboy** [comment]
I get the same error, if I traced it correctly the new version of readr::read_csv does not have na.strings argument, rather, it is replaced with na

I'm using the following readr
0.2.2.9000 2016-02-02 Github (hadley/readr@ef750db)

**Comment by ReportMort** [comment]
@frenkiboy I think you've got it. Just tracing through the code:

`gs_read` calls `httr::content` at this line: https://github.com/jennybc/googlesheets/blob/master/R/gs_read_csv.R#L75

The parser for `httr::content` ends up calling this function in `parsers$text/csv`:
https://github.com/hadley/httr/blob/f0fc278b96e8814c3527bb7a6ada19522d297df0/R/content-parse.r#L111

Which ends up calling `readr::read_csv` and the argument name is no longer `na.strings`, but `na`

**Comment by zkamvar** [comment]
@frenkiboy and @ReportMort, That's what I assumed at first, but you might notice that readr has never had the na.strings argument (see https://github.com/hadley/readr/blob/a4256026d5793bddcc52a8c56960dbe60d1d4de3/R/read_delim.R#L70-L71). 

I believe the culprit is a move from using [`read.csv()`](https://github.com/hadley/httr/blob/140ccd4c5d7a703e4c301861b6e246e4d042165f/R/content-parse.r#L95) in version 1.0.0 to using [`reader::read_csv()`](https://github.com/hadley/httr/blob/master/R/content-parse.r#L115) in version 1.1.0

**Comment by jennybc** [comment]
I am on top of this; its part of various adjustments necessary for httr 1.1.0. It will be fixed in master in the next ~day.

**Comment by maaraaj** [comment]
Hi Jenny
I am facing same issue..
Please find my session info below 
` package      * version    date       source                      
 assertthat     0.1        2013-12-06 CRAN (R 3.2.0)              
 cellranger     1.0.0      2015-06-20 CRAN (R 3.2.0)              
 curl           0.9.5      2016-01-23 CRAN (R 3.2.3)              
 DBI            0.3.1      2014-09-24 CRAN (R 3.2.0)              
 devtools       1.9.1      2015-09-11 CRAN (R 3.2.0)              
 digest         0.6.9      2016-01-08 CRAN (R 3.2.3)              
 dplyr          0.4.3      2015-09-01 CRAN (R 3.2.0)              
 googlesheets * 0.1.0      2015-07-05 CRAN (R 3.2.0)              
 httr           1.1.0      2016-01-28 CRAN (R 3.2.3)              
 jsonlite       0.9.19     2015-11-28 CRAN (R 3.2.2)              
 lazyeval       0.1.10     2015-01-02 CRAN (R 3.2.0)              
 magrittr       1.5        2014-11-22 CRAN (R 3.2.0)              
 memoise        0.2.1      2014-04-22 CRAN (R 3.2.0)              
 openssl        0.9.1      2016-01-18 CRAN (R 3.2.3)              
 R6             2.1.2      2016-01-26 CRAN (R 3.2.3)              
 Rcpp           0.12.3     2016-01-10 CRAN (R 3.2.3)              
 readr        * 0.2.2      2015-10-22 CRAN (R 3.2.0)              
 stringi        1.0-1      2015-10-22 CRAN (R 3.2.0)              
 stringr        1.0.0      2015-04-30 CRAN (R 3.2.0)              
 xml2           0.1.2.9000 2016-01-29 Github (hadley/xml2@4c4a448)`

**Comment by maaraaj** [comment]
Hi Jenny 
I m facing same issue 

 package      * version    date       source                      
 assertthat     0.1        2013-12-06 CRAN (R 3.2.0)              
 cellranger     1.0.0      2015-06-20 CRAN (R 3.2.0)              
 curl           0.9.5      2016-01-23 CRAN (R 3.2.3)              
 DBI            0.3.1      2014-09-24 CRAN (R 3.2.0)              
 devtools       1.9.1      2015-09-11 CRAN (R 3.2.0)              
 digest         0.6.9      2016-01-08 CRAN (R 3.2.3)              
 dplyr          0.4.3      2015-09-01 CRAN (R 3.2.0)              
 googlesheets * 0.1.0      2015-07-05 CRAN (R 3.2.0)              
 httr           1.1.0      2016-01-28 CRAN (R 3.2.3)              
 jsonlite       0.9.19     2015-11-28 CRAN (R 3.2.2)              
 lazyeval       0.1.10     2015-01-02 CRAN (R 3.2.0)              
 magrittr       1.5        2014-11-22 CRAN (R 3.2.0)              
 memoise        0.2.1      2014-04-22 CRAN (R 3.2.0)              
 openssl        0.9.1      2016-01-18 CRAN (R 3.2.3)              
 R6             2.1.2      2016-01-26 CRAN (R 3.2.3)              
 Rcpp           0.12.3     2016-01-10 CRAN (R 3.2.3)              
 readr        * 0.2.2      2015-10-22 CRAN (R 3.2.0)              
 stringi        1.0-1      2015-10-22 CRAN (R 3.2.0)              
 stringr        1.0.0      2015-04-30 CRAN (R 3.2.0)              
 xml2           0.1.2.9000 2016-01-29 Github (hadley/xml2@4c4a448)

**Comment by jennybc** [comment]
I think this is straightened out in the [`adjust-to-httr-v1.1.0`](https://github.com/jennybc/googlesheets/tree/adjust-to-httr-v1.1.0) branch. I pass tests locally and on travis. Could one or more of you test it today? And if it holds up, I'll merge this into master tonight.

Please make sure you're running `httr v1.1.0`, i.e. the current CRAN version.

And install `googlesheets` like so:

``` r
devtools::install_github("jennybc/googlesheets@adjust-to-httr-v1.1.0")
```

**Comment by zkamvar** [comment]
:+1: 

Just tested on my mwe. It works for me to read from a document.

```r
library("googlesheets")
library("magrittr")
ex_key <- "1N58tQL5ioci4_JripPZgvpxiNQ_Ky4WWpD364oVvMCY" 
participants <- ex_key %>% 
    gs_key(lookup = FALSE) %>%      # register the sheet with R
    gs_read()
```

As you brought up in #195, the variable names change due to the hands-off approach of *readr* when it comes to variable names as opposed to the default `check.names = TRUE` argument for `read.table()`. I have restored previous behavior by setting `setNames(names(.) %>% make.names())` after `gs_read()`

**Comment by jennybc** [comment]
@zkamvar Yes the variable naming is a dilemma. I do want to match expectations for "hadleyverse" data ingest. But the `NA` as variable name is pretty out there for most people. Do you think I should offer an argument for read functions that optionally processes the variable names in a more standard manner, such as what you did above?

**Comment by dalewsteele** [comment]
My original code now runs without error using the  [adjust-to-httr-v1.1.0](https://github.com/jennybc/googlesheets/tree/adjust-to-httr-v1.1.0)  branch.  Thanks!

**Comment by zkamvar** [comment]
> @zkamvar Yes the variable naming is a dilemma. I do want to match expectations for "hadleyverse" data ingest. But the NA as variable name is pretty out there for most people. Do you think I should offer an argument for read functions that optionally processes the variable names in a more standard manner, such as what you did above?

I would be in favor of adding the argument, because an argument is visible even without documentation.

**Comment by rodrigomurta** [comment]
I have the same issue, and installing from:
`devtools::install_github("jennybc/googlesheets@adjust-to-httr-v1.1.0")`
worked for me. tks!
