### ISSUE TITLE
Cant read googlesheets

### ISSUE THREAD

**Issue by nehiljain** [jennybc/googlesheets#197]
```R
gs_title("test_iris")  %>% gs_read(ws = 1)
```
Output
```
Sheet successfully identifed: "test_iris"
Accessing worksheet titled "Sheet1"
Error in readr::read_csv(x, readr::locale(encoding = encoding), ...) : 
  unused argument (na.strings = c("", "NA"))
```

I am not sure if I am doing something wrong, but i tried on different spreadsheets and different accounts and authentications

**Comment by jennybc** [comment]
What version of `googlesheets` are you using? Can you give me output from `devtools::session_info()`? The short answer is you should re-install from GitHub and make sure you meet new version requirements for `readr` and `httr`. But I'd love to know if that does not happen automatically (or at least produce messaging) when you install from GitHub.

**Comment by jemus42** [comment]
I've run into the same issue. Session info:

```
Session info -----------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.2.3 (2015-12-10)
 system   x86_64, darwin13.4.0        
 ui       RStudio (0.99.876)          
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       Europe/Berlin               
 date     2016-02-06                  

Packages ---------------------------------------------------------------------------------------------------------------
 package      * version date       source                            
 assertthat     0.1     2013-12-06 CRAN (R 3.1.0)                    
 cellranger     1.0.0   2015-06-20 CRAN (R 3.2.0)                    
 colorspace     1.2-6   2015-03-11 CRAN (R 3.2.0)                    
 curl           0.9.5   2016-01-23 CRAN (R 3.2.3)                    
 DBI            0.3.1   2014-09-24 CRAN (R 3.1.1)                    
 devtools     * 1.10.0  2016-01-23 CRAN (R 3.2.3)                    
 digest         0.6.9   2016-01-08 CRAN (R 3.2.3)                    
 dplyr        * 0.4.3   2015-09-01 CRAN (R 3.2.0)                    
 ggplot2        2.0.0   2015-12-18 CRAN (R 3.2.3)                    
 googlesheets * 0.1.0   2015-07-05 CRAN (R 3.2.0)                    
 gtable         0.1.2   2012-12-05 CRAN (R 3.1.0)                    
 httr           1.1.0   2016-01-28 CRAN (R 3.2.3)                    
 jsonlite       0.9.19  2015-11-28 CRAN (R 3.2.2)                    
 lazyeval       0.1.10  2015-01-02 CRAN (R 3.1.2)                    
 magrittr       1.5     2014-11-22 CRAN (R 3.2.0)                    
 memoise        1.0.0   2016-01-29 CRAN (R 3.2.3)                    
 munsell        0.4.2   2013-07-11 CRAN (R 3.1.0)                    
 openssl        0.9.1   2016-01-18 CRAN (R 3.2.3)                    
 plyr           1.8.3   2015-06-12 CRAN (R 3.2.0)                    
 R6             2.1.2   2016-01-26 CRAN (R 3.2.3)                    
 Rcpp           0.12.3  2016-01-10 CRAN (R 3.2.3)                    
 readr          0.2.2   2015-10-22 CRAN (R 3.2.0)                    
 rsconnect      0.4.1.4 2015-09-02 Github (rstudio/rsconnect@fcac892)
 scales         0.3.0   2015-08-25 CRAN (R 3.2.0)                    
 stringi        1.0-1   2015-10-22 CRAN (R 3.2.0)                    
 stringr        1.0.0   2015-04-30 CRAN (R 3.2.0)                    
 xml2           0.1.2   2015-09-01 CRAN (R 3.2.0) 
```

I then reinstalled `googlesheets` from GitHub and it works fine, so the issue seems to be with the CRAN version?

**Comment by jennybc** [comment]
Yeah the CRAN version will not work with the current versions of `readr` and `httr`. But I can't go back in time and put an upper bound on the required versions for those packages. I will update `googlesheets` on CRAN sometime in the next month.

**Comment by nehiljain** [comment]
github version works for me :+1:

**Comment by jennybc** [comment]
Ok thanks. Closing this.

**Comment by djbiggs** [comment]
Am I missing something? Which Github version?

Getting 

Accessing worksheet titled "Sheet2"
Error in readr::read_csv(x, readr::locale(encoding = encoding), ...) : 
  unused argument (na.strings = c("", "NA"))

> devtools::session_info()
Session info ------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.2.3 (2015-12-10)
 system   x86_64, mingw32             
 ui       RStudio (0.99.491)          
 language (EN)                        
 collate  English_United States.1252  
 tz       Australia/Sydney            
 date     2016-02-17                  

Packages ----------------------------------------------------------------------------------
 package      * version    date       source        
 assertthat     0.1        2013-12-06 CRAN (R 3.2.3)
 cellranger     1.0.0      2015-06-20 CRAN (R 3.2.3)
 curl           0.9.5      2016-01-23 CRAN (R 3.2.3)
 DBI            0.3.1      2014-09-24 CRAN (R 3.2.3)
 devtools       1.10.0     2016-01-23 CRAN (R 3.2.3)
 digest         0.6.9      2016-01-08 CRAN (R 3.2.3)
 dplyr        * 0.4.3      2015-09-01 CRAN (R 3.2.3)
 googlesheets * 0.1.0.9000 2016-02-16 local         
 httr           1.1.0      2016-01-28 CRAN (R 3.2.3)
 jsonlite       0.9.19     2015-11-28 CRAN (R 3.2.3)
 lazyeval       0.1.10     2015-01-02 CRAN (R 3.2.3)
 magrittr       1.5        2014-11-22 CRAN (R 3.2.3)
 memoise        1.0.0      2016-01-29 CRAN (R 3.2.3)
 openssl        0.9.1      2016-01-18 CRAN (R 3.2.3)
 R6             2.1.2      2016-01-26 CRAN (R 3.2.3)
 Rcpp           0.12.3     2016-01-10 CRAN (R 3.2.3)
 readr          0.2.2      2015-10-22 CRAN (R 3.2.3)
 rstudioapi     0.5        2016-01-24 CRAN (R 3.2.3)
 stringi        1.0-1      2015-10-22 CRAN (R 3.2.3)
 stringr        1.0.0      2015-04-30 CRAN (R 3.2.3)
 xml2           0.1.2      2015-09-01 CRAN (R 3.2.3)

**Comment by jennybc** [comment]
@djbiggs Is there any chance you need to restart R and reload `googlesheets`? All your versions look good to me.

**Comment by djbiggs** [comment]
Have tried that to no avail.

**Comment by jennybc** [comment]
Why does the `googlesheets` version above say "local" instead of github and a SHA? I'm not 100% convinced you're running current dev version.

**Comment by fennoguillermo** [comment]
im running into the same issue, tried downloading googlesheets from Github and get the following message

Downloading GitHub repo fennoguilermo/googlesheets@master
from URL https://api.github.com/repos/fennoguilermo/googlesheets/zipball/master
Error in download(dest, src, auth) : Not Found (HTTP 404).

**Comment by jennybc** [comment]
@fennoguillermo Can you show me the exact code you are using to install from GitHub? It should be this:

```
devtools::github_install("jennybc/googlesheets")
```

But the error message above indicates you are somehow looking for it in your own GitHub account. Which will only work if you have forked mine or some such.
