### ISSUE TITLE
Refresh the OAuth token

### ISSUE THREAD

**Issue by jennybc** [jennybc/googlesheets#20]
I think we need a function to query the validity of the current OAuth token and/or to trigger a manual refresh. Related to #15.

**Comment by jennybc** [comment]
I've confirmed my hunch about this over in #15. We need to build token auto-refresh into the data consumption functions.

**Comment by jzhaoo** [comment]
The refreshing of the token should be handled in httr's GET/POST/PUT functions when [`make_request()`](https://github.com/hadley/httr/blob/65f66f76d6b9624f1d2dfa5030c6f57d70970230/R/http--request.r) gets called inside the GET/POST/PUT functions. I don't get the odd application/binary responses from using the data consumption functions on a "stale" spreadsheet after #31.

**Comment by jennybc** [comment]
Any chance we're using different versions of `httr`? What's yours?

**Comment by jzhaoo** [comment]
0.6.1

**Comment by jennybc** [comment]
I'm on 0.6.1.9000. Humor me and install from GitHub. Authenticate before you go to bed and use `register()`. Then in the morning use, e.g., `get_via_lf()` and see what happens.

**Comment by jennybc** [comment]
Here's one commit since I last installed that is related to token refreshing …. I should also upgrade and see what happens….

https://github.com/hadley/httr/commit/e415faf42f1260b59bbe30e8648d4999fe83cbee

**Comment by jennybc** [comment]
I continue to have problems with this. Anecdotally a call to `list_spreadsheets()` seems to force token refresh and restoration of function more reliably than a call to `register_ss()`.

**Comment by jennybc** [comment]
I am no longer having problems with this. `httr` has not changed, so presumably we have gotten our house in order. Much has changed since late February.

For the record, here is how to manually force an existing token to refresh:

```
> library(googlesheets)

> gs_user()
No authorization yet in this session!
NOTE: a .httr-oauth file exists in current working directory.
 Run gs_auth() to use the credentials cached in .httr-oauth for this session.
No user currently authorized.

> jtoken <- gs_auth()
> gs_user()
          displayName: Jennifer Bryan
         emailAddress: jenny@stat.ubc.ca
                 date: 2015-06-16 04:25:43 GMT
         access token: valid
 peek at access token: ya29....VKSIQ
peek at refresh token: 1/D-s...Ihmao
> fresh_jtoken <- jtoken$refresh()
> gs_user()
          displayName: Jennifer Bryan
         emailAddress: jenny@stat.ubc.ca
                 date: 2015-06-16 04:25:43 GMT
         access token: valid
 peek at access token: ya29....12FfA
peek at refresh token: 1/D-s…Ihmao
```

You can verify that the refresh token is NOT changing, but the access token is. This is taking advantage of the R6 nature of the token class.

If we have problems with this again or there's legit need for it, I can always wrap the above in a proper function. But, for now? Closing this.

**Comment by jennybc** [comment]
Here's what such a function could look like:

```
#' Refresh the current authorization
#'
#' @keywords internal
gs_refresh <- function() {
  if(token_exists()) {
    .state$token$refresh()
  } else {
    message("no token to refresh")
    invisible(NULL)
  }
}
```
