### ISSUE TITLE
Error in readr::read_csv(x, readr::locale(encoding = encoding), ...) : 

### ISSUE THREAD

**Issue by slackline** [jennybc/googlesheets#200]
Hi,

Thanks for writing and maintaining `googlesheets` its really, really useful.

I've started getting the following error trying to download a sheet...

    gs_read(ss = cams,
            ws = cam.sheet)
    + Accessing worksheet titled "Plain List (2015-12-19)"
    Error in readr::read_csv(x, readr::locale(encoding = encoding), ...) : 
      unused argument (na.strings = c("", "NA"))
    > traceback()
    13: readr::read_csv(x, readr::locale(encoding = encoding), ...)
    12: parser(content, type = type, encoding = encoding, ...)
    11: parse_auto(raw, type, encoding, ...)
    10: httr::content(., type = "text/csv", na.strings = c("", "NA"), 
            encoding = "UTF-8", ...)
    9: function_list[[i]](value)
    8: freduce(value, `_function_list`)
    7: `_fseq`(`_lhs`)
    6: eval(expr, envir, enclos)
    5: eval(quote(`_fseq`(`_lhs`)), env, env)
    4: withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
    3: req %>% httr::content(type = "text/csv", na.strings = c("", "NA"), 
           encoding = "UTF-8", ...) %>% dplyr::as_data_frame() %>% dplyr::as.tbl()
    2: gs_read_csv(ss, ws = ws, ..., verbose = verbose)
    1: gs_read(ss = cams, ws = cam.sheet)

Reinstalled `googlesheets` to ensure I had the latest version but it persists.  Probably of relevance is the version of readr I have installed which is currently 0.2.2

If I can provide any more information please let me know.

**Comment by jennybc** [comment]
This puzzles me a bit. But short version: can you also update `httr`? And/or give me full output of `devtools::session_info()`?

**Comment by slackline** [comment]
Updated `httr` (I try and use stable so its 1.1.0 from CRAN) but still encountered the error.

Full `devtools::session_info()` follows...

    > devtools::session_info()
    Session info ---------------------------------------------------------------------------------------------------------------------
     setting  value                       
     version  R version 3.2.3 (2015-12-10)
     system   x86_64, linux-gnu           
     ui       X11                         
     language (EN)                        
     collate  C                           
     tz       <NA>                        
     date     2016-02-10                  
    
    Packages -------------------------------------------------------------------------------------------------------------------------
     package      * version    date       source           
     DBI          * 0.3.1      2014-09-24 CRAN (R 3.2.3)   
     Formula      * 1.2-1      2015-04-07 R-Forge (R 3.2.3)
     GGally       * 1.0.1      2016-01-14 CRAN (R 3.2.3)   
     Hmisc        * 3.17-1     2015-12-18 CRAN (R 3.2.3)   
     MASS           7.3-45     2015-11-10 CRAN (R 3.2.3)   
     Matrix         1.2-4      2016-01-26 R-Forge (R 3.2.3)
     MatrixModels   0.4-2      2015-08-24 R-Forge (R 3.2.3)
     R6             2.1.2      2016-01-26 CRAN (R 3.2.3)   
     RColorBrewer   1.1-2      2014-12-07 CRAN (R 3.2.3)   
     RSQLite      * 1.0.0      2014-10-25 CRAN (R 3.2.3)   
     Rcpp           0.12.3     2016-01-10 CRAN (R 3.2.3)   
     SparseM      * 1.7        2015-08-15 CRAN (R 3.2.3)   
     TH.data        1.0-7      2016-01-28 R-Forge (R 3.2.3)
     acepack        1.3-3.3    2014-11-24 CRAN (R 3.2.3)   
     assertthat     0.1        2013-12-06 CRAN (R 3.2.3)   
     cellranger     1.0.0      2015-06-20 CRAN (R 3.2.3)   
     cluster        2.0.3      2015-07-21 CRAN (R 3.2.3)   
     codetools      0.2-14     2015-07-15 CRAN (R 3.2.3)   
     colorspace     1.2-6      2015-03-11 CRAN (R 3.2.3)   
     curl           0.9.5      2016-01-23 CRAN (R 3.2.3)   
     devtools     * 1.10.0     2016-01-23 CRAN (R 3.2.3)   
     digest         0.6.9      2016-01-08 CRAN (R 3.2.3)   
     dplyr        * 0.4.3      2015-09-01 CRAN (R 3.2.3)   
     foreign      * 0.8-66     2015-08-19 CRAN (R 3.2.3)   
     ggplot2      * 2.0.0      2015-12-18 CRAN (R 3.2.3)   
     ggvis        * 0.4.2      2015-06-06 CRAN (R 3.2.3)   
     googlesheets * 0.1.0      2015-07-05 CRAN (R 3.2.3)   
     gridExtra      2.0.0      2015-07-14 CRAN (R 3.2.3)   
     gtable         0.1.2      2012-12-05 CRAN (R 3.2.3)   
     haven        * 0.2.0      2015-04-09 CRAN (R 3.2.3)   
     htmltools      0.3        2015-12-29 CRAN (R 3.2.3)   
     httpuv         1.3.3      2015-08-04 CRAN (R 3.2.3)   
     httr           1.1.0      2016-01-28 CRAN (R 3.2.3)   
     jsonlite       0.9.19     2015-11-28 CRAN (R 3.2.3)   
     knitr        * 1.12.3     2016-01-22 CRAN (R 3.2.3)   
     lattice      * 0.20-33    2015-07-07 R-Forge (R 3.2.3)
     latticeExtra   0.6-28     2016-02-09 CRAN (R 3.2.3)   
     lazyeval       0.1.10     2015-01-02 CRAN (R 3.2.3)   
     lubridate    * 1.5.0      2015-12-03 CRAN (R 3.2.3)   
     magrittr     * 1.5        2014-11-22 CRAN (R 3.2.3)   
     memoise        1.0.0      2016-01-29 CRAN (R 3.2.3)   
     mime           0.4        2015-09-03 CRAN (R 3.2.3)   
     multcomp       1.4-4      2016-02-03 R-Forge (R 3.2.3)
     munsell        0.4.2      2013-07-11 CRAN (R 3.2.3)   
     mvtnorm        1.0-5      2016-02-02 R-Forge (R 3.2.3)
     nlme           3.1-124    2016-01-20 CRAN (R 3.2.3)   
     nmisc        * 0.0.2.0000 2016-02-03 local            
     nnet           7.3-12     2016-02-02 CRAN (R 3.2.3)   
     openssl        0.9.1      2016-01-18 CRAN (R 3.2.3)   
     plyr           1.8.3      2015-06-12 CRAN (R 3.2.3)   
     polspline      1.1.12     2015-07-14 CRAN (R 3.2.3)   
     quantreg       5.19       2015-08-31 CRAN (R 3.2.3)   
     readr          0.2.2      2015-10-22 CRAN (R 3.2.3)   
     reshape        0.8.5      2014-04-23 CRAN (R 3.2.3)   
     reshape2     * 1.4.1      2014-12-06 CRAN (R 3.2.3)   
     rms          * 4.4-1      2015-12-21 CRAN (R 3.2.3)   
     rpart          4.1-10     2015-06-29 CRAN (R 3.2.3)   
     sandwich       2.3-4      2015-09-24 CRAN (R 3.2.3)   
     scales         0.3.0      2015-08-25 CRAN (R 3.2.3)   
     shiny        * 0.13.0     2016-01-12 CRAN (R 3.2.3)   
     stringi        1.0-1      2015-10-22 CRAN (R 3.2.3)   
     stringr      * 1.0.0      2015-04-30 CRAN (R 3.2.3)   
     survival     * 2.38-3     2015-07-02 CRAN (R 3.2.3)   
     tidyr        * 0.4.1      2016-02-05 CRAN (R 3.2.3)   
     xml2           0.1.2      2015-09-01 CRAN (R 3.2.3)   
     xtable         1.8-2      2016-02-02 R-Forge (R 3.2.3)
     zoo            1.7-13     2015-12-15 R-Forge (R 3.2.3)
    >

**Comment by jennybc** [comment]
You're running the CRAN version of `googlesheets` and, if you're running current `readr` and `httr`, you'll need to use GitHub version of `googlesheets`. I plan to update on CRAN in the next month or so.

**Comment by slackline** [comment]
Ah that makes sense, updated to your Github version of `googlesheets` and it all works fine.

Thanks for your assistance in resolving this, and again my thanks for writing and maintaining the package.
