### ISSUE TITLE
Unused argument error

### ISSUE THREAD

**Issue by bshor** [jennybc/googlesheets#207]
Today I'm getting an error upon reading a google sheet that I've never gotten before. It's easily reproducible from the help files. All reading fails. I'm using googlesheets 0.1.0 on Windows R 3.2.

```
gap_ss <- gs_gap()
oceania_csv <- gs_read(gap_ss, ws = "Oceania")
```
Gives me:

```
Accessing worksheet titled "Oceania"
Error in readr::read_csv(x, readr::locale(encoding = encoding), ...) : 
  unused argument (na.strings = c("", "NA"))
```

Errors go away upon install development versions of xml2 and googlesheets.

**Comment by jennybc** [comment]
Yes this happens when people upgrade to `httr v1.1.0`, which is not compatible with the CRAN version of `googlesheets`. The solution is, as you found, to re-install `googlesheets` from github.

**Comment by bshor** [comment]
Well, httr v1.1.0 is automatically installed by CRAN googlesheets 0.1.0! So its broken out of the box! Not good.

**Comment by jennybc** [comment]
I will update googlesheets on CRAN soon, which will be compatible with and require httr v1.1.0. So things won't be in this sub-optimal state for long.

**Comment by bshor** [comment]
Cool, thanks!
