### ISSUE TITLE
xmlSApply error

### ISSUE THREAD

**Issue by dcabanillas** [jennybc/googlesheets#209]
Running

gs_u <- gs_edit_cells(gs_u,ws="Data",input = data_adgroup, anchor = "A1")

I'm getting the following error
Range affected by the update: "A1:B2000"
Accessing worksheet titled "Data"
No encoding supplied: defaulting to UTF-8.
Error in UseMethod("xmlSApply") : 
  no applicable method for 'xmlSApply' applied to an object of class "c('xml_document', 'xml_node')"

Can someone help me?

Best.

**Comment by jennybc** [comment]
Can you show me package versions? Ideally from `devtools::session_info()` or `sessionInfo()` otherwise.

Can you run the examples for `gs_edit_cells()`?

**Comment by dcabanillas** [comment]
Hi Jennifer,
With gs_edit_cells() I can run the examples.

Session info
----------------------------------------------------------------------------------------------------------------------------------------------------------
 setting  value
 version  R version 3.2.3 (2015-12-10)
 system   x86_64, mingw32
 ui       RStudio (0.99.887)
 language (EN)
 collate  Spanish_Spain.1252
 tz       Europe/Paris
 date     2016-02-26

Packages
--------------------------------------------------------------------------------------------------------------------------------------------------------------
 package      * version date       source
 assertthat     0.1     2013-12-06 CRAN (R 3.2.3)
 cellranger     1.0.0   2015-06-20 CRAN (R 3.2.3)
 curl           0.9.5   2016-01-23 CRAN (R 3.2.3)
 DBI            0.3.1   2014-09-24 CRAN (R 3.2.3)
 devtools       1.10.0  2016-01-23 CRAN (R 3.2.3)
 digest         0.6.9   2016-01-08 CRAN (R 3.2.3)
 dplyr          0.4.3   2015-09-01 CRAN (R 3.2.3)
 googlesheets * 0.1.0   2015-07-05 CRAN (R 3.2.3)
 httr           1.1.0   2016-01-28 CRAN (R 3.2.3)
 jsonlite       0.9.19  2015-11-28 CRAN (R 3.2.3)
 magrittr       1.5     2014-11-22 CRAN (R 3.2.3)
 memoise        1.0.0   2016-01-29 CRAN (R 3.2.3)
 R6             2.1.2   2016-01-26 CRAN (R 3.2.3)
 RAdwords     * 0.1.6   2015-08-07 CRAN (R 3.2.3)
 Rcpp           0.12.3  2016-01-10 CRAN (R 3.2.3)


R version 3.2.3 (2015-12-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server >= 2012 x64 (build 9200)

locale:
[1] LC_COLLATE=Spanish_Spain.1252  LC_CTYPE=Spanish_Spain.1252
 LC_MONETARY=Spanish_Spain.1252 LC_NUMERIC=C
LC_TIME=Spanish_Spain.1252

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] RAdwords_0.1.6     googlesheets_0.1.0

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.3      digest_0.6.9     dplyr_0.4.3      assertthat_0.1
cellranger_1.0.0 R6_2.1.2         jsonlite_0.9.19  DBI_0.3.1
 magrittr_1.5
[10] httr_1.1.0       curl_0.9.5       rstudioapi_0.5   devtools_1.10.0
 tools_3.2.3      parallel_3.2.3   memoise_1.0.0
>



On Thu, Feb 25, 2016 at 6:46 PM, Jennifer (Jenny) Bryan <
notifications@github.com> wrote:

> Can you show me package versions? Ideally from devtools::session_info()
> or sessionInfo() otherwise.
>
> Can you run the examples for gs_edit_cells()?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jennybc/googlesheets/issues/209#issuecomment-188900475>
> .
>



-- 
bye
--david

**Comment by jennybc** [comment]
Will you please install `googlesheets` from GitHub and not CRAN? Several dependencies have updated since July 2015, with at least some breaking changes (especially from `httr`). I am actively working on a new version to send to CRAN myself. But in the meantime, you'll need to install the dev version. I'll be interested to hear if this solves your problem.

``` r
devtools::install_github("jennybc/googlesheets")
```

I'm somewhat surprised to not see `xml2` and `XML` listed above in session info. Regardless, they would be good packages to re-install as well.

```r
install.packages("XML")
devtools::install_github("hadley/xml2")
```

**Comment by jennybc** [comment]
@dcabanillas are you still having this problem? Can we close this?

**Comment by dcabanillas** [comment]
Right now it is right. Thanks.

On Tue, Mar 15, 2016 at 1:57 AM, Jennifer (Jenny) Bryan <
notifications@github.com> wrote:

> @dcabanillas <https://github.com/dcabanillas> are you still having this
> problem? Can we close this?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/jennybc/googlesheets/issues/209#issuecomment-196589934
>



-- 
bye
--david
