### ISSUE TITLE
gs_read_csv complains about mismatched content types

### ISSUE THREAD

**Issue by andrewheiss** [jennybc/googlesheets#212]
This may be related to the switch over to `readr`. The `gs_read_csv` function complains about mismatched content types and won't read sheets. Using `gs_read_listfeed` works as expected.

Reproducible example follows (using a [public spreadsheet](https://docs.google.com/spreadsheets/d/1mW9r6ztHCVI8yLCgGL6iFeHlW-tmnB6Vg29yKL-tys4/))

``` r
library(googlesheets)
library(dplyr)

# Sample public spreadsheet at 
# https://docs.google.com/spreadsheets/d/1mW9r6ztHCVI8yLCgGL6iFeHlW-tmnB6Vg29yKL-tys4/edit

# This doesn't work
df <- gs_key("1mW9r6ztHCVI8yLCgGL6iFeHlW-tmnB6Vg29yKL-tys4", verbose=TRUE) %>% 
  gs_read_csv(ws="Sheet1", verbose=FALSE) 
#> Worksheets feed constructed with public visibility
#> Error in stop_for_content_type(req, "text/csv"): Expected content-type:
#> text/csv
#> Actual content-type:
#> text/html; charset=UTF-8

# This works
df1 <- gs_key("1mW9r6ztHCVI8yLCgGL6iFeHlW-tmnB6Vg29yKL-tys4", verbose=TRUE) %>% 
  gs_read_listfeed(ws="Sheet1", verbose=FALSE) 
#> Worksheets feed constructed with public visibility



devtools::session_info()
#> Session info --------------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.2.3 (2015-12-10)
#>  system   x86_64, darwin13.4.0        
#>  ui       RStudio (0.99.879)          
#>  language (EN)                        
#>  collate  en_US.UTF-8                 
#>  tz       America/New_York            
#>  date     2016-03-01
#> Packages ------------------------------------------------------------------
#>  package      * version    date      
#>  assertthat     0.1        2013-12-06
#>  cellranger     1.0.0      2015-06-20
#>  clipr          0.2.0      2015-10-06
#>  colorspace     1.2-6      2015-03-11
#>  curl           0.9.6      2016-02-17
#>  DBI            0.3.1      2014-09-24
#>  devtools       1.10.0     2016-01-23
#>  digest         0.6.9      2016-01-08
#>  dplyr        * 0.4.3      2015-09-01
#>  evaluate       0.8        2015-09-18
#>  formatR        1.2.1      2015-09-18
#>  ggplot2      * 2.0.0      2015-12-18
#>  googlesheets * 0.1.0.9001 2016-03-01
#>  gtable         0.2.0      2016-02-26
#>  htmltools      0.3        2015-12-29
#>  httr           1.1.0      2016-01-28
#>  knitr          1.12.3     2016-01-22
#>  lazyeval       0.1.10     2015-01-02
#>  lubridate    * 1.5.0      2015-12-03
#>  magrittr       1.5        2014-11-22
#>  memoise        1.0.0      2016-01-29
#>  munsell        0.4.3      2016-02-13
#>  plyr           1.8.3      2015-06-12
#>  purrr          0.2.1      2016-02-13
#>  R6             2.1.2      2016-01-26
#>  rath         * 0.2        2015-07-18
#>  Rcpp           0.12.3     2016-01-10
#>  readr          0.2.2      2015-10-22
#>  reprex       * 0.0.0.9001 2016-02-10
#>  rmarkdown      0.9.5      2016-02-22
#>  rsconnect      0.4.1.11   2016-01-13
#>  rstudioapi     0.5        2016-01-24
#>  scales         0.4.0      2016-02-26
#>  stringi        1.0-1      2015-10-22
#>  stringr        1.0.0      2015-04-30
#>  tidyr          0.4.1      2016-02-05
#>  xml2           0.1.2      2015-09-01
#>  source                               
#>  CRAN (R 3.2.0)                       
#>  CRAN (R 3.2.0)                       
#>  CRAN (R 3.2.0)                       
#>  CRAN (R 3.2.0)                       
#>  CRAN (R 3.2.3)                       
#>  CRAN (R 3.2.0)                       
#>  CRAN (R 3.2.3)                       
#>  CRAN (R 3.2.3)                       
#>  CRAN (R 3.2.0)                       
#>  CRAN (R 3.2.0)                       
#>  CRAN (R 3.2.0)                       
#>  CRAN (R 3.2.3)                       
#>  Github (jennybc/googlesheets@debf4a8)
#>  CRAN (R 3.2.3)                       
#>  CRAN (R 3.2.3)                       
#>  CRAN (R 3.2.3)                       
#>  CRAN (R 3.2.3)                       
#>  CRAN (R 3.2.0)                       
#>  CRAN (R 3.2.3)                       
#>  CRAN (R 3.2.0)                       
#>  CRAN (R 3.2.3)                       
#>  CRAN (R 3.2.3)                       
#>  CRAN (R 3.2.0)                       
#>  CRAN (R 3.2.3)                       
#>  CRAN (R 3.2.3)                       
#>  local                                
#>  CRAN (R 3.2.3)                       
#>  CRAN (R 3.2.0)                       
#>  Github (jennybc/reprex@826ddf4)      
#>  CRAN (R 3.2.3)                       
#>  Github (rstudio/rsconnect@3034ab8)   
#>  CRAN (R 3.2.3)                       
#>  CRAN (R 3.2.3)                       
#>  CRAN (R 3.2.0)                       
#>  CRAN (R 3.2.0)                       
#>  CRAN (R 3.2.3)                       
#>  CRAN (R 3.2.0)
```

**Comment by jennybc** [comment]
This is characteristic of a permissions problem. I am slowing closing in on exactly what makes the csv link available vs the list feed vs the cell feed. I bet you can also read this sheet right now with `gs_read()` IFF you specify a cell range? Will you confirm that?

``` r
gs_read(..., range = "A1: D4")
```

or whatever range is correct / reasonable. It's just a test anyway.

Can you tell me the status of this sheet w/r/t "publishing on the web" (from File) and "sharing or public on the web" (from the Share button in the upper right corner of the browser)?

**Comment by andrewheiss** [comment]
I made it public with File > Publish to the web… 

![screen shot 2016-03-01 at 11 25 15](https://cloud.githubusercontent.com/assets/73663/13433568/645b7a68-dfa0-11e5-8d2c-a1e183381b54.png)

Using `gs_read(..., range = "blah")` works (but not specifying a range doesn't work, since `gs_read()` defaults to `gs_read_csv()` behind the scenes, correct?)

**Comment by andrewheiss** [comment]
It looks like publishing the sheet via File > Publish to web *and* making it public with the "Share" button in the top left corner (and generating a shareable link) fixes it. But both have to happen. 

Which is weird, since the Sheets API only really cares about the publish to web part, and not the public link sharing part, right?

**Comment by jennybc** [comment]
Perfect! Thanks.

> It looks like publishing the sheet via File > Publish to web and making it public with the "Share" button in the top left corner (and generating a shareable link) fixes it. But both have to happen. Which is weird, since the Sheets API only really cares about the publish to web part, and not the public link sharing part, right?

Yes what you say is true. When I grab with the `exportcsv` link (which is what `gs_read(..., range = NULL)` or `gs_read_csv()` does), it's probably more accurate to say I'm using Drive functionality. The official Sheets API methods of consumption are via list and cell feed. But god they are slow. So I try to use the csv link when possible. I need to have better messages re: why the chosen method consumption doesn't work. Or I should automatically shift to one that does ....

If you're satisfied for now, will you close this? I already have other open issues about this permission topic.

**Comment by smach** [comment]
Just FYI, I had a similar issue when I was running googlesheets on a Unix server remotely, but not when I was running it locally on my Mac. Adding the sharable link fixed this on the Unix box.
