### ISSUE TITLE
"Too Many Requests" Error

### ISSUE THREAD

**Issue by bshor** [jennybc/googlesheets#214]
I am trying to gs_read() a sheet that is privately shared with several other people. I haven't ever had any problems before today. I access individual worksheets one at a time from it.

Today, for the first time, after accessing about half of the worksheets, I get the following error:

```
Error in gsheets_GET(this_ws$exportcsv, to_xml = FALSE, use_auth = !ss$is_public) : 
  client error: (429) Too Many Requests (RFC 6585)
```

I don't understand how there can be too many requests. I access it maybe a dozen times per day, and my colleagues a dozen or so altogether. I'd never gotten this error before in over a month of using this sheet.

Any ideas?

**Comment by jennybc** [comment]
I have had this problem with too many **unauthenticated** requests. But I assume yours are with auth, if it's privately shared. So, no, this is new to me.

FWIW, I can tell you're using the CRAN version from the error message. I have no reason to believe I have changed anything that helps with this particular issue. And yet I have updated the scope I use for Google Drive. So there's some chance that installing `googlesheets` from GitHub will help. Otherwise, we  start Googling this error ...

**Comment by bshor** [comment]
Yes, the sheet is privately shared.

I installed the devtools version of googlesheets (which also installed all its dependencies) and I get the error in exactly the same spot, after the 6th worksheet access.

```
Error in function_list[[k]](value) : 
  Too Many Requests (RFC 6585) (HTTP 429). 
```

Just to give you a sense of my code, here are the first couple of lines:

```
 (my_sheets <- gs_ls())
  # (expect a prompt to authenticate with Google interactively HERE)
  my_sheets %>% glimpse()
    
  title = "State Legislative Pres Endorsements Only 2016"
  test <- gs_title(title)
  
  cands <- list()
  
  cands$bush <- test %>% gs_read(ws = "Bush")

```

**Comment by jennybc** [comment]
I think you really are discovering something about the API. Near-term workarounds that come to mind:

  * use `Sys.sleep()` in between these calls to space them out
  * do some Googling on the limits and error message and use this info to set your `Sys.sleep()` interval strategically
  * use `gs_download()` to get it as `xlsx` and use `readxl` to read the Sheet at your leisure

**Comment by willglanville** [comment]
Hi - 

I've also been receiving this error message regularly over the last week. Maybe Google have changed the quota rules.

**Comment by jennybc** [comment]
Either Google has changed or just more people are doing more things with `googlesheets`, so we're learning about this issue now.

Discussion of same from the node.js client:
https://github.com/theoephraim/node-google-spreadsheet/issues/40

My low tech advice stands for now -- try to space things out in time and/or do things "in bulk", rather than in pieces -- when this problem occurs.

**Comment by jennybc** [comment]
Can this be closed @bshor? Did spacing things out help?

I don't think there's really anything I can do about this in the package. In general, many people are getting more errors about too many requests and internal server errors. It feels like there has been some sort of phase shift with the Drive/Sheets API behaviour.

**Comment by willglanville** [comment]
gs_download() then readxl has worked for me, thanks for your help.

**Comment by Kreynor** [comment]
Hi all,
      I just start getting this problem too... same script working on the same document, so it seems something has changed on the drive API side of things. 

I've tried to put in a wait between calls, for me 6 seconds between sheets was the magic number. 

I also tried the gs_download() route ran into a similar problem. You start to get a quota block there too, though, I think it may be slightly more permissive.

**Comment by jennybc** [comment]
Thanks for the 6 seconds advice! This is driving me nuts too.

**Comment by diegogarcilazo** [comment]
I got this problem too... I was reading many sheets with lapply.
I've tried to put in a wait between calls, for 6 seconds too and it work ok.
Thanks.

**Comment by florisvdh** [comment]
I needed to read 27 sheets, which I did in a for loop. 6 seconds waiting within the loop made the process stop after 6 sheets (*Too Many Requests (RFC 6585) (HTTP 429)*), 7 seconds made it stop after 23 sheets, and with 8 seconds I succeeded. So the needed waiting time seems to depend on the number of sheets.

**Comment by thanosgatos** [comment]
I am still getting the same issue. As mentioned earlier, my best understanding is that it has to do with the number of lines read per *some* amount of time.

The solution with the manual delay, using `Sys.sleep()` works, but it feels like there could be a "prettier" solution to this. Any updates maybe?

**Comment by jennybc** [comment]
@thanosgatos I hadn't thought about this in a while. I added automatic retries to certain requests, because we were getting lots of Internal Server Error (HTTP 500). Perhaps I should take a similar approach to this, making it easy to space things out in time. I'll reopen so I remember to look at it.

**Comment by jennybc** [comment]
Oh I see I've already opened an issue for this, so re-closing this one.

**Comment by christinabrady** [comment]
Having this same issue. Sys.sleep is not working for me.

**Comment by stephenhky** [comment]
So should we simply pause a few seconds between requests?

**Comment by jennybc** [comment]
> So should we simply pause a few seconds between requests?

That is what `Sys.sleep()` does. I may very well work for you, although clearly others have not been able to solve it that way.

**Comment by jennybc** [comment]
There are lots of different forms of rate limit, so I assume that explains the mixed results here. E.g. some people may have already hit some limit for the day, in which cases spacing out the next few requests won't help.

**Comment by stephenhky** [comment]
thanks! @jennybc

**Comment by fishyl** [comment]
The 6 secs work for me. Thanks @jennybc !

**Comment by tomwwagstaff-product** [comment]
I'm encountering this error too. Still timing out even with 30 seconds' sleep. I'm wondering if it's better to do a try-catch and just keep hitting the API until you get something?

**Comment by romunov** [comment]
Works for me with 10 second `Sys.sleep`.

**Comment by Deleetdk** [comment]
I never had this issue previously, but suddenly popped up today despite no change in underlying data. A sleep duration of 6 seconds was fine for my purpose. In my case, I was loading data from 16 consecutive spreadsheets in a row and it would fail on the last one with the `Too Many Requests` error!

**Comment by arencambre** [comment]
I tried a Sys.sleep of 6 seconds and then 8 seconds while reading the 50+ worksheets in a particular sheet. It failed earlier with the longer wait time!

So far, the only permanent solution appears to be the "download as Excel" workaround.

**Comment by jennybc** [comment]
I think the deeper we get into the period where this API is deprecated ... the worse things like this are getting. That is, this package wraps an old Sheets API (v3) whereas its successor googlesheets4 wraps the current API (v4, hence the 4).

Remember: googlesheets4 is already capable of reading data, with auth:

https://github.com/tidyverse/googlesheets4

googledrive and gmailr are going to CRAN next week, having been retrofit to use gargle. This moves googlesheets4 to the top of my priority list and I'll soon be able to release it to CRAN, first with its current read-only capability. Then a subsequent release will gain write capability.
