### ISSUE TITLE
googlesheets_token.rds error

### ISSUE THREAD

**Issue by dcabanillas** [jennybc/googlesheets#216]
In my code I have
#non-interactive
gs_auth(token = "C:/Users/david.cabanillas/Documents/Rworkspace/SQR_NGRAM/googlesheets_token.rds")
#gs_auth(token = "C:/Users/david.cabanillas/Documents/Rworkspace/Adwords/googlesheets_token.rds")
suppressMessages(gs_auth(token = "googlesheets_token.rds", verbose = FALSE))

It works in interactive mode but in batch mode (in a task scheduler) I'm getting the following error:

Error: Cannot read token from alleged .rds file:
googlesheets_token.rds

**Comment by jennybc** [comment]
This error means the attempt to use `readRDS()` on the path was unsuccessful. Perhaps I should write that function to provide more useful info? But let's try to figure it out anyway.

In your script that gets run in batch mode via the task scheduler, can you insert something like this *prior* to the `gs_auth()` attempt that is failing?

``` r
file.info("C:/Users/david.cabanillas/Documents/Rworkspace/SQR_NGRAM/googlesheets_token.rds")
```

and make sure output is captured. If you see all `NA`s then the file is not readable by your script, at that time and place, given working directory. I sort of suspect this is true. In any case, this will probably be informative.

**Comment by jennybc** [comment]
Can this be closed @dcabanillas?

**Comment by dcabanillas** [comment]
Yes. Thanks.

On Tue, Mar 15, 2016 at 1:54 AM, Jennifer (Jenny) Bryan <
notifications@github.com> wrote:

> Can this be closed @dcabanillas <https://github.com/dcabanillas>?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/jennybc/googlesheets/issues/216#issuecomment-196589398
>



-- 
bye
--david
