### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by dcabanillas** [jennybc/googlesheets#218]
Sometimes I get the following error any suggestion to avoid or recover from this error? Thanks.

Error in function_list[[k]](value) : Internal Server Error (HTTP 500). 

32 stop(http_condition(x, "error", task = task, call = call)) 
31 httr::stop_for_status(.) 
30 function_list[[k]](value) 
29 withVisible(function_list[[k]](value)) 
28 freduce(value, `_function_list`) 
27 `_fseq`(`_lhs`) 
26 eval(expr, envir, enclos) 
25 eval(quote(`_fseq`(`_lhs`)), env, env) 
24 withVisible(eval(quote(`_fseq`(`_lhs`)), env, env)) 
23 httr::GET(the_url, google_token()) %>% httr::stop_for_status() 
22 gs_ls() 
21 gs_lookup(., "sheet_key", verbose) 
20 function_list[[k]](value) 
19 withVisible(function_list[[k]](value))

**Comment by jennybc** [comment]
500 is an error on the Google server side. I get them too. You just have to try again.

Please do re-open if it's happening very reliably with one specific call or something like that. But otherwise, I chalk it up to intermittent glitches with the Sheets API.

**Comment by dcabanillas** [comment]
Thanks Jenny,

Ok, I can assume that it is an error related to Google server side but my question is how my code could overcome this problem?

For example, my r code should write down 12000 x 26 cells, when the code arrives to 8000 x 26 I get the Error:  Error in function_list[[k]](value) : Internal Server Error (HTTP 500). 

How I can do it to turn to write down from 8000 to 12000? It is to following with the process.

Thanks.

**Comment by ceo4ced** [comment]
I too get the error and it's usually the first time authenticating after resting for awhile.  OSX system

**Comment by jennybc** [comment]
The current dev version here on github now has up to 5 automatic retries on all GETs that result in Internal Server Error (HTTP 500). So far I have had NO trouble building vignettes, running tests, or passing on Travis! This is huge progress. Try the dev version if you've been having trouble with these errors.

```
devtools::install_github("jennybc/googlesheets")
```

It probably needs some refinement, so am happy to get feedback.

**Comment by dcabanillas** [comment]
Thanks for the effor Jenny. I will try your solution.

Best.

On Mon, Mar 28, 2016 at 9:22 PM, Jennifer (Jenny) Bryan <
notifications@github.com> wrote:

> The current dev version here on github now has up to 5 automatic retries
> on all GETs that result in Internal Server Error (HTTP 500). So far I have
> had NO trouble building vignettes, running tests, or passing on Travis!
> This is huge progress. Try the dev version if you've been having trouble
> with these errors.
>
> devtools::install_github("jennybc/googlesheets")
>
> It probably needs some refinement, so am happy to get feedback.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/jennybc/googlesheets/issues/218#issuecomment-202541047>
>



-- 
bye
--david
