### ISSUE TITLE
Overcome error 500

### ISSUE THREAD

**Issue by dcabanillas** [jennybc/googlesheets#219]
Do you think that it could be a good way to overcome an error 500? Thanks.
 
      withCallingHandlers({ 
        gs_f <- gs_edit_cells(gs_f,ws="Data",input = totalchunk, anchor = anc,col_names = FALSE)
      }, error = function(e) { 
        message("error xxx") 
        withRestarts(invokeRestart("foo", ws="Data",input = totalchunk, anchor = anc,col_names = FALSE),  foo = function(gs_f,ws="Data",input = totalchunk, anchor = anc,col_names = FALSE) {gs_f<-gs_key(gs_f$sheet_key) 
        gs_f <- gs_edit_cells(gs_f,ws="Data",input = totalchunk, anchor = anc,col_names = FALSE)})
      })

**Comment by jennybc** [comment]
I am also getting a lot more 500 errors than usual!

This [Q + A](http://stackoverflow.com/questions/21328522/getform-retry-connection-upon-error) looks worth emulating. I will give it a try myself, since I am seeing 500s tonight too.

**Comment by jennybc** [comment]
Of course now that I need an internal server error, I can't get one! Except on Travis, where I keep getting them 😢.

I suggest you try something like this, which is lightly modified from [this gist](https://gist.github.com/ramhiser/9396c30c1c6e3fe2bf5e) by @ramhiser. Please let me know if this works for you, so we can record it in a vignette for other people who need to put `googlesheets` calls inside something that catches errors and retries w/ exponential backoff.

``` r
try_backoff <- function(expr, silent = FALSE, max_attempts = 10, verbose = FALSE) {
  for (attempt_i in seq_len(max_attempts)) {
    results <- try(expo = expr, silent = silent)
    if (inherits(results, "try-error")) {
      backoff <- runif(n = 1, min = 0, max = 2^attempt_i - 1)
      if (verbose) {
        message("Backing off for ", backoff, " seconds.")
      }
      Sys.sleep(backoff)
    } else {
      if (verbose) {
        message("Succeeded after ", attempt_i, " attempts.")
      }
      break
    }
  }
  results
}

# use with a googlesheets call that you can't afford to error
try_backoff(gs_read(ss), verbose = TRUE, max_attempts = 5)
```

**Comment by ReportMort** [comment]
I think there is a typo in line 3 of the `try_backoff` function above. I'm getting an error in R that says `unused argument (expo = expr)`. I believe you meant:

```
results <- try(expr = expr, silent = silent)
```

**Comment by dcabanillas** [comment]
Steve you are right.

On Monday I will publish the code but the problem is that I'm getting the
same error after 5 trails :(

Best.

On Sat, Mar 12, 2016 at 7:59 PM, Steve Mortimer <notifications@github.com>
wrote:

> I think there is a typo in line 3 of the try_backoff function above. I'm
> getting an error in R that says unused argument (expo = expr). I believe
> you meant:
>
> results <- try(expr = expr, silent = silent)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jennybc/googlesheets/issues/219#issuecomment-195790367>
> .
>



-- 
bye
--david

**Comment by jennybc** [comment]
Yes! Not sure how I managed to do that, because I did actually use this function before I put it here. Fixed above.

**Comment by jennybc** [comment]
I want to put this sort of wrapper function into the package. I'm getting more errors these days that merit a few retry attempts. In addition to 500 internal server error, getting this:

```
Too Many Requests (RFC 6585) (HTTP 429)
```

but I can't find exact quota or rate info to help me avoid triggering this ☹️.

**Comment by dcabanillas** [comment]
Hi,

The function code try-catch
try_backoff <- function(expr, silent = FALSE, max_attempts = 10, verbose =
FALSE) {
  print("expr")
  #print(str(expr))
  for (attempt_i in seq_len(max_attempts)) {
    results <- try(expr, silent = silent)
    if (inherits(results, "try-error")) {
      backoff <- runif(n = 1, min = 0, max = 2^attempt_i - 1)
      if (verbose) {
        message("Backing off for ", backoff, " seconds.")
      }
      Sys.sleep(backoff)
    } else {
      if (verbose) {
        message("Succeeded after ", attempt_i, " attempts.")
      }
      break
    }
  }
  results
}



A log where my code is recovering from an HTTP 500 using try_backoff
function. But it doesn't means that it overcome an error. if the number of
attempts is higher than N (5 in my cases) the code is finalized :(

* Connection #0 to host adwords.google.com left intact
Successful copy! New sheet is titled "892-8975-DATE-2016-03-14".
Range affected by the update: "A1:R1001"
Accessing worksheet titled "Data"
Sheet successfully identified: "892-8975-DATE-2016-03-14"
Accessing worksheet titled "Data"
Worksheet "Data" dimensions changed to 1001 x 26.
Worksheet "Data" successfully updated with 18018 new value(s).
Succeeded after 1 attempts.
Sheet successfully identified: "892-8975-DATE-2016-03-14"
Succeeded after 1 attempts.
Range affected by the update: "A1001:R2001"
Accessing worksheet titled "Data"
Sheet successfully identified: "892-8975-DATE-2016-03-14"
Accessing worksheet titled "Data"
Worksheet "Data" dimensions changed to 2001 x 26.
Worksheet "Data" successfully updated with 18018 new value(s).
Error in function_list[[k]](value) : Internal Server Error (HTTP 500).
Backing off for 0.35867045330815 seconds.
Range affected by the update: "A1001:R2001"
Accessing worksheet titled "Data"
Error in function_list[[k]](value) : Conflict (HTTP 409).
In addition: Warning message:
In doTryCatch(return(expr), name, parentenv, handler) :
  restarting interrupted promise evaluation
Backing off for 2.80856150574982 seconds.
Range affected by the update: "A1001:R2001"
Accessing worksheet titled "Data"
Error in function_list[[k]](value) : Conflict (HTTP 409).
In addition: Warning message:
In doTryCatch(return(expr), name, parentenv, handler) :
  restarting interrupted promise evaluation
Backing off for 6.75054567842744 seconds.
Range affected by the update: "A1001:R2001"
Accessing worksheet titled "Data"
Error in function_list[[k]](value) : Conflict (HTTP 409).
In addition: Warning message:
In doTryCatch(return(expr), name, parentenv, handler) :
  restarting interrupted promise evaluation
Backing off for 13.4699615207501 seconds.
Range affected by the update: "A1001:R2001"
Accessing worksheet titled "Data"
Error in function_list[[k]](value) : Conflict (HTTP 409).
In addition: Warning message:
In doTryCatch(return(expr), name, parentenv, handler) :
  restarting interrupted promise evaluation
Backing off for 9.85137281985953 seconds.
Sheet successfully identified: "892-8975-DATE-2016-03-14"
Succeeded after 1 attempts.




On Mon, Mar 14, 2016 at 12:38 AM, Jennifer (Jenny) Bryan <
notifications@github.com> wrote:

> I want to put this sort of wrapper function into the package. I'm getting
> more errors these days that merit a few retry attempts. In addition to 500
> internal server error, getting this:
>
> Too Many Requests (RFC 6585) (HTTP 429)
>
> but I can't find exact quota or rate info to help me avoid triggering this
> ☹️.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jennybc/googlesheets/issues/219#issuecomment-196083149>
> .
>



-- 
bye
--david

**Comment by jennybc** [comment]
@dcabanillas We have to have a maximum number of retries. What do you want to happen when that max gets hit? You're correct, right now the error is returned. The function could be written differently. It all depends on if you really want your script to continue, ie. does it make sense to continue despite lack of success. You could also increase `max_attempts`.

Sidebar: Are these 409 errors typical of your experience?

**Comment by dcabanillas** [comment]
Hi,

You are right, we should to have a max number of trials. In my humble
opinion we should have an environment variable that save the status. sheet,
Nº rows write down, ... any information useful to recover from an error.

Best.

On Mon, Mar 14, 2016 at 4:44 PM, Jennifer (Jenny) Bryan <
notifications@github.com> wrote:

> @dcabanillas <https://github.com/dcabanillas> We have to have a maximum
> number of retries. What do you want to happen when that max gets hit?
> You're correct, right now the error is returned. The function could be
> written differently. It all depends on if you really want your script to
> continue, ie. does it make sense to continue despite lack of success. You
> could also increase max_attempts.
>
> Sidebar: Are these 409 errors typical of your experience?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jennybc/googlesheets/issues/219#issuecomment-196375161>
> .
>



-- 
bye
--david

**Comment by jennybc** [comment]
It looks like you are uploading data in batches? So you could simply stop trying once you hit `max_attempts` but here's what you're also hoping for:

  * function doesn't return error, just exits gracefully, even though last request generated 500 internal server error
  * the sheet, http exit status, and task status ("n rows uploaded") are recorded somewhere for you to read and deal with later

Do I understand correctly?

**Comment by dcabanillas** [comment]
Yes.

Some time ago you suggest me that it could be convenient to chunk the data
that I would like to upload. I have a function that take a huge dataframe
(size S) and call to gs_edit_cells N times. This update will be done S/N
times.

Best.

PS. Thanks for all your time and effort.


On Mon, Mar 14, 2016 at 5:11 PM, Jennifer (Jenny) Bryan <
notifications@github.com> wrote:

> It looks like you are uploading data in batches? So you could simply stop
> trying once you hit max_attempts but here's what you're also hoping for:
>
>    - function doesn't return error, just exits gracefully, even though
>    last request generated 500 internal server error
>    - the sheet, http exit status, and task status ("n rows uploaded") are
>    recorded somewhere for you to read and deal with later
>
> Do I understand correctly?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jennybc/googlesheets/issues/219#issuecomment-196388153>
> .
>



-- 
bye
--david

**Comment by jennybc** [comment]
OK I will think on this.

Since you have the most experience, what is a good chunk size, i.e. number of rows to send at once? Someone else is suffering today (#222).

**Comment by dcabanillas** [comment]
Hi,

I am testing with 1000 x 15 and 1000 x 20 in the results sames correct. But
it is a rule of thumb.

best.

On Mon, Mar 14, 2016 at 5:24 PM, Jennifer (Jenny) Bryan <
notifications@github.com> wrote:

> OK I will think on this.
>
> Since you have the most experience, what is a good chunk size, i.e. number
> of rows to send at once? Someone else is suffering today (#222
> <https://github.com/jennybc/googlesheets/issues/222>).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jennybc/googlesheets/issues/219#issuecomment-196396477>
> .
>



-- 
bye
--david

**Comment by jennybc** [comment]
I opened an issue for putting some sort of function like the above into the package itself: https://github.com/jennybc/googlesheets/issues/225.

**Comment by ReportMort** [comment]
FWIW, I posted on Google Drive Help Forum and another user provided an explanation for HTTP 500 errors:

> The error occurs if the sheet is open (by any user), and works if closed by all

I've submitted feedback to Google, but not really expecting any changes on their part. 
Link to post on the help forum:
[https://productforums.google.com/forum/#!msg/drive/CmFxCpAPQ1Q/KNeHtKawBQAJ](https://productforums.google.com/forum/#!msg/drive/CmFxCpAPQ1Q/KNeHtKawBQAJ)

**Comment by jennybc** [comment]
@ReportMort 

Thanks for the interesting link! I'm in the midst of a `googlesheets` CRAN submission, so am re-compiling vignettes and running tests a lot. And the huge increase in HTTP errors is maddening. Glad others are noticing and reporting.

I don't really buy the explanation about sheets being open, as that is practically never the case for me. But there is something very specific about the first access, i.e. that often produces the 500 error. And the subsequent calls work. Very strange.

**Comment by jennybc** [comment]
*Apologies if you see this notification more than once: I'm posting it on all the threads re: HTTP 500 errors*

The current dev version here on github now has up to 5 automatic retries on all GETs that result in Internal Server Error (HTTP 500). So far I have had NO trouble building vignettes, running tests, or passing on Travis! This is huge progress. Try the dev version if you've been having trouble with these errors.

```
devtools::install_github("jennybc/googlesheets")
```

It probably needs some refinement, so am happy to get feedback.

**Comment by jennybc** [comment]
Fellow 500 internal server error sufferers:

Are you using the built-in client_id and secret? Or are you providing your own? If you have no idea what I'm talking about, you're using the built-in ones 😁. I'm beginning to wonder if this is part of the puzzle. Maybe the fact that so many people are using the *same* client_id and secret is problematic? If that's true, I should be encouraging more people to use their own client_id and secret. Especially anyone using the package heavily.

**Comment by dcabanillas** [comment]
I'm using my own client_id and secret.

**Comment by dcabanillas** [comment]
Hi Jenny, again
Using your  last version devtools::install_github("jennybc/googlesheets")

And calling to 
gs_f<-gs_key(gs_f$sheet_key)

I'm getting the following error.

 Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached

**Comment by cmedinag** [comment]
I'm using my own keys. I launch the following code:
`googlekeys <- read.csv("../googlekeys.txt", header = T)
client_id <- as.character(googlekeys$client_id[1])
client_secret <- as.character(googlekeys$client_secret[1])

# Launching auth processs upon googlesheets package.
# Providing saved token and my own project keys
# Since gs_auth goes to authorize over Drive API, and we are under a google apps for business which has Drive API banned, it will assume the token but a 403 error will be returned.
# Hence the try, in order that the script execution don't get halted.
try(gs_auth(token = google_token, key = client_id, secret = client_secret, verbose = T))

#gs_key Access the spreadsheet using loaded authentication.
key <- "xxxxxxxxx"
sheetname <- "blablabla"

spreadsheet <- gs_key(key) #Reference to the corresponding spreadsheet`

In the last line is where I get the error 500. In my case ALWAYS fails 5 times before working.

`> packageVersion("googlesheets")
[1] ‘0.1.0.9001’`

**Comment by jennybc** [comment]
@dcabanillas I'm not sure that has anything to do with the update or the 500 errors. It could just be exactly what it says: timeout. Is this happening across the board?

@cmedinag If you want the automatic retries, which it seems you need!, please upgrade to the current dev version: `devtools::install_github("jennybc/googlesheets")`. I'm curious about your auth comments. I think I've seen another case of this and @craigcitro might be interested in hearing more. Because the attempt to get info on you as a user should still work, yet somehow does not (hence the 403 error).

**Comment by cmedinag** [comment]
About the 403...

I'm running the package to access a sheet that is in a google apps domain. The administrators of the domain determined that Drive API cannot be used due to security reasons. But the Spreadsheets API is free to use in the domain.

Since the gs_auth seems to perform any operation to the drive API (maybe gs_ls() to list the spreadsheets in drive), it will always return a forbidden status (403).

So, every operation involving Drive API (list, create, delete or clone a spreadsheet) will return a 403.

I can only edit already existing spreadsheets (add, edit or delete rows or sheets inside a existing sheet).

Derived from this, since this script is intended to run offline, I needed, first, to download my user credentials (the token) to avoid the online user-pass request screen, and last to avoid the interruption of the script when calling to gs_auth. 

For the first part I found a chunk of code somewhere in the web (if you're interested in that, I can provide the code with my own adaptations). For the latter, if you run a R script and an error happens, the script will halt at the point of the error and stop immediatly the execution. Because of that, I needed to embed the gs_auth (which is doomed to fail) inside a try statement.

Hope this explanation helps. If you need more detail, I'll be happy to answer your doubts.

**Comment by dcabanillas** [comment]
Hi Jenny,

In this case, we can not consider the tool confident/ACID in order to use
this as a way to store data, at least in heay processes. Right?

On Wed, Mar 30, 2016 at 4:10 PM, cmedinag <notifications@github.com> wrote:

> About the 403...
>
> I'm running the package to access a sheet that is in a google apps domain.
> The administrators of the domain determined that Drive API cannot be used
> due to security reasons. But the Spreadsheets API is free to use in the
> domain.
>
> Since the gs_auth seems to perform any operation to the drive API (maybe
> gs_ls() to list the spreadsheets in drive), it will always return a
> forbidden status (403).
>
> So, every operation involving Drive API (list, create, delete or clone a
> spreadsheet) will return a 403.
>
> I can only edit already existing spreadsheets (add, edit or delete rows or
> sheets inside a existing sheet).
>
> Derived from this, since this script is intended to run offline, I needed,
> first, to download my user credentials (the token) to avoid the online
> user-pass request screen, and last to avoid the interruption of the script
> when calling to gs_auth.
>
> For the first part I found a chunk of code somewhere in the web (if you're
> interested in that, I can provide the code with my own adaptations). For
> the latter, if you run a R script and an error happens, the script will
> halt at the point of the error and stop immediatly the execution. Because
> of that, I needed to embed the gs_auth (which is doomed to fail) inside a
> try statement.
>
> Hope this explanation helps. If you need more detail, I'll be happy to
> answer your doubts.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/jennybc/googlesheets/issues/219#issuecomment-203449218>
>



-- 
bye
--david
