### ISSUE TITLE
Error using gs_read

### ISSUE THREAD

**Issue by ps0ares** [jennybc/googlesheets#221]
I've found the following error using googlesheets along with readr version 0.2.2:

> gap_ss <- gs_gap()
> oceania_csv <- gs_read(gap_ss, ws = "Oceania")
Accessing worksheet titled "Oceania"
Error in readr::read_csv(x, readr::locale(encoding = encoding), ...) : 
  unused argument (na.strings = c("", "NA"))

In readr::read_csv documentation there's a 'na' argument instead of 'na.strings'. May it be a recent change?

**Comment by jennybc** [comment]
This actually means you need to update `httr`. Can you please do `install.packages("httr")` and restart R and try again? That should solve it. There will be a new version of `googlesheets` soon that makes this version dependency clear.

**Comment by ps0ares** [comment]
I already had the latest version of `httr` (1.1.0).

**Comment by jennybc** [comment]
Sorry, I think it also best that you run the GitHub version of `googlesheets`: `devtools::install_github("jennybc/googlesheets")`. If that is already the case (and you've verified your problem in a fresh R session, ie. not the one where you did installs/updates), would you please provide the output of `devtools::session_info()`?

**Comment by ps0ares** [comment]
Thanks. I installed your development version from GitHub and the error is gone.

**Comment by jennybc** [comment]
Great!
