### ISSUE TITLE
gs_edit_cells() is not working for large number of rows

### ISSUE THREAD

**Issue by akshanshgupta** [jennybc/googlesheets#222]
I have a data frame with 4677 rows x 15 columns. When I issue a gs_edit_cells() to update the sheet with new values, it gets stuck and nothing happens.

**Comment by jennybc** [comment]
Does it work with your workflow to put this data into a Google Sheet via `gs_upload()`? That will work better.

If you really need to use `gs_edit_cells()` ... maybe you should see if doing this in, say, 5 batches of 1000 rows works better in practice. There is no structural problem with what you want to do, but that doesn't mean it works well.

**Comment by jennybc** [comment]
See #219 for someone coping with the same problem by batching uploads (but also running them inside a function to catch errors and retry).

**Comment by akshanshgupta** [comment]
gs_upload() worked well for me. But I would like to try to batch upload for a more elegant solution.

**Comment by jennybc** [comment]
The two open issues relevant to this are https://github.com/jennybc/googlesheets/issues/225 (which is about creating a retry wrapper for these batched edits) and also https://github.com/jennybc/googlesheets/issues/183 for resumable uploads (though that will still be a whole file upload, not sending data into a specific worksheet).
