### ISSUE TITLE
all the permissions things

### ISSUE THREAD

**Issue by jennybc** [jennybc/googlesheets#224]
As of 2022-02-03, the googlesheets package has been archived on CRAN.
I'm closing all issues and pull requests prior to archiving this GitHub repo.

Learn more at:

<https://github.com/jennybc/googlesheets#readme>

**Comment by katossky** [comment]
What needs to be done here? I am using your (great) package and I need to use permission capabilities. I can help improving this part but I need some guidance to start with ;)

**Comment by jennybc** [comment]
This is being addressed in googledrive:

https://github.com/tidyverse/googledrive

a package we're actively developing right now to wrap the Drive API v3. It already has permission editing capability, so see if it does what you need.
