### ISSUE TITLE
function to catch error and retry n times with back off

### ISSUE THREAD

**Issue by jennybc** [jennybc/googlesheets#225]
This is what https://github.com/jennybc/googlesheets/issues/219 morphed into. 500 internal server error is the main error to treat this way but also 429 Too Many Requests.

**Comment by stephencunningham** [comment]
+1 to this. Seeing the same issue.

Also seeing a lot of 500 errors. Sometimes it works, sometimes not. 

Googlesheets is great, would love to see this resolved!

Thanks :)

**Comment by jennybc** [comment]
Consider wrapping all the httr:VERBs in this way and then only use those. Package wide.
