### ISSUE TITLE
oauth_listener() needs an interactive environment in trying to run Shiny app on shinyapps.io

### ISSUE THREAD

**Issue by klittle314** [jennybc/googlesheets#235]
Hi, I had successfully run a Shiny app that uses googlesheets package, both locally and on the shinyapps.io server....I updated to version 0.2.0 and now when I try to start the app on shinyapps.io server, the app fails with message "oauth_listener() needs an interactive environment" 

The shiny app runs locally without error (evidently happy to find the .httr-oauth in the working directory.   This file is loaded along with everything else of course in publishing the app to shinyapps.io ...and everything used to work!

Wonder if this is related to oauth issues discussed last year? 

 I read thru your article on authorization dated 26 Mar 2016 and it seems relevant but I am sorry I couldn't figure out exactly what to do to fix my problem.

Maybe I hit the limit of refresh tokens?   I have other apps accessing Google Drive and I have been actively testing...not sure what action I should take to comply with Google's advice to write code to account for fact "There is currently a limit of 25 refresh tokens per user account per client. If the limit is reached, creating a new token automatically invalidates the oldest token without warning." 

thanks for any light you can shed.

BACKGROUND
> rsconnect::appDependencies()
        package  version source
1            BH 1.60.0-1   CRAN
2           DBI    0.3.1   CRAN
3           PKI    0.1-3   CRAN
4            R6    2.1.2   CRAN
5         RCurl 1.95-4.8   CRAN
6       RJSONIO    1.3-0   CRAN
7          Rcpp   0.12.4   CRAN
8       Rmonkey    0.3.1   CRAN
9           XML 3.98-1.4   CRAN
10   assertthat      0.1   CRAN
11    base64enc    0.1-3   CRAN
12       bitops    1.0-6   CRAN
13   cellranger    1.0.0   CRAN
14         curl    0.9.6   CRAN
15     devtools   1.10.0   CRAN
16       digest    0.6.9   CRAN
17        dplyr    0.4.3   CRAN
18        git2r   0.13.1   CRAN
19 googlesheets    0.2.0   CRAN
20    htmltools      0.3   CRAN
21       httpuv    1.3.3   CRAN
22         httr    1.1.0   CRAN
23     jsonlite   0.9.19   CRAN
24     lazyeval   0.1.10   CRAN
25     magrittr      1.5   CRAN
26      memoise    1.0.0   CRAN
27         mime      0.4   CRAN
28       miniUI    0.1.1   CRAN
29      openssl    0.9.2   CRAN
30     openxlsx    3.0.0   CRAN
31      packrat  0.4.7-1   CRAN
32         plyr    1.8.3   CRAN
33        purrr    0.2.1   CRAN
34        readr    0.2.2   CRAN
35     reshape2    1.4.1   CRAN
36    rsconnect  0.4.2.1   CRAN
37   rstudioapi      0.5   CRAN
38        shiny   0.13.2   CRAN
39    shinyapps   0.3.63 github
40      shinyjs    0.5.2   CRAN
41      stringi    1.0-1   CRAN
42      stringr    1.0.0   CRAN
43        tidyr    0.4.1   CRAN
44      whisker    0.3-2   CRAN
45        withr    1.0.1   CRAN
46         xml2    0.1.2   CRAN
47       xtable    1.8-2   CRAN
48         yaml   2.1.13   CRAN

> sessionInfo()
R version 3.2.3 (2015-12-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] BH_1.60.0-1        reshape2_1.4.1     openxlsx_3.0.0     dplyr_0.4.3       
 [5] googlesheets_0.2.0 jsonlite_0.9.19    Rmonkey_0.3.1      stringi_1.0-1     
 [9] httr_1.1.0         RCurl_1.95-4.8     bitops_1.0-6       curl_0.9.6        
[13] devtools_1.10.0    rsconnect_0.4.2.1  shinyapps_0.3.63   shinyjs_0.5.2     
[17] shiny_0.13.2      

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.4      xml2_0.1.2       magrittr_1.5     xtable_1.8-2    
 [5] R6_2.1.2         stringr_1.0.0    plyr_1.8.3       tools_3.2.3     
 [9] packrat_0.4.7-1  parallel_3.2.3   miniUI_0.1.1     DBI_0.3.1       
[13] htmltools_0.3    lazyeval_0.1.10  openssl_0.9.2    digest_0.6.9    
[17] assertthat_0.1   RJSONIO_1.3-0    readr_0.2.2      purrr_0.2.1     
[21] memoise_1.0.0    mime_0.4         cellranger_1.0.0 httpuv_1.3.3

**Comment by jennybc** [comment]
This error is characteristic of the token not being found or usable. I have changed the scopes used by `googlesheets` and tokens are cached in a way such that scope is recorded. So you probably do need to copy a very recent `.httr-oauth` over to wherever you keep the one that has previously provided auth for your app. Suggestion: use the `.httr-oauth` associated with your local success running this very same app, post-upgrade to v0.2.0.

**Comment by klittle314** [comment]
thanks for quick response.   I tried your suggestion, no luck, welcome any other ideas.  Will post to google group/shiny apps, too.  (I am also exchanging info via SurveyMonkey API but no httr-oauth file needed there)

DETAILS
 I opened a new RStudio project and ran gs_auth and it successfully downloaded to the working directory.   I checked that I could communicate with GoogleDrive.   I copied the httr-oauth file to the working directory of the Shiny app and tested the app in local mode.  app worked fine.   However, same error on upload to shinyapps.io:

Error in value[[3L]](cond) : 
  oauth_listener() needs an interactive environment.
Calls: local ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted

**Comment by jennybc** [comment]
Duly noted. Honestly I have not tried the auth with Shiny apps in a long time. In my defence, I think a better universal Google auth solution is coming (https://github.com/ropenscilabs/gauth) and I'm sort of hoping to procrastinate on Shiny until I can just rip out my stuff and use `gauth`. But I will try this myself soon and see if it fails for me and if I can learn anything.

Just to be sure: are you absolutely certain you need auth to do what you Shiny app does? What does your app do? Is the source for it online anywhere?

**Comment by klittle314** [comment]
Thanks for replying.   I built a couple of minimal examples (one REALLY minimal) that still fails, e.g. [https://github.com/klittle314/googlesheet_shinyapp_tiny_example.git](url).

My production app reads  data to/from a Google Sheet, to enable our users to create a SurveyMonkey survey.   We use the Google Sheet to store survey metadata.   We do this to use a master SurveyMonkey account, users just access the Shiny app and entering a few fields, the app makes the SurveyMonkey survey.    On the other side, if the user enters his/her email address, the app shows a list of SurveyMonkey surveys that are available for the user to summarize, making an Excel sheet based on data pulled over the SurveyMonkey API.

So, ultimately, all I need to be able to do is have my app be able to read and write to a private Google Sheet (it can't be public because it has email addresses and information about our programs...nothing super secret, just nice to have slightly protected.)

**Comment by MarkEdmondson1234** [comment]
In the meantime, you can run the gs_auth() locally with the options set so you can upload the httr-oauth file (if you leave it default you can't see the hidden file to upload ;) )

Something like this:

```r
options("httr_oauth_cache" = "gs_auth")
library(googlesheets)
gs_auth() ## go through the flow
```

Then upload the `gs_auth` file to your Shiny instance, and run your googlesheets functions and they should run normally.

**Comment by klittle314** [comment]
Mark thanks for suggestion not sure I follow.   the .httr-oauth file is dropped into my working directory automatically by the call gs_auth() (and in all my apps over the past six months that is what happens, the .httr-oauth file drops into the working directory.)

![wdpix](https://cloud.githubusercontent.com/assets/3459577/14255685/d55bc70c-fa5a-11e5-9dc3-3a3590c56b10.png)

setting option as you suggested does not seem to affect anything.  (e.g. just ran the tiny example locally and then it failed again on upload to shinyapps.io)   

To see if there is some setting messed up on my local system that I can't find, would you mind trying out the tiny example [https://github.com/klittle314/googlesheet_shinyapp_tiny_example.git](url)?

**Comment by MarkEdmondson1234** [comment]
Thanks, that helped :) I have a working version of your git here: https://mark.shinyapps.io/googlesheet_bug/ (with my sheet example)

* Got rid of some unnecessary libraries
* Deleted the global.R and put the calls in a reactive expression (this speeds up rendering)
* Set option `    options("googlesheets.httr_oauth_cache" = "gs_auth")`
* Put `gs_auth()` in the reactive call 
* Set the option locally too, then ran `gs_auth(new_user=TRUE)` to get the `gs_auth`file

The option means you can then select the file `gs_auth` in the dialogue when uploading to shinyapps.io, otherwise it is not being uploaded unless you explicitly select it. 

Here are my ui.R and server.R

```r
##ui.R
library(shiny)
#tiny inimal example ui

shinyUI(fluidPage(
  
  titlePanel("GoogleSheet Download"),
  
  sidebarLayout(
    
    sidebarPanel(
      helpText("Test of loading and downloading data from a Google sheet"),
      downloadButton('downloadData', 'Download'),
      width=3
      
    ),
    
    mainPanel(
      h2('Fruit Available'), hr(),
      dataTableOutput('table1')
      
    )
  )
 )
)


###server.R
library(shiny)
library(googlesheets)

shinyServer(function(input, output, session) {
  
  gs_df <- reactive({
    #Example key for my simple spreadsheet on google drive
    options("googlesheets.httr_oauth_cache" = "gs_auth")
    gskey2 <- "1XNrRWWFR-5Ik60miiLMQX2QIRoKR03qAnMgqMozSYY4"
    
    gs_auth()
    # register the googlesheet
    gs_file <- gs_key(x=gskey2)
    gs_df <- head(gs_read(gs_file))
  })

  # print table using input from Google Sheet
  output$table1 = renderDataTable(gs_df())
  
  # download file
  output$downloadData <- downloadHandler(
      filename = function() {
        paste('data-', Sys.Date(), '.csv', sep='')
      },
      content = function(con) {
        write.csv(df, con)
      }
    )
 }
)


```

**Comment by klittle314** [comment]
Mark thank you.  Magical!   Something must have changed from several months ago in the RStudio/shiny environment and the way I work things.   I notice now that I should pay attention to the file list for publishing (in early shinyapps.io versions that did not appear?  the deployApp() swept up everything in the working directory I think!)
![rstudio publish](https://cloud.githubusercontent.com/assets/3459577/14261157/0558f316-fa75-11e5-93d1-b2a5486127a9.png)

I appreciate the tip on using global.R and putting the call in reactive expression.   I have to rethink my practice (I used global.R in the past as I was building the app and testing before making everything reactive the right way.)

Now I will try to get the production app to play nice.

PS in your version of the tiny example we need write.csv(gs_df()).

` # download file
  output$downloadData <- downloadHandler(
      filename = function() {
        paste('data-', Sys.Date(), '.csv', sep='')
      },
      content = function(con) {
        write.csv(df, con)
      }
    )`

**Comment by MarkEdmondson1234** [comment]
Glad it helped, made the edit for reference.  Yes I think it did used to uploaded everything, but it may have just been the missing explict gs_auth() that needed to run that session that fixed it, as if its not there the functions will run it themselves (and try to interactively?)

**Comment by klittle314** [comment]
Big challenge:  the production app not only reads the google sheet but also has to write to the google sheet. (we use the google sheet as our master list of SurveyMonkey survey metadata--one part of the app creates a new SurveyMonkey survey and so updates the google sheet with a new record.)

My first look is worrying me about a cascade of reactive events.   When I write to the googlesheet, will that cause the reactive function gs_df to update?   Part of me thinks NO as there are no reactive inputs that are changing [the file changing is not an event??]

I will just have to try and see what happens, my knowledge of reactivity is too shallow to give a strong prediction!

**Comment by MarkEdmondson1234** [comment]
It should be ok if you have buttons for loading and saving the data and wrap up the call in `eventReactive(input$fetch_data, {blah})` instead of `reactive({})` as a precaution, but even then I think it will work as googlesheets will only load once on load then remain stationary until you force it to run again.

**Comment by klittle314** [comment]
thx, would like to avoid LOAD button (ultimate user does not care about the google sheet).  We have a SUBMIT button now that triggers the creation of the SurveyMonkey survey and writes a metadata record to the Googlesheet, so that's good.

I tried to extend the tiny example to read write--just adding a ADD A ROW button and reactive event.  But does not appear to add a row.   Can you  see what's missing?   You need to set up the app like before, running gs_auth locally to get the gs_auth file and then pointing to the desired google sheet key.
[https://github.com/klittle314/googlesheet_shinyapp_readwrite_example.git](url)

thanks again for your insights.

**Comment by MarkEdmondson1234** [comment]
I can take a look later this week, but just checking that you are aware of [Rmonkey](https://github.com/cloudyr/Rmonkey) ? Perhaps that may be a more direct way to do what you are asking.

**Comment by klittle314** [comment]
yes to Rmonkey, that's how we access SurveyMonkey (no direct work with SurveyMonkey API at this point)  Appreciate any light you can shine on the read/write problem.  thx

**Comment by jennybc** [comment]
@klittle314 Have you looked at @daattali's blog post on [persistent data storage in Shiny apps](http://deanattali.com/blog/shiny-persistent-data-storage/)? One of the examples is a Google Sheet so there might be some good example code there. Pardon if I'm off target -- I didn't read the last few messages in detail.

**Comment by klittle314** [comment]
Thank you I have seen this….i looked quickly again, nothing that helps but thanks for the suggestion.  

 

When I try daattali’s app now with the Googlesheets option, the example throws an error!  (maybe I am in good company!

).  

 

I am wrestling with read and write to the googlesheet, hoping that mark may have a thought soon or I may have a breakthrough on my own (though my coding in Shiny is closer to 1000 monkeys producing Hamlet than Shakespeare doing it.)

 

Thanks

 

K

 

Kevin Little, Ph.D.

Informing Ecological Design, LLC

2213 West Lawn Avenue

Madison, WI  53711

tel 608.251.4355  fax 888.247.7543

email klittle@iecodesign.com

 <http://www.iecodesign.com/> http://www.iecodesign.com

**Comment by daattali** [comment]
@klittle314 @jennybc my app indeed does not work with google sheets anymore. Both read and write operations are failing with a `client error: (400) Bad Request` error.   The last time it somebody submitted a response successfully using googlesheets on that app was April 1 (4 days ago).

**Comment by daattali** [comment]
Update: it looks like for some reason `httr` wasn't able to automatically refresh my token. That 400 error was happening when httr tried to auto-refresh a stale token, which worked for several months, but for some reason broke on April 1. After manually creating a new token and verifying authentication via the web, and copying the new oauth token to that shiny app directory, now it works

**Comment by jennybc** [comment]
See the [news for the recent CRAN release](https://cran.r-project.org/web/packages/googlesheets/news.html). I changed the Drive scope (from something ancient to something modern), which means that tokens cached under the old scopes will not be refreshed and will, instead, spawn a new OAuth process.

**Comment by klittle314** [comment]
Hi Dean, thanks for update.    Your blog post from last summer helped convince me to use Google Sheet to read and write our survey metadata.

You say in that blog

"The googlesheets package uses a similar approach to authentication as rdrop2, and thus you also need to authenticate in a similar fashion, such as by copying a valid .httr-oauth file to your Shiny directory."  (http://deanattali.com/blog/shiny-persistent-data-storage/#persistent )

That was in fact how my Shiny app was working in the fall and into early winter.   I just had a valid .httr-oauth file in Shiny directory and then published the wd to shinyapps.io server.   Then things broke a week ago on trying to make edits to the underlying app.

I am stuck generalizing Mark’s suggestion (above) which works for Reading a sheet, I need to read and write (and am down a reactive rabbit hole).

However, your email suggests that you just put a valid .httr-oauth file in your wd and uploaded…..did that work?  Are you running Shiny on a server other than shinyapps.io?

Thanks for any insight you can provide.

**Comment by jennybc** [comment]
@klittle314 Have you remade this `.httr-oauth` file with the new CRAN version of googlesheets? That will be very important. Apologies if I've already said that once in this thread.

**Comment by klittle314** [comment]
Yes, back to version 0.2.0, appears to have no effect--things that worked that last few days with 0.1.0.9001 work with 0.2.0 and things that fail, fail under both.   still trying to fix, thanks for reminder.

**Comment by daattali** [comment]
I generated an oatuh token on my local machine and copied that file to the folder of the shiny app on my shiny server. It's my own shiny server, it's NOT shinyapps.io, though I don't think there should be a difference.  I haven't updated to the new googlesheets yet on my server - it's still using 0.0.0.9001.  Reading and writing indeed both work

**Comment by klittle314** [comment]
Apparently with the current shinyapps.io, the .httr-oauth file is NOT uploaded.   It is not listed in the list of files in the wd when you try to publish.

**Comment by daattali** [comment]
I wouldn't necessarily equate that to meaning it's not uploaded. It's possible, but it's also possible that whatever RStudio is showing is hiding all files beginning with a period.  You should probably clarify with RStudio whether .httr-oauth gets uploaded along with your app or not

**Comment by jennybc** [comment]
If `.httr-oauth` turns out to be the problem, you can find instructions on explicitly writing a token to file, then reading it back in, in the [Managing OAuth Tokens vignette](https://rawgit.com/jennybc/googlesheets/master/vignettes/managing-auth-tokens.html). Then you can pick the file name of your choice.

**Comment by klittle314** [comment]
Thanks Jenny for tip.   That is essentially what MarkEdmondson1234 achieves, we wind up creating a file names gs_auth that is recognized and published to the shinyapps.io server.   Then code can run for at least the tiny example to read a google sheet.   His trick involved setting up a reactive function in server.R (I am stuck trying to get read and write function at this point)....on Dean's point:   yes I am in touch with RStudio folks to see if they have insights.    Thank you both for thinking about my problem I will document when (not if!) there is a solution.

**Comment by MarkEdmondson1234** [comment]
I think I can see the issue in your gist: the `gs_auth` needs to run within each reactive block as they don't share state.  So in your example, add row would be:

```
  add_row <- eventReactive(input$submit, {
    options("googlesheets.httr_oauth_cache" = "gs_auth")
    gskey2 <- "1QhPtrsukBCVZJ-t-nSxCLR1J2OCX-yVReAGVYXIzexM"

    gs_auth()
    gs_add_row(gs_list()[[2]], input = output_sheet_row)
  })
```

You can move the option and gskey2 assignment to the header or a global.R if you like.

**Comment by klittle314** [comment]
Ah yes, of course.   Thank you for your gently worded corection.   I will now try revising the production app following your lead.

**Comment by klittle314** [comment]
Back to simpler solution:   Tareef from RStudio identified the issue as inconsistent behavior of the PUBLISH functionality in the RStudio IDE.   If you use rsconnect::deployApp(), the "old" way will work--that is, if you have a valid .httr-oauth file in the working directory, the deployApp function will load all the bits that you need to run on the shinyapps.io server.    So while MarkEdmondson1234's fix will indeed work (and is necessary if you want to continue using the PUBLISH button in RStudio 0.99.892 or 0.99.893), for those of us with legacy shiny apps, avoid PUBLISH until the bug is fixed.

**Comment by jennybc** [comment]
I suspect my proposal to store the token in a file that does not start with a dot `.` would have also worked? I.e. I imagine that file *would* have been pushed up via the PUBLISH button.

But in any case, how lovely it is to have an answer! Can we close this?

**Comment by klittle314** [comment]
Yes, time to close, I think.   thank you for your suggestions and thanks for the package!
