### ISSUE TITLE
Add "httpuv" to imports

### ISSUE THREAD

**Issue by znmeb** [jennybc/googlesheets#236]
As it stands now, if you do a "gs_new" without the "httpuv" package installed and no stored authentication token, you'll get a message like this:

```
> foo <- gs_new()
httpuv not installed, defaulting to out-of-band authentication
Please point your browser to the following url: 

  https://accounts.google.com/o/oauth2/auth?<long string of stuff you have to copy and paste>

Enter authorization code: 
```

Of course, on my GNOME terminal I can open that via the magic of "xdg-open", etc. But with "httpuv" installed the browser opens up by itself in exactly the right place! So it seems logical to import "httpuv" and eliminate this annoyance.

**Comment by jennybc** [comment]
The current status w/r/t `httpuv` comes from `httr`, which Suggests `httpuv`. I agree it seems logical to install it, but this way the user gets a choice. Upon first encounter of this annoyance, I suspect many will decide to install. But leaving things "as is" leaves `httpuv` as an optional package.

I also make no direct usage of `httpuv`, so I cannot list it under `Imports` w/o triggering a NOTE from `R CMD check`, which I do not want to justify to CRAN.

**Comment by znmeb** [comment]
Ah, well ... I'll find something in `httpuv` to import and load it in my driver code for Google Sheets ;-)
