### ISSUE TITLE
gs_read_csv seems to fail because of an unused argument down the pipeline

### ISSUE THREAD

**Issue by daattali** [jennybc/googlesheets#237]
Perhaps this is already known or maybe I'm doing something wrong, but I noticed I'm not able to read a sheet.

Taken straight from the documentation:

```
gap_ss <- gs_gap()
oceania_csv <- gs_read_csv(gap_ss, ws = "Oceania")
# Accessing worksheet titled "Oceania"
# Error in readr::read_csv(x, readr::locale(encoding = encoding), ...) : 
#   unused argument (na.strings = c("", "NA"))
```

It looks like httr has been running into this issue for at least 3 months: [see here](https://github.com/hadley/httr/blame/7261a525ede1beb9880d1ce2e2009d27c8e8bef7/revdep/summary.md#L579-L590)

**Comment by jennybc** [comment]
This is characteristic of old googlesheets + new httr. Can you install `googlesheets` from CRAN or github and see if problem goes away?

**Comment by daattali** [comment]
Yup. False alarm :alarm_clock:
