### ISSUE TITLE
Incorrect work with cirillyc alphabet

### ISSUE THREAD

**Issue by selesnow** [jennybc/googlesheets#238]
Hello, faced with problem what gs_add_row not supported cirillyc alphabet.

For example, i have data frame which contains cirillyc letters.
<img src="http://img.netpeak.ua/alsey/146004233595_kiss_134kb.jpg" data-canonical-src="http://img.netpeak.ua/alsey/146004233595_kiss_134kb.jpg" style="max-width:100%;">
http://img.netpeak.ua/alsey/146004233595_kiss_134kb.jpg

This data frame name totalData, when i send this data to spreadsheets cirillyc letters load incorrect.
<img src="http://img.netpeak.ua/alsey/146004351712_kiss_96kb.jpg" data-canonical-src="http://img.netpeak.ua/alsey/146004351712_kiss_96kb.jpg" style="max-width:100%;">
http://img.netpeak.ua/alsey/146004233595_kiss_134kb.jpg

http://img.netpeak.ua/alsey/146004351712_kiss_96kb.jpg

Do you can fix this bug?

**Comment by jennybc** [comment]
Do I understand you correctly?

  * You've got a pre-existing Sheet with Cyrillic characters represented correctly. That data was entered in a way that had nothing to do with the `googlesheets` package.
  * You are using `gs_add_rows()` to append new rows and these entries are garbled.

Can you make a small sheet with Cyrillic entries for me in the browser? And **publish it to web** and give me the link so I can read it? I need something to practice with (I can then copy it, in order to write to it).

Can I see the output of `devtools::session_info("googlesheets")`?

**Comment by selesnow** [comment]
@jennybc 
> Do I understand you correctly?

> You've got a pre-existing Sheet with Cyrillic characters represented correctly. That data was entered in a way that had nothing to do with the googlesheets package.

> You are using gs_add_rows() to append new rows and these entries are garbled.

Not certainly in that way, i create data frame in R, and send him to Google Spreadsheets by package googlesheets.

Data frame name "totalData", i try use gs_new with input, and i try gs_add_row, and i get same result in both cases.

`gs <- gs_new(title = "MySpreadsheetNane", ws_title = "kw_qualyti_analisys", row_extent = length(totalData$KeyWord) + 1, col_extent = length(totalData), verbose = F, input = totalData)`

I need create new google spreadsheet documet and past into this spreadsheet data from data frame totalData, which contains cyrillic characters.

> Can you make a small sheet with Cyrillic entries for me in the browser? And publish it to web and give me the link so I can read it? I need something to practice with (I can then copy it, in order to write to it).

Yes, pls go this link, https://docs.google.com/spreadsheets/d/1DvnEaG56QbxMFgqzl9swkzN68bGw35tStjuEi6x5O5Y/edit#gid=0

This spreadsheet contains 2 worksheets:
1) **paste over googlesheets package** - this result i get over use `gs_new(title = "MySpreadsheetNane", ws_title = "kw_qualyti_analisys", row_extent = length(totalData$KeyWord) + 1, col_extent = length(totalData), verbose = F, input = totalData)`

2) **desired result, paste from csv file** - contains result which i need get, this sheet i load from simple csv file which i get by `write.table(totalData,file = paste(gs_title,"_", Sys.Date(), ".csv"), sep = ";", dec = ".", row.names = F)`, and later load into spreadsheet using internal feature "import". You can download this csv file by link https://drive.google.com/file/d/0B1rgddqnM9XJX09oazR6a0Nmcjg/view?usp=sharing

> Can I see the output of devtools::session_info("googlesheets")?

Session info ----------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.2.4 (2016-03-10)
 system   x86_64, mingw32             
 ui       RStudio (0.99.451)          
 language (EN)                        
 collate  Russian_Russia.1251         
 tz       Europe/Helsinki             
 date     2016-04-08                  

Packages ---------------------------------------------------------------------------------------------------------------
 package      * version  date       source        
 assertthat     0.1      2013-12-06 CRAN (R 3.2.4)
 BH             1.60.0-1 2015-12-28 CRAN (R 3.2.3)
 cellranger     1.0.0    2015-06-20 CRAN (R 3.2.4)
 curl           0.9.6    2016-02-17 CRAN (R 3.2.4)
 DBI            0.3.1    2014-09-24 CRAN (R 3.2.4)
 dplyr          0.4.3    2015-09-01 CRAN (R 3.2.4)
 googlesheets * 0.2.0    2016-03-18 CRAN (R 3.2.4)
 httr           1.1.0    2016-01-28 CRAN (R 3.2.4)
 jsonlite       0.9.19   2015-11-28 CRAN (R 3.2.4)
 lazyeval       0.1.10   2015-01-02 CRAN (R 3.2.4)
 magrittr       1.5      2014-11-22 CRAN (R 3.2.1)
 mime           0.4      2015-09-03 CRAN (R 3.2.3)
 openssl        0.9.2    2016-02-26 CRAN (R 3.2.4)
 purrr          0.2.1    2016-02-13 CRAN (R 3.2.4)
 R6             2.1.2    2016-01-26 CRAN (R 3.2.4)
 Rcpp           0.11.6   2015-05-01 CRAN (R 3.2.1)
 readr          0.2.2    2015-10-22 CRAN (R 3.2.4)
 stringi        0.5-5    2015-06-29 CRAN (R 3.2.1)
 stringr        1.0.0    2015-04-30 CRAN (R 3.2.4)
 tidyr          0.4.1    2016-02-05 CRAN (R 3.2.4)
 XML            3.98-1.4 2016-03-01 CRAN (R 3.2.3)
 xml2           0.1.2    2015-09-01 CRAN (R 3.2.4)
>

**Comment by jennybc** [comment]
One quick thing to try if you are willing: install the development version of `xml2` from GitHub:

```
devtools::install_github("hadley/xml2")
```

They did fix one encoding problem because of bug reports from users of `googlesheets` (https://github.com/hadley/xml2/commit/9362d379e126a86091af8698a8987c51b5b230fe). It's possible this will fix your problem too.

**Comment by selesnow** [comment]
Not helped:
<img src="http://img.netpeak.ua/alsey/146011128779_kiss_7kb.jpg" data-canonical-src="http://img.netpeak.ua/alsey/146011128779_kiss_7kb.jpg" style="max-width:100%;">
http://img.netpeak.ua/alsey/146011128779_kiss_7kb.jpg

**Comment by selesnow** [comment]
I get error when i try `devtools::install_github("hadley/xml2")`

> devtools::install_github("hadley/xml2")
Downloading GitHub repo hadley/xml2@master
from URL https://api.github.com/repos/hadley/xml2/zipball/master
Installing xml2
Installing 1 package: Rcpp
package ‘Rcpp’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘Rcpp’
"C:/PROGRA~1/R/R-32~1.4/bin/x64/R" --no-site-file --no-environ --no-save --no-restore CMD INSTALL  \
  "C:/Users/Alsey/AppData/Local/Temp/RtmpmiERzH/devtools224c7cc377e1/hadley-xml2-d00c6a9" --library="C:/Users/Alsey/Documents/R/win-library/3.2" --install-tests 

ERROR: dependency 'Rcpp' is not available for package 'xml2'
* removing 'C:/Users/Alsey/Documents/R/win-library/3.2/xml2'

**Comment by selesnow** [comment]
Hello again.

I found solution, maybe you add him to package's functions.

Before send data frame into spreadsheets we must encod him to UTF8 two times, and then send.

In my case it would be so:

```
totalData <- lapply(totalData, function(x) {iconv(x, to = "UTF8");iconv(x, to = "UTF8")})
totalData <- as.data.frame(totalData)
gs_new(title = "MySpreadsheetNane", ws_title = "kw_qualyti_analisys", row_extent = length(totalData$KeyWord) + 1, col_extent = length(totalData), verbose = F, input = totalData))
```


Thanks.

**Comment by selesnow** [comment]
Function for encoding data frame before send to spreadsheets.

```
beforeSendEnc <- function(dataframe) {
  for(i in 1:length(dataframe)) {
    if(class(dataframe[,i]) %in% c("character","factor")) {
      dataframe[,i] <- lapply(dataframe[,i], function(x) {iconv(x, to = "UTF8");iconv(x, to = "UTF8")})}
  }
  dataframe <- as.data.frame(dataframe)
}
```

**Comment by jennybc** [comment]
@selesnow Thanks for solving your own problem and sharing the solution. Yes I will incorporate it!

Will you try this modified version of `beforeSendEnc` and tell me if it works for you? And can you tell me what the encoding of your text is *before* you encode it as UTF8? Apply `Encoding()` to one of the relevant variables from your data frame. That would help me better understand the situation.

``` r
beforeSendEnc <- function(df) {
  df[] <- lapply(df, function(x) {
    if (is.character(x) || is.factor(x)) {
      iconv(x, to = "UTF8")
    } else {
      x
    }
  })
  df
}
```

**Comment by jennybc** [comment]
For my own future reference, here is a Universal Cyrillic decoder:

http://2cyr.com/decode/?lang=en

**Comment by jennybc** [comment]
BTW back to your attempt to install `xml2` from GitHub. You might want to try `devtools::install_github("hadley/xml2", upgrade_dependencies = FALSE)` (thanks @richfitz). I acknowledge we are longer focusing on that as the primary problem or solution re: your main issue. It would just be nice if you *could* install the development version of `xml2` if you wanted to.

**Comment by selesnow** [comment]
```
beforeSendEnc <- function(df) {
  df[] <- lapply(df, function(x) {
    if (is.character(x) || is.factor(x)) {
      iconv(x, to = "UTF8")
    } else {
      x
    }
  })
  df
}
```

Work correctly

**Comment by jennybc** [comment]
Thanks for testing. It's possible I should just be doing this in general ... Do you consider your problem solved? If so, please close this.

**Comment by selesnow** [comment]
yes, my problem solved, thanks
