### ISSUE TITLE
Conflict (HTTP 409).

### ISSUE THREAD

**Issue by Kinzowa** [jennybc/googlesheets#239]
As of 2022-02-03, the googlesheets package has been archived on CRAN.
I'm closing all issues and pull requests prior to archiving this GitHub repo.

Learn more at:

<https://github.com/jennybc/googlesheets#readme>

**Comment by jennybc** [comment]
Did this only happen once or repeatedly? I have to backoff in `gs_edit_cells()` to give various operations time to complete. If I try to, e.g., resize/trim the sheet too soon after I send the new data, I get a 409 error. I tried to choose a time interval that is a good compromise between "usually works" and "doesn't make things unnecessarily slow". But I'm sure every now and then it's still a problem. If it's an ongoing problem, let me know and I can try a more refined solution. But yes you could use something like `tryCatch()`. I like the error catching functions in `purrr` a lot.

**Comment by HornKild** [comment]
Hi Jenny, it is not 100% clear for me what trigger the error but it is possible I have the same problem you had after editing the worksheet just before.

**Comment by jennybc** [comment]
What I really need to know is if the problem is intermittent or happens very frequently for you. Thanks.

**Comment by HornKild** [comment]
Hi Jenny, the problem is intermittent in my case.
