### ISSUE TITLE
Fail in Quick demo

### ISSUE THREAD

**Issue by agogomei01** [jennybc/googlesheets#240]
Hi all,

I am a newbie in R and googlesheets. I meet an issue and tried to google it but failed. I am wondering if my fundamental understanding is not enough. hope you could give me some guides or hint.

I am practicing Quick Demo after library "googlesheets" and "dplyr".
When I run 
```
gs_gap() %>% 
+     gs_copy(to = "Gapminder")
```
it shows
`Error in req$headers : $ operator is invalid for atomic vectors`

I have no idea how to fix it.
Could you help me on it?

**Comment by jennybc** [comment]
I'm not sure what to tell you. The code above works works for me. I just ran this:

``` r
library(googlesheets)
library(dplyr)
my_gap <- gs_gap() %>% 
   gs_copy(to = "Gapminder")
#>                   Spreadsheet title: Gapminder
#>                 Spreadsheet author: gspreadr
#>  Date of googlesheets registration: 2016-04-25 16:03:21 GMT
#>    Date of last spreadsheet update: 2016-04-25 16:03:18 GMT
#>                         visibility: private
#>                        permissions: rw
#>                            version: new
#>
#> Contains 5 worksheets:
#> (Title): (Nominal worksheet extent as rows x columns)
#> Africa: 625 x 6
#> Americas: 301 x 6
#> Asia: 397 x 6
#> Europe: 361 x 6
#> Oceania: 25 x 6
#>
#> Key: 1uV9PzuGfcnRt9I_VApVZzzmyNCet9rjkAp51tcCIXtg
#> Browser URL:
#> https://docs.google.com/spreadsheets/d/1uV9PzuGfcnRt9I_VApVZzzmyNCet9rjkAp51tcCIXtg/
```

Were there truly no other errors preceding this? Have you tried cleaning out your workspace and restarting R and doing this in a clean session? Since you're copying, you must/should have had to authenticate in the browser. How did that go? Finally, it is possible you somehow have incompatible versions of packages, but it's kind of hard to get into that state. I suspect something simpler is going wrong.

**Comment by claudiocaponera** [comment]
Hi

I am experiencing exactly the same problem. I am pretty sure that it depends on incompatible versions of packages. Any suggestion on how to solve this? 

Many thanks,
Claudio

**Comment by jennybc** [comment]
If that's your intuition, can you post the output of `devtools::session_info()`?

**Comment by claudiocaponera** [comment]
Hi,

'googlesheets' package started to not work anymore after I installed 'httr' from the following link to solve incompatibility with 'bigrquery' - https://cran.r-project.org/src/contrib/Archive/httr/.

It looks like things came back to normality updating 'googlesheets' to version 0.2.0.

Below the current output, after several updates, of devtools::session_info():

package          * version date       source        
 assertthat         0.1     2013-12-06 CRAN (R 3.2.2)
 bigrquery        * 0.2.0   2016-03-03 CRAN (R 3.2.5)
 cellranger         1.0.0   2015-06-20 CRAN (R 3.2.2)
 chron              2.3-47  2015-06-24 CRAN (R 3.2.2)
 colorspace         1.2-6   2015-03-11 CRAN (R 3.2.2)
 data.table       * 1.9.6   2015-09-19 CRAN (R 3.2.5)
 DBI              * 0.4-1   2016-05-08 CRAN (R 3.2.5)
 devtools           1.11.1  2016-04-21 CRAN (R 3.2.5)
 digest             0.6.9   2016-01-08 CRAN (R 3.2.5)
 doBy             * 4.5-15  2016-03-31 CRAN (R 3.2.5)
 dplyr            * 0.4.3   2015-09-01 CRAN (R 3.2.2)
 ggplot2          * 2.1.0   2016-03-01 CRAN (R 3.2.5)
 googlesheets     * 0.2.0   2016-03-18 CRAN (R 3.2.5)
 gridExtra        * 2.2.1   2016-02-29 CRAN (R 3.2.4)
 gsubfn           * 0.6-6   2014-08-27 CRAN (R 3.2.2)
 gtable             0.2.0   2016-02-26 CRAN (R 3.2.5)
 httr             * 1.1.0   2016-01-28 CRAN (R 3.2.5)
 lattice            0.20-33 2015-07-14 CRAN (R 3.2.2)
 lazyeval           0.1.10  2015-01-02 CRAN (R 3.2.2)
 lubridate        * 1.5.6   2016-04-06 CRAN (R 3.2.5)
 magrittr           1.5     2014-11-22 CRAN (R 3.2.2)
 MASS               7.3-43  2015-07-16 CRAN (R 3.2.2)
 Matrix             1.2-2   2015-07-08 CRAN (R 3.2.2)
 memoise            1.0.0   2016-01-29 CRAN (R 3.2.5)
 munsell            0.4.3   2016-02-13 CRAN (R 3.2.5)
 plyr             * 1.8.3   2015-06-12 CRAN (R 3.2.2)
 png              * 0.1-7   2013-12-03 CRAN (R 3.2.3)
 proto            * 0.3-10  2012-12-22 CRAN (R 3.2.2)
 purrr              0.2.1   2016-02-13 CRAN (R 3.2.5)
 R6                 2.1.2   2016-01-26 CRAN (R 3.2.5)
 Rcpp               0.12.4  2016-03-26 CRAN (R 3.2.5)
 reshape2         * 1.4.1   2014-12-06 CRAN (R 3.2.2)
 RGoogleAnalytics * 0.1.1   2014-08-16 CRAN (R 3.2.2)
 RMySQL           * 0.10.9  2016-05-08 CRAN (R 3.2.5)
 rpart            * 4.1-10  2015-06-29 CRAN (R 3.2.3)
 RPostgreSQL      * 0.4-1   2016-05-08 CRAN (R 3.2.5)
 RSQLite          * 1.0.0   2014-10-25 CRAN (R 3.2.2)
 scales           * 0.4.0   2016-02-26 CRAN (R 3.2.5)
 splitstackshape  * 1.4.2   2014-10-23 CRAN (R 3.2.2)
 sqldf            * 0.4-10  2014-11-07 CRAN (R 3.2.2)
 stringi            1.0-1   2015-10-22 CRAN (R 3.2.3)
 stringr          * 1.0.0   2015-04-30 CRAN (R 3.2.2)
 survival         * 2.39-4  2016-05-11 CRAN (R 3.2.2)
 withr              1.0.1   2016-02-04 CRAN (R 3.2.5)
 zoo              * 1.7-13  2016-05-03 CRAN (R 3.2.5)

Thanks,
Claudio

**Comment by jennybc** [comment]
Yes, current `googlesheets` definitely requires `httr (>= 1.1.0)`, as specified in DESCRIPTION:

https://github.com/jennybc/googlesheets/blob/df2fc3c227848878627bb44477162b2337b9ba71/DESCRIPTION#L18

What's going on with `bigrquery` that forced you to downgrade `httr`?

I wonder if this is @agogomei01's problem as well?

**Comment by efh0888** [comment]
It is likely. I had the same issue trying to authenticate using httr version 1.0.0. Also ran into another issue using an older version of xml2. Got it to work with httr version 1.2.1 and xml2 version 1.0.0.
