### ISSUE TITLE
Migrate to Sheets API v4

### ISSUE THREAD

**Issue by jennybc** [jennybc/googlesheets#247]
As of 2022-02-03, the googlesheets package has been archived on CRAN.
I'm closing all issues and pull requests prior to archiving this GitHub repo.

Learn more at:

<https://github.com/jennybc/googlesheets#readme>

**Comment by ReportMort** [comment]
@jennybc Do you have any thoughts about timing and method to the migrate to Sheets API v4? I've done a verbatim transfer of the V4 objects and methods and their documentation from the discovery document (https://sheets.googleapis.com/$discovery/rest?version=v4). It's on branch called `sheets-v4`, so you can install using `devtools::install_github('ReportMort/googlesheets', ref='sheets-v4')`. 

Here is a vignette to demonstrate usage:
https://rawgit.com/reportmort/googlesheets/sheets-v4/vignettes/sheets-v4-usage.html
Specifically, this section demos new sheet formatting functionality:
https://rawgit.com/reportmort/googlesheets/sheets-v4/vignettes/sheets-v4-usage.html#sheet-formatting

The functions are sometimes long and complicated, but I think it would be great to keep them as close as possible to their Google equivalents and then write some wrapper functions around these base components that make it backwards compatible and easier to use. This way the package can be quickly updated to newer API versions by parsing new discovery documents and theoretically expose all the API capabilities through R in case some more esoteric functionality is desired.

**Comment by jennybc** [comment]
@ReportMort This is great! I absolutely want to switch to the new API and am happy to have help!

I am doing an extraordinary amount of teaching this term. Realistically, I can't truly buckle down on this until January, when I am starting a leave from UBC. However, my teaching insanity will ramp down gradually, so I can hopefully give it some thought before then.

I haven't looked at your fork/branch yet but wanted to respond. Something I want to accomplish at the same time as the switch to v4 API is to completely decouple: request formation, API call, response processing. I think this echoes what you say about making it easier to adapt to API changes.

**Comment by ReportMort** [comment]
Thanks for the quick reply. No rush on your part. I just wanted to check that this seemed like a reasonable approach before doing any more. I will take the time to write more documentation and tests. Just let me know when you have any updates on your end.
