### ISSUE TITLE
add googleformr to README

### ISSUE THREAD

**Issue by jennybc** [jennybc/googlesheets#248]
@data-steve I'd like to include [`googleformr`](https://github.com/data-steve/googleformr) as a way to get some interesting data into a Google Sheet. From R itself! At the least, let this be an FYI. But if you'd like to propose a couple of sentences and a link, that would be great too.

In fact, I'm curious: once you make a form and populate it, is there a programmatic way to get identifying info on the associated Sheet? For that matter, is there necessarily an associated Sheet? I feel like this is an option, but you might have to request it.

**Comment by data-steve** [comment]
Hi Jenny,

Great! Thanks for your support. Just to be clear, from the email subject i gather you'd like to include something about googleformr into googlesheets README, right?

On your second point: As soon as I told you in my last email that Google Form makes a sheet attached to a form, I find that Google Forms 2.0 now embeds the results in Form UI. If your forms started under Forms 1.0, they still had a sheet auto generated. Still, under the new system you can make the data reside in a identifiable sheet by taking an extra step. 

Tyler's recent post does a great job of stepping out the process under the new system from creation to data extraction, using googlesheets of course. 👍🏿 Once you follow the steps you'll have a sheet with a key / url etc https://trinkerrstuff.wordpress.com/2016/05/12/googleformr-at-work-pneumatic-road-tube-allegory/.  I'll post about this later myself, but thought I'd give folks a rest. 

Let me know if that helps

Also, I'll get you something re googleformr ASAP. 

~Steve

Sent via telepathy

**Comment by data-steve** [comment]
Hi Jenny,

For your README the first sentence from my README would be most direct. 

> "googleformr is an API to Google Forms, allowing users to POST data securely to Google Forms without needing authentication or permissioning."



For a link, the README itself has been updated to incorporate Tyler’s helpful how-to.  https://github.com/data-steve/googleformr <https://github.com/data-steve/googleformr/blob/master/inst/googleformr_logo.png> If they also want a link to my blog links related to googleformr, here it is: http://data-steve.github.io/tags/#googleformr <http://data-steve.github.io/tags/#googleformr>

In case you’re as obsessive about branding as I am:  The googleformr logo link is here. 
https://github.com/data-steve/googleformr/blob/master/inst/googleformr_logo.png <https://github.com/data-steve/googleformr/blob/master/inst/googleformr_logo.png>

I found this html code helpful in keeping it from using up too much space: 

<div style="float:right; margin:10px;">
 <img src="https://github.com/data-steve/googleformr/blob/master/inst/googleformr_logo.png <https://github.com/data-steve/googleformr/blob/master/inst/googleformr_logo.png>" width="200">
</div>

thanks again!

~Steve

Sent via telepathy
