### ISSUE TITLE
gs_add_col

### ISSUE THREAD

**Issue by kindlychung** [jennybc/googlesheets#250]
As of 2022-02-03, the googlesheets package has been archived on CRAN.
I'm closing all issues and pull requests prior to archiving this GitHub repo.

Learn more at:

<https://github.com/jennybc/googlesheets#readme>

**Comment by jennybc** [comment]
Adding rows is a very privileged operation by the API, in a way that adding a column is not.

Technically you can already do this yourself by checking current dimensions and then using `gs_edit_cells()` and specifying which column to populate.

But yes I can see that it would make sense to have `gs_add_col()` as a companion to `gs_add_row()`, even though what's going on under the hood is quite different. And that function could take care of the dimension checking and column specification.

**Comment by vikash6451** [comment]
Will we ever get gs_add_col? This is quite needed in case I want to insert a column somewhere in the middle of a large table without messing up my entire sheet.

**Comment by jennybc** [comment]
This package will get a reboot, beginning very soon, (it was blocked by doing some Google Drive work, but we've made substantial progress on that https://tidyverse.github.io/googledrive/).

Issues like this will be tackled in the reboot, which wraps the newer [Sheets API v4](https://developers.google.com/sheets/api/reference/rest/).

Here's the guide that looks most relevant:

https://developers.google.com/sheets/api/guides/batchupdate

AFAICT *inserting* a column remains a very unfavourable operation, i.e. we'd have to do it with brute force, but perhaps we could wrap it.
