### ISSUE TITLE
'xml2::xml_find_one' is deprecated.

### ISSUE THREAD

**Issue by Rhoboot** [jennybc/googlesheets#253]
`ss <- googlesheets::gs_key(sheet_key)
`
Sheet successfully identified: 
Warning messages:
1: 'xml2::xml_find_one' is deprecated.
Use 'xml_find_first' instead.

**Comment by jennybc** [comment]
Will you try re-installing `googlesheets` from github? I assume you're running a development version from github? This warning is because of some new developments in `xml2`, which have been accommodated, but perhaps your version of `googlesheets` is slightly behind.

**Comment by jennybc** [comment]
This should be resolved with current CRAN versions of `googlesheets` and `xml2`.
