### ISSUE TITLE
increasing speed using gs functions?

### ISSUE THREAD

**Issue by klittle314** [jennybc/googlesheets#258]
As of 2022-02-03, the googlesheets package has been archived on CRAN.
I'm closing all issues and pull requests prior to archiving this GitHub repo.

Learn more at:

<https://github.com/jennybc/googlesheets#readme>

**Comment by jennybc** [comment]
The API is truly slow. If you are already doing your update in a single call to gs_edit_cells(), I'm not sure how to do any faster.

Is there any way to use `gs_upload()`? Now that might be faster!

Otherwise, I'll take that SO answer into consideration. Thanks for the link. But before I tried to do anything exactly like that, we should see if the new API is somehow snappier. I plan to switch everything over to that in July/August.

https://developers.google.com/sheets/guides/migration

That's the next thing that will trigger re-writing of, say, `gs_edit()`.

**Comment by klittle314** [comment]
Thanks for gs_upload idea.   I will have to play with it to see if I can maintain the same file name on Google Drive.   The new API may help (we can only hope), thank you for your continued development of the package, looking forward to your next iteration.

**Comment by jennybc** [comment]
Keep me posted. I have plans to add more Google Drive stuff. Here or elsewhere.

Do you want to open an issue requesting `gs_replace()`? This looks promising:

https://developers.google.com/drive/v2/reference/files/update

I might be able to wrap something that replaces the guts of the document on Drive but keeps existing filename, URL, etc. I suspect this will always be faster than any approach that uses a cell-aware API, i.e. Google Sheets API, no matter the version.

**Comment by klittle314** [comment]
Yes, gs_replace sounds like a nice function.  Will open an issue.  (BTW I looked last night at writing a custom function that would sort the Google sheet by columns....I got part way through the HTML calls, following your function scripts...given enough hours, I think I could make it work but my skills are primitive, it involves a lot of trying your functions line by line....However if the API interface is slow, that wouldn't buy me better performance.   Will do some timing of gs_edit_cells later today for different size rectangular objects.)

**Comment by jennybc** [comment]
The list feed already has sorting! In theory. Read my help on `gs_read_listfeed()` to see how to invoke. I seem to recall some of the claimed features do not actually work (on the Google side, not mine).

**Comment by klittle314** [comment]
I made a couple of functions to time different size data objects written to Google Sheets in Rmarkdown, zipped and attached.   You may already have this covered but if not might save you 10 minutes in testing any changes next month.   Lesson confirms belief that i need to keep my cell edits
[test_time.zip](https://github.com/jennybc/googlesheets/files/323975/test_time.zip)

 low to keep the response times within reasons, whether or not I write a sheet or just edit cells.

thx again

**Comment by jennybc** [comment]
@klittle314 That is super useful! Thanks for sharing. I'll probably park it in [`internal-projects`](https://github.com/jennybc/googlesheets/tree/master/internal-projects) with my own navel-gazing experiments 😀 unless you object. I think you only sent me the html btw?

**Comment by klittle314** [comment]
Yes, pls use it.   I edited the Rmd file to delete the specific gskey as my test spreadsheet may go away!  See the attached zip with an Rmd file...

**Comment by klittle314** [comment]
here it is
[testPublic.zip](https://github.com/jennybc/googlesheets/files/324162/testPublic.zip)
