### ISSUE TITLE
Encoding issue

### ISSUE THREAD

**Issue by jcdepth** [jennybc/googlesheets#259]
As of 2022-02-03, the googlesheets package has been archived on CRAN.
I'm closing all issues and pull requests prior to archiving this GitHub repo.

Learn more at:

<https://github.com/jennybc/googlesheets#readme>

**Comment by jennybc** [comment]
These are two separate problems, though that is hard to tell.

The first one about `Encoding(targetList)`. Here's a little reprex:

``` r
library(googlesheets)
ss <- gs_gap()
df <- gs_read_csv(ss)
#> Accessing worksheet titled 'Africa'.
#> No encoding supplied: defaulting to UTF-8.
Encoding(head(df$country, 3))
#> [1] "unknown" "unknown" "unknown"
```

Yes indeed the encoding is not set for this vector. Can you elaborate on the downstream problem that this lack of declared encoding causes?

Your colleague's error message actually suggests they are not successfully reading the Sheet. That is really hard for you to know, of course. But at this point, I know that unexpected html (which I see above) almost always means the API is essentially sending a webpage that says "Error". I need to work on displaying such an error better.

But on this front, I suspect you have a sharing/permissions problem. I suspect your colleague doesn't have the necessary permission to read this sheet via the API. Is it a public sheet? Or private but your intent is to give this colleague access? If the latter, exactly how did you grant this permission?

**Comment by jcdepth** [comment]
Thanks for the response! 

Regarding the error message that my colleague got, that makes sense. The document is a private one, and I probably forgot to properly authenticate their Google session.

Interestingly enough, when I reran the `gs_key` function on my computer in a new RStudio session, I got a string of warning messages about various `xml2` methods being deprecated. Is this because I loaded the `xml2` library in my session.

Regarding encoding specifically affecting my workflow, basically I'm using the `twitteR` package right now to grab some tweets for specific Twitter display names, which are stored in the vector I'm creating from the Google Sheet. The issue is that when I retrieve the Tweets, some are in UTF-8, most are `unknown` encoding. This makes them unusable for the `tm_map` package

I was wondering if there was a connection between what I was passing to the Twitter API via `twitteR`, and the encoding issues I'm having. Generally in my current session, I find that even if I create a dummy vector, i.e. `vec <- c["a","b","c"]', the encoding is unknown, and is unchangeable, including using the `iconv` function.

If this is a bit rambly, essentially I'm trying to determine why it seems I'm unable to change any  `unknown` encodings. If this is not typically the case for data obtained through the `googlesheet` functions, then I may have a larger problem.

**Comment by jennybc** [comment]
> Interestingly enough, when I reran the gs_key function on my computer in a new RStudio session, I got a string of warning messages about various xml2 methods being deprecated. Is this because I loaded the xml2 library in my session?

This suggests you loaded a development version of `xml2` but a CRAN version of `googlesheets` (or an older development version). `xml2` is about to update on CRAN and `googlesheets` is ready, but I have to wait for them to go first. Try re-installing `googlesheets` from github to fix this.

I don't know about why you can't change encoding and that seems separate from `googlesheets`. Once you get a data frame with a `gs_read*()` function, it's just a regular data frame.

> Is it possible to supply encoding as an option in the call to the Google Sheet?

Have you tried passing `locale =` to `gs_read_csv()`? I pass that straight through to `readr` for all of my read functions. Encoding is one of the things that can be specified there.

**Comment by jcdepth** [comment]
I can't seem to coerce the data into the encoding I want, whether through the API, or through directly downloaded CSVs, so I'm going to close this issue. Strange, but I don't think this is specific to this package, but maybe with how Google handles encoding for its sheets.

**Comment by jennybc** [comment]
This is not a solution, but an acknowledgement that I don't fully understand all the ways to control Sheet locale. These links might be interesting to you:

https://github.com/jennybc/googlesheets/issues/182

I will try to make progress on this, for your sake and others, but am really busy at a conference this week.
