### ISSUE TITLE
Issue With Shiny OAuth Token

### ISSUE THREAD

**Issue by jcdepth** [jennybc/googlesheets#262]
Hi,

I'm running an AWS instance, with Ubuntu 14.

The relevant authentication code snippet:

`library(googlesheets)`
`sheetKey <- "somekey" #Sharing key of Google Sheet`
`suppressMessages(gs_auth(token = "sheets_token.rds", verbose = FALSE))`
`sheetObject <- gs_key(sheetKey, visibility = "private")`
`dataSheet <- gs_read_csv(sheetObject, col_names=TRUE)`

The output from the console:
`Auto-refreshing stale OAuth token.`
`Warning in gzfile(file, mode) :`
  `cannot open compressed file '.httr-oauth', probable reason 'Permission denied'`
`Warning: Error in gzfile: cannot open the connection`

I've checked the read and write permissions on the token, and that doesn't seem to be the problem. I uploaded the rds file both via FTP, and Git, but it doesn't remove the error.

Restarting the Shiny instance didn't seem to resolve this issue as well.

**Comment by jcdepth** [comment]
I'm not sure if this matters, but looking through some other reported issues, the document in question does belong to a Google Apps for Work account.

**Comment by jennybc** [comment]
Was auth working for this app in the past and the error above is something new?

It's true that Google Apps for Work has presented special difficulties.

But this also sounds like a permissions problem I feared would happen due of a change in `httr`.

https://github.com/hadley/httr/issues/365

What exactly does `ls -l .httr-oauth` show?

**Comment by jcdepth** [comment]
I had not had a fully functioning app up and running before the recent CRAN updates to `XML2` and `googlesheets`, so tough to say.

There's no explicit `.httr-oauth` file in my directory, since on my local machine I saved the token as an RDS file. Is that going to be a problem?

`$ ls -l sheets_token.rds`
gets
`-rwxr-xr-x 1 ubuntu ubuntu 3634 Jun 27 20:04 sheets_token.rds`

**Comment by jennybc** [comment]
I think the explicit token strategy is what you should do. And I now see that in the code at the very top. So I am puzzling over this error, which makes explicit reference to `.httr-oauth`

```
The output from the console:
Auto-refreshing stale OAuth token.
Warning in gzfile(file, mode) :
cannot open compressed file '.httr-oauth', probable reason 'Permission denied'
Warning: Error in gzfile: cannot open the connection
```

On your local machine, please remake the token and make absolutely sure that `cache = FALSE` in the relevant call to `gs_auth()` or make sure the package option `googlesheets.httr_oauth_cache = FALSE`.

See this bit of a vignette:

https://rawgit.com/jennybc/googlesheets/master/vignettes/managing-auth-tokens.html#how-do-i-store-and-retrieve-a-token

**Comment by jcdepth** [comment]
Giving the explicit `cache=FALSE` option to `gs_auth()` solved the issue. Thanks a ton!

On a side note, for some reason R is not recognizing the `gd_token()` function, even with `googlesheets` loaded as a library.

**Comment by jennybc** [comment]
What version of googlesheets do you have? The version with `gd_token()` only went to CRAN this past weekend.

**Comment by jcdepth** [comment]
When I run
`packageVersion("googlesheets")`,

It shows that I have 0.2.1.

A new variant of the authentication issue arose. For some reason when I'm running a `cron` job, I'm getting the token authentication error again in the log.

`> suppressMessages(gs_auth(token = "sheets_token.rds", verbose = FALSE))
Error: Cannot read token from alleged .rds file:
sheets_token.rds
Execution halted`

However, when I'm manually running `Rscript example.R` from command line it works fine.

If I use the workaround of writing a bash shell that executes the R script file, there's no such issue though. (See the answer from Bob on http://stackoverflow.com/questions/12014837/how-to-run-an-r-script-in-crontab).

Is this some kind of permissions issue?

**Comment by jennybc** [comment]
What user will own the process when this is rrun via crontab?

**Comment by jcdepth** [comment]
As of now, just the default `ubuntu` user. Do I need to run it as root?

I've seen various StackOverflow posts stating that running as `sudo` will not work, because a password is needed, which the `cron` job will not be able to provide.

**Comment by jcdepth** [comment]
It seems that for some reason, the method with `cron` scheduling with a bash script is not working anymore as well.

**Comment by jennybc** [comment]
And the rds file that holds the token is also owned by the same user (ubuntu)?

**Comment by jcdepth** [comment]
Looks like it is owned by ubuntu.

`>ls -lh shiny_token.rds`
`-rw-rw-r-- 1 ubuntu ubuntu 3.6K Jun 28 17:47 shiny_token.rds`

**Comment by jcdepth** [comment]
Is there some kind of workflow workaround if I register though the Google Developer Console, so that there's no need to read in a rds token with `gs_auth`?

**Comment by jennybc** [comment]
This package only implements OAuth2 at this time. And given it's nature, i.e. accessing public or user data on behalf of a user, it's not clear that any other approach would be appropriate or possible.

This really should work.

I feel like you might have a working directory / path problem or something similar. Maybe you can rewrite your script to first load the token into an R object via `readRDS()` and then provide that to `gs_auth()`. It would be interesting to know what happens in this case.

**Comment by jennybc** [comment]
From a separate thread on twitter, I gather there may be some problem with CRAN `httr`? For good measure, I suggest you upgrade to the dev version of `httr` from github and see what happens.

There's also some advice about cron jobs in [this thread](https://twitter.com/chipoglesby/status/748189985300348928) (which go back to the working directory issue I raised above).

**Comment by jcdepth** [comment]
Hi,

I think you may be onto something with the permissions issue.

I edited my `.R` file to use `readRDS()`

`> sheetsToken <- readRDS("sheets_token.rds")
> suppressMessages(gs_auth(token = sheetsToken, verbose = FALSE))`

This portion of the code gets:

`Error in gzfile(file, "rb") : cannot open the connection
Calls: readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file 'sheets_token.rds', probable reason 'No such file$
Execution halted`

Is this some kind of permissions issue?

**Comment by jennybc** [comment]
No, I believe the above suggests you've got a file path / working directory issue. We are not even getting to the point of reading the token. The person in the cron thread above? Turned out to have a working directory issue. I suspect that is a problem in your case as well. I propose you drop `getwd()` into your script, just prior to the attempt to read the token, and either write that to file or capture output.

**Comment by jcdepth** [comment]
Hi, so I went ahead and entered `getwd()` as you suggested, and saw that the working directory was indeed not the one where my token was contained. Having `setwd()` explicitly set solved this issue.

I seem to have conflated the location of the cron script with that of the R script.

**Comment by nadeemkhan786** [comment]
OAuth has not been registered for this session
how to solve this in shiny app 
r studio version 3.4.3
