### ISSUE TITLE
gs_auth() issue with offline token

### ISSUE THREAD

**Issue by wma1125** [jennybc/googlesheets#263]
Hi Jenny,

i'm using googlehsheets in R. .there is some issues when I tried to use .rds for authentication without interaction with browser. it seems failed refreshing and I have to use gs_auth() to re-enter my authentication in browser.

gs_auth(token = "ttt.rds", verbose = FALSE)

Auto-refreshing stale OAuth token.
Error in function_list[k] : Unauthorized (HTTP 401).
In addition: Warning message:
Unable to refresh token

**Comment by jennybc** [comment]
Can you explain to me (and perhaps retry, while you're at it) exactly how you created `ttt.rds`? Did you create this with a previous version of googlesheets? In v0.2.0 I updated the scopes, so I suppose a token obtained with an older version would not be refreshable. Also, tokens that go unused for a long time can't be refreshed.

When you first create it and have access to the token, inspect like I do below, so we can figure out if you truly do not have a refresh token.

``` r
library(googlesheets)
## I have an .httr-oauth file fhere
setwd("~/rrr/googlesheets/")
## this loads and refreshes the token in .httr-oauth
gs_auth()
gd_token()
#>          access token: valid
#>  peek at access token: ya29....qTq9g
#> peek at refresh token: 1/goh...Mm6_0
#>                scopes: https://spreadsheets.google.com/feeds
#>                        https://www.googleapis.com/auth/drive
#>      token cache_path: .httr-oauth
``````

**Comment by wma1125** [comment]
thanks. Jenny.. I'm using googlesheets v0.2.1.   here is what I did and what happened.

The script triggered the browser for authentication. 
> setwd("C:/RStudio/workfolder/")
> ttt <- gs_auth()
> saveRDS(ttt, "ttt.rds")
>gd_token()
> gd_token()
         access token: valid
 peek at access token: ya29....hQpug
peek at refresh token: 1/tUk...tU4p8
               scopes: https://spreadsheets.google.com/feeds
                       https://www.googleapis.com/auth/drive
     token cache_path: .httr-oauth



After a while. It is expired

> gd_token()
         access token: expired, will auto-refresh
 peek at access token: ya29....hQpug
peek at refresh token: 1/tUk...tU4p8
               scopes: https://spreadsheets.google.com/feeds
                       https://www.googleapis.com/auth/drive
     token cache_path: .httr-oauth


>gs_auth()  #this trigger browser again

**Comment by wma1125** [comment]
thanks. Jenny.. I'm using googlesheets v0.2.1. here is what I did and what happened.

The script triggered the browser for authentication.

setwd("C:/RStudio/workfolder/")
ttt <- gs_auth()
saveRDS(ttt, "ttt.rds")
gd_token()
gd_token()
access token: valid
peek at access token: ya29....hQpug
peek at refresh token: 1/tUk...tU4p8
scopes: https://spreadsheets.google.com/feeds
https://www.googleapis.com/auth/drive
token cache_path: .httr-oauth
After a while. It is expired

gd_token()
access token: expired, will auto-refresh
peek at access token: ya29....hQpug
peek at refresh token: 1/tUk...tU4p8
scopes: https://spreadsheets.google.com/feeds
https://www.googleapis.com/auth/drive
token cache_path: .httr-oauth
#this trigger browser again

gs_auth()
if I use gs_auth(token="ttt.rds"), it shows

gs_auth(token="ttt.rds")
Auto-refreshing stale OAuth token.
Error in function_list[k] : Unauthorized (HTTP 401).
In addition: Warning message:
Unable to refresh token

**Comment by jennybc** [comment]
So you never experience successful auto-refresh of tokens?

Is there any chance you also have some working directory problems going on here?

Also, what version of `httr` do you have?

**Comment by wma1125** [comment]
my httr is 1.2.1.   I can read and write my working directory.. anything else I need to pay attention?

**Comment by jennybc** [comment]
OK that's the most recent `httr`. So probably not our problem.

I know it seems unlikely, but it's pretty easy to obtain and store a token in one directory. Then when your script or Shiny app or whatever runs, working directory is such that the token can't be found or a different (older) token is being found. A surprising number of problems boil down to exactly this.

Therefore I am wondering if somehow the `ttt.rds` you have newly created and examined above is not the one that's being loaded and, ideally, refreshed, at runtime.

Do you want to tell me more about what exactly you are trying to do? Are you using Google Apps for Work or is there anything else unusual about your situation? Are you perhaps using your own client id and secret?

**Comment by wma1125** [comment]
i'm using it for work.. Is it possible to use client id and secret as a alternative way?

**Comment by jennybc** [comment]
I bundle a client id and secret in the package for anyone to use. But it is possible to get your own and, indeed, if you use `googlesheets` a lot, you should. Hence I am asked about whether you set up your own id and secret.

Auth is an additional process and still necessary regardless. But when I google about your problems -- the 401 error and lack of refresh -- many of the hits were about people having improper id and secret or not enabling the right APIs for app access.

I've never seen this problem before and I suspect it's fixable. You've given me some detail, but I'd still benefit from an actual R script, with `getwd()` and `gd_token()` calls sprinkled in, that shows an exact sequence of your actions that produce an unsuccessful token refresh.

**Comment by wma1125** [comment]
Hi Jenny, thanks so much for your time.. below is my script

library("googlesheets") 
library("openssl")
library("jsonlite")
library("curl")
library("xml2")
library("httr")
library("XML")
library("assertthat")

setwd("C:/RStudio/workfolder/")
getwd()
gs_auth(toke="ttt.rds")
gd_token()

##read file
mygs<-gs_title("mygs")

**Comment by jennybc** [comment]
I'm still concerned that you're not loading a freshly made token. I see you explicitly setting working directory. My spidey sense is that either there is no `ttt.rds` token file in `C:/RStudio/workfolder/` (was working directory set to this dir at the time of token creation and storage?) or the token in this file is not refreshable because

  * it is an old one from a previous version of `googlesheets` or ...
  * it has fallen off the end of your 25 token limit and can no longer be refreshed to get new access tokens (you can only have 25 valid refresh tokens)

I suggest you write and run two scripts:

  * One for token creation, which you'd run interactively. It would load `googlesheets` and do `ttt <- gs_auth()`, with you going to the browser to make 100% we have a brand new refresh token. Then write `ttt` to a file with a name that is specific to NOW, e.g., `2016-07-11-token.rds`.
  * One for token usage. It would basically be the script above, but with `ttt.rds` replaced by `2016-07-11-token.rds`.

This exercise would really narrow the problems down.

**Comment by wma1125** [comment]
Yes, I wrote a script and save the "token-7-11.rds"

then run the my old script below. it is connected(for now)
gs_auth(toke="token-7-11.rds")
gd_token()
         access token: valid
 peek at access token: ya29....vLnWA
peek at refresh token: 1/oys...MW9f8
               scopes: https://spreadsheets.google.com/feeds
                       https://www.googleapis.com/auth/drive
     token cache_path: .httr-oauth

**Comment by wma1125** [comment]
it is not work again.. with "token-7-11.rds".  one thing that I found is that the access token and refresh token are change from time to time.. is it normal?

**Comment by wma1125** [comment]
Hi Jenny, Finally I fixed the issue. It it because I use two folders for library. I called both when I run the googlesheets. There might be some conflict between the libraries from the locations.. When I put all the packages into my default library folder. there is no issue.. Thanks a lot for your help..
