### ISSUE TITLE
R 3.0.2 not available

### ISSUE THREAD

**Issue by songyurita** [jennybc/googlesheets#266]
As of 2022-02-03, the googlesheets package has been archived on CRAN.
I'm closing all issues and pull requests prior to archiving this GitHub repo.

Learn more at:

<https://github.com/jennybc/googlesheets#readme>

**Comment by jennybc** [comment]
Officially, it requires R (>= 3.2.0). I can't guarantee exactly what the true minimum is. But I doubt that I'd even be able to take it back to 3.0.2 if I tried, because there are a lot of dependencies with their own constraints.
