### ISSUE TITLE
Error: Cannot download Google spreadsheet as this format:

### ISSUE THREAD

**Issue by asaumya** [jennybc/googlesheets#270]
Hi,
I am using googlesheets for last 2 months to download file on local. It was working fine till yesterday, but today I am getting error message.
Code:
gs_title("Master SKU") %>%
      gs_download(to = "C:/Users/Saumya/Desktop/Work/AdHoc/")

Console:
Sheet successfully identified: "Master SKU"
Error: Cannot download Google spreadsheet as this format: 

The sheets haven't been changed, so not sure what the issue is. Any suggestions?

**Comment by asaumya** [comment]
Got the error. Closing the issue. I was not providing .csv extension in "to"

**Comment by jennybc** [comment]
👍 glad you sorted it out
