### ISSUE TITLE
runtime error after update - R session closes

### ISSUE THREAD

**Issue by vicama** [jennybc/googlesheets#271]
As of 2022-02-03, the googlesheets package has been archived on CRAN.
I'm closing all issues and pull requests prior to archiving this GitHub repo.

Learn more at:

<https://github.com/jennybc/googlesheets#readme>

**Comment by vicama** [comment]
Add more information about my problem.

I have run in debugger mode and I have seen that the problem occurs in the gs_lookup function when the next line is running:

"_.getNamespace(c("xml2", "1.0.0"), "class")_"

A loop ( see attached log ) occurs when the library is evaluated xml2 and R session ends with error.

Can anybody help me?

[R_log.txt](https://github.com/jennybc/googlesheets/files/439476/R_log.txt)

**Comment by jennybc** [comment]
@jimhester I haven't scrutinized this log but does it immediately tell you anything? It's a googlesheets error (never heard of it before) that nominally has something to do with `xml2` but who knows?

**Comment by jimhester** [comment]
The error looks like it's occurs when trying to load the xml2 namespace.
This suggests to me @vicama's library has been corrupted. I would try
removing the googlesheets and xml2 libraries and reinstalling them. Then
trying again in a new R session.

**Comment by vicama** [comment]
@jimhester, @jennybc  it's very strange. I have removed all libraries , installation of R and R Studio. I deleted user data, I installed all the software again , I created new project and the error persists :(

**Comment by AJPSport** [comment]
I had this issue, switched from 32 bit to 64 bit and it worked fine.
