### ISSUE TITLE
Can't Write to Column "RC" using A1 Style in anchor argument

### ISSUE THREAD

**Issue by StevenMMortimer** [jennybc/googlesheets#275]
As of 2022-02-03, the googlesheets package has been archived on CRAN.
I'm closing all issues and pull requests prior to archiving this GitHub repo.

Learn more at:

<https://github.com/jennybc/googlesheets#readme>

**Comment by jennybc** [comment]
The most recent release of `cellranger` (which `googlesheets` relies on) got much smarter and more careful about this exact issue. But `googlesheets` isn't using any of that smarts yet. How much of a problem is this for you right now?

**Comment by ReportMort** [comment]
This is not a problem, I just wanted to note something that I observed. 

I have daily spreadsheet tasks scheduled via cron and got a notification that when my script failed to write in column "RC" using "A1" style. As workaround I just wrote the data into column "RD", then copy pasted into "RC", and let the script continue on it's merry way after that.

Thanks for reaching out. Really appreciate the effort to maintain the package, which I'm sure could be one full-time job.

**Comment by jennybc** [comment]
So you really need to write specifically into the cell "RC". What are the chances? I mean if you could right into a cell range that spanned it, this would not come up.

**Comment by ReportMort** [comment]
Yep, anything where the anchor starts in "RC".

**Comment by ReportMort** [comment]
I don't advocate supporting processes that write data all the way into column "RC" in a random google sheet, but sometimes you just get stuck with this sort of stuff. :frowning:
