### ISSUE TITLE
Reading .csv files from a specific google drive folder example

### ISSUE THREAD

**Issue by sv1478** [jennybc/googlesheets#277]
As of 2022-02-03, the googlesheets package has been archived on CRAN.
I'm closing all issues and pull requests prior to archiving this GitHub repo.

Learn more at:

<https://github.com/jennybc/googlesheets#readme>

**Comment by jennybc** [comment]
No, googlesheets can't currently read from csv files on Drive. It can read from Sheets on Drive and it can download them as csv. Or upload csv into Sheets. But not what you want 😢.

So you want to do what ... turn csv's into Sheets? Or just download csv files from Drive to your local machine?
