### ISSUE TITLE
unable read only active cells

### ISSUE THREAD

**Issue by prasoonsrivas** [jennybc/googlesheets#278]
As of 2022-02-03, the googlesheets package has been archived on CRAN.
I'm closing all issues and pull requests prior to archiving this GitHub repo.

Learn more at:

<https://github.com/jennybc/googlesheets#readme>

**Comment by jennybc** [comment]
No the package currently has no way to automatically determine this. I'm not even sure the Sheets API supports a notion of "active cells".

In any case, with this package, you'd have to read the sheet in its entirety and, on the R side, figure out which cells are populated.

Is the data rectangle always in the upper left corner? Or is it migrating around quite freely? If the data lives in the upper left rectangle, it seems like reading from the sheet should "just work". But perhaps you have already seen a problem?
