### ISSUE TITLE
Problems handling hyphens in key names?

### ISSUE THREAD

**Issue by trevormartin** [jennybc/googlesheets#280]
I have created a new google sheet that happens to have a hyphen in its name and running the following code gives the following error (it is a public spreadsheet so no authentication required): 

```
> test = gs_key("12lT1v1GC6pwl-RfQaQ5kzZ707L8Zcw6ojT2o6MuMDYs")
Error in stop_for_content_type(req, expected = "application/atom+xml; charset=UTF-8") : 
  Expected content-type:
application/atom+xml; charset=UTF-8
Actual content-type:
text/html; charset=UTF-8
```

I have tried this exact gs_key call with other (public) keys with no problem - but all of them lack the hyphen so I'm thinking that may be the issue? Unless I'm missing something obvious. 

Thanks! 

**An update:** 

This google sheet created by someone else has hyphens and works correctly, so I'm not sure what's going on: 

```
> gs_key("1mW9r6ztHCVI8yLCgGL6iFeHlW-tmnB6Vg29yKL-tys4")
Worksheets feed constructed with public visibility
                  Spreadsheet title: Example
                 Spreadsheet author: andrewheiss
  Date of googlesheets registration: 2016-11-28 02:24:51 GMT
    Date of last spreadsheet update: 2016-03-01 15:22:48 GMT
                         visibility: public
                        permissions: rw
                            version: new

Contains 1 worksheets:
(Title): (Nominal worksheet extent as rows x columns)
Sheet1: 1000 x 26

Key: 1mW9r6ztHCVI8yLCgGL6iFeHlW-tmnB6Vg29yKL-tys4
Browser URL: https://docs.google.com/spreadsheets/d/1mW9r6ztHCVI8yLCgGL6iFeHlW-tmnB6Vg29yKL-tys4/
```

**Comment by trevormartin** [comment]
I think I've worked through this myself now, sorry for the misleading issue - basically in addition to updating the spreadsheet as viewable/editable to anyone on the web using the top right "share" button in google sheets you also need to publish the worksheet to the web in order for gs_key to work. Perhaps the error could be adjusted to be more informative to help new users?

**Comment by jennybc** [comment]
> Perhaps the error could be adjusted to be more informative to help new users?

Yes you are exactly right 😁 I will do this on my next sweep, which is on the horizon.

https://github.com/jennybc/googlesheets/issues/163
