### ISSUE TITLE
Best way to update a large sheet with new data?

### ISSUE THREAD

**Issue by ashleylester** [jennybc/googlesheets#282]
Hey Jenny

What's the best way to wipe the data in a Google Sheet and replace it with new data? The data is too big for me to upload it so I've been batch-uploading through gs_edit_cells but I'm running into API errors (409 mostly).

The reason I can't gs_upload as a new worksheet is because the sheet is hooked into Tableau, and to keep the automation I can't change anything about the worksheet like its key and so on.

**Comment by jennybc** [comment]
Can you slow your requests down by putting `Sys.sleep()` inside whatever is doing the iteration? There are even a couple of instance of this inside googlesheets itself. Sometimes you have to give the Sheets back end time to digest a change before trying the next. I know it's sad to make things even slower, but this faster than failing due to error!

I recently saw a new package go by (maybe on CRAN or maybe just on Twitter) that seemed to have nicer facilities than `Sys.sleep()` for this sort of thing. Will try to think of it.

**Comment by jennybc** [comment]
It's this naptime package:

https://github.com/drknexus/naptime

**Comment by jennybc** [comment]
I could also try to catch this and retry. I have retries built in for some other specific errors and could consider expanding to this ... will leave this open.

**Comment by ashleylester** [comment]
Thanks! Well I used the try-catch code posted on the other thread about the HTTP 500 error, but after 10 retries, it still resulted in a 409. It's only around 10,000 lines.

What I think I'm going to do is use gs_upload and then alter its id through the Google Drive API and the httr package. Using gs_upload takes about 2 seconds, it's just that Tableau doesn't see it as the same file.

**Comment by jennybc** [comment]
If you're willing to test, it would be interesting to know if file size has anything to do with it, really. As in, does the delay needed seem to scale with the number of lines you're sending? And is there some back off at which you are successful? I.e. if the minimum delay is x seconds?

When I work on this next I will see if `gs_upload()` can somehow write into (overwrite) an existing Sheet, i.e. do something along the lines you are proposing. Let me know if it works!

**Comment by omgjens** [comment]
You can pull this feature from https://github.com/jennybc/googlesheets/pull/285. It will add an overwrite argument to gs_upload() like jennybc proposed

**Comment by ashleylester** [comment]
Nice! I'll test it asap.

**Comment by jennybc** [comment]
The `overwrite` feature described and contributed by @omgjens is now merged in. Does this solve your problem @ashleylester?

**Comment by ashleylester** [comment]
Hey @jennybc I'm branching a project today to test this. Will let you know.

Really enjoyed watching your talk at Plotcon on YouTube by the way. :)

**Comment by ashleylester** [comment]
Mmmmmmm this seems to work very nicely! Thanks to you both @omgjens @jennybc you've saved me a few hours on Monday mornings copying and pasting.

👍

**Comment by jennybc** [comment]
Great!
