### ISSUE TITLE
automagically gitignore .httr-oauth token 

### ISSUE THREAD

**Issue by maxheld83** [jennybc/googlesheets#283]
following up on #165 and to protect against really newbie users, might it be possible to automatically append the `.gitignore` with `.httr-oauth`, just to be extra, extra safe?

**Comment by jennybc** [comment]
Yes this has been on my mind. Thanks for opening a concrete issue.

**Comment by jennybc** [comment]
httr actually does this:

https://github.com/hadley/httr/search?utf8=✓&q=gitignore&type=

Is this a suggestion on principle or do you know of a googlesheets workflow that somehow circumvents this and needs to be accounted for here?

**Comment by maxheld83** [comment]
uh ok, sorry I missed that.
Unfortunately, I do not remember the steps that lead to this situation.
It's possible, that `httr` actually did it's job, and *I*, in some haze of confusion, actually discarded the patched `.gitignore`, thereby shooting myself in the foot.

So, I guess this can be closed since a protection *is* already in place.

I'll reopen should I ever encounter such a googlesheets workflow, but I am guessing that this was then just my stupidity.

Thanks for following up on this.

**Comment by jennybc** [comment]
@mine-cetinkaya-rundel I feel like we've discussed this recently to. Can you add anything?

**Comment by mine-cetinkaya-rundel** [comment]
Yes, I made this mistake recently as well. I was following the steps for getting started with `googlesheets` on the README.

1. It would be nice to add a concrete step to the repo README to remind users to add .httr-oauth to their .gitignore file. I realize not all users of the package will be committing their code to a repo, but it's still worth mentioning in the quick demo (or right before). (I can do a PR for this too.)
    - Note: This is mentioned in the Managing OAuth tokens document linked from the README but I assume many might not click on that initially and just move on to the quick demo.

2. Add .httr-oauth to the .gitignore when the package is in use. Is this feasible to do based on loaded packages in the environment/project?

**Comment by jennybc** [comment]
But my point is that `.httr-oauth` will be automatically added to `.gitignore`. So what are people doing to somehow circumvent this helpful thing? I feel like I'm missing something in the workflow.

**Comment by mine-cetinkaya-rundel** [comment]
Reading over the thread again, I think you're saying that `.httr-oauth` is already automatically added to `.gitignore`. This somehow didn't happen for me.

I just tried to create a new repo, clone it via an RStudio project, load googlesheets, and read a Google sheet that then generated the `.httr-oauth` file. So far it has not been added to the `.gitignore`. It would be at this stage that one might accidentally commit the file if they do something like committing all changed files at once.

**Comment by jennybc** [comment]
It *should* be added by httr, according to its docs and source. So perhaps I need to check that again and follow up on that! What version of httr do you have?

**Comment by mine-cetinkaya-rundel** [comment]
I have httr_1.2.1.

**Comment by jennybc** [comment]
Well, yeah, I just proved to myself that merely creating `.httr-oauth` does not add it to gitignore, so I will follow up on that.

**Comment by jennybc** [comment]
I've made a PR to fix this generally in httr:

https://github.com/hadley/httr/pull/437

**Comment by jennybc** [comment]
The PR to httr has now been merged. Until that is part of a CRAN release, the remedy is to install httr from GitHub.

It is possible that googlesheets should still address this in the interim. Therefore, leaving this open.

**Comment by nadeemkhan786** [comment]
hii mam. my name is khan i getting error when i run my code . Can u please help to solve this error
error
Adding .httr-oauth to .gitignore
Error in check_twitter_oauth() : OAuth authentication error:
This most likely means that you have incorrectly called setup_twitter_oauth()'
> 
what is the steps to solve this kind of error
