### ISSUE TITLE
Authentication without browser

### ISSUE THREAD

**Issue by kanatti** [jennybc/googlesheets#287]
As of 2022-02-03, the googlesheets package has been archived on CRAN.
I'm closing all issues and pull requests prior to archiving this GitHub repo.

Learn more at:

<https://github.com/jennybc/googlesheets#readme>

**Comment by jennybc** [comment]
You will need to do this process **once** on a machine where you do have a browser and save a token. Then move that token to the server. This is covered in the "Managing OAuth Tokens" vignette, which ships with the package, or you can view here:

https://rawgit.com/jennybc/googlesheets/master/vignettes/managing-auth-tokens.html

**Comment by claudiocaponera** [comment]
I have the same problem - Waiting for authentication in browser...

**Comment by claudiocaponera** [comment]
Sorted - it works when not on the VPN.
