### ISSUE TITLE
Setting up new authentication using key and secret

### ISSUE THREAD

**Issue by efh0888** [jennybc/googlesheets#288]
Does this feature work?  I'm getting an HTTP 403 error but have verified the associated Project has the Google Sheets API enabled.  Is there another API that I need to enable first?  I also know the client ID and secret are correct as the app name displayed on the consent screen is the same.

Here's the full error:
`Error in function_list[[k]](value) : Forbidden (HTTP 403).`

**Comment by jennybc** [comment]
Could you provide a more complete picture of what you've done? Just so we can jointly determine if you've skipped a step or if some step is not recorded. I believe others have done this.

**Comment by efh0888** [comment]
Sure.

1. Created a new project in the Google developers console.  Enabled the Google Sheets API.  Grabbed the client ID and secret.
2. Ran the following and on the consent screen made sure I was logged in as the user who owns the project.
```
newAuth <- gs_auth(new_user = TRUE, cache = FALSE,
                    key = "295835262045-hah64g9miut109pfhs5p73emgf2a8jgu.apps.googleusercontent.com",
                    secret = "J_qZRYf1dvLVSzoa2mOoHdgS")
```

**Comment by davidpitkin** [comment]
I had the same problem, I also rolled my own google API credentials since I was planning to use this for work. I was able to login, and gs_ls() but gs_new() gave a 403.

```
> gs_ls()
# A tibble: 110 × 10
                sheet_title        author  perm version             updated sheet_key
                      <chr>         <chr> <chr>   <chr>              <dttm>     <chr>
1  HIDDEN    rw     old 2017-02-04 19:15:22 1ZZU20ez…
2  HIDDEN    rw     old 2017-02-04 01:23:00 1gvFkzXA…
3  HIDDEN    rw     old 2017-02-03 23:52:31 1atPovSx…
4  HIDDEN    rw     old 2017-02-03 18:54:03 1hVn1ZlE…
5  HIDDEN    rw     old 2017-02-03 17:25:43 1qckwkeo…
6  HIDDEN    rw     old 2017-02-03 14:58:26 1CBkH0b1…
7  HIDDEN    r     old 2017-02-02 21:22:22 1VTFG-wa…
8  HIDDEN   r     old 2017-02-02 19:27:16 14dZe8C5…
9  HIDDEN    rw     old 2017-02-02 18:56:41 15Z7z5Q3…
10 HIDDEN   rw     old 2017-02-02 12:13:35 1EycRfpM…
# ... with 100 more rows, and 4 more variables: ws_feed <chr>, alternate <chr>, self <chr>, alt_key <chr>

> boring_ss <- gs_new("boring", ws_title = "iris-gs_new", input = head(iris),
...                     trim = TRUE, verbose = FALSE)
Error in function_list[[k]](value) : Forbidden (HTTP 403).
```

**Comment by davidpitkin** [comment]
I have a suspicion that my problem is the same as @cmedinag in this comment, my Google Domain has the spreadsheet API available but not the drive API. That would also explain why I am unable to use gs_upload() with the same 403 error.

https://github.com/jennybc/googlesheets/issues/219#issuecomment-203449218

**Comment by jennybc** [comment]
Thanks @davidpitkin, I just read the thread you linked to. It's sort of buried at the end of a totally unrelated topic 😔. Would you open a new issue where the name is clearly about ... domains that don't grant permissions to use the Drive API? Unless, @efh0888: are you also dealing with a Google Apps for business domain? In which case you or I can edit the title of this thread to reflect the real problem.

This is hard to fix because `gs_ls()` is used in a lot of places. But there is a major refactor planned and I could work on this then, i.e. determining how much can be done w/o any calls to the Drive API.

**Comment by davidpitkin** [comment]
@jennybc I think you are right about the other topic as a distraction. I logged out of my corporate drive account via googlesheets and into my personal account and got the same 403 Error when doing the simple task here.

gs_gap() %>% 
...   gs_copy(to = "Gapminder")
Error in function_list[[k]](value) : Forbidden (HTTP 403).
> 

I continue to believe now this is related to me using my own Google API key, how can I get more debugging information? gs_ls() works and so does most commands, but upload csv fails and even when I do a gs_auth() after returning from the browser I see that same 403 error.

> gs_auth()
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Authentication complete.
Error in function_list[[k]](value) : Forbidden (HTTP 403).
>

**Comment by jennybc** [comment]
>  I logged out of my corporate drive account via googlesheets and into my personal account and got the same 403 Error when doing the simple task here.

How sure are you that a cached token was not being used? I.e. how sure this is a true test of using the main Google domain and your personal account?

I'm going to look at how I set up the app credentials baked into the package... and take a screenshot or something, for us to compare.

**Comment by jennybc** [comment]
If I'm interpreting the API Manager correctly, the credentials I have baked into the googlesheets package are only explicitly associated with Google Drive. Not with Sheets. 🤔

**Comment by jennybc** [comment]
@craigcitro Does this make any sense to you? Is it plausible that a client id and secret for the Drive API also confer the ability to make requests on the Sheets API? But, as I believe we are seeing above, not the other way around?

**Comment by craigcitro** [comment]
So I think it would be instructive to print the error we're getting with the 403 here. (Sadly, a 403 can be from many causes.) Can we run this all with `httr::with_verbose`?

I suspect that the full error message says either "The Drive API has not been activated for this project", or something about an invalid client ID. But that's going to be our fastest route to new info.

(Also, just to confirm -- we're mentioning "api key" here, but no one is actually using an API key, right? Just a client ID/client secret pair?)

**Comment by jennybc** [comment]
> (Also, just to confirm -- we're mentioning "api key" here, but no one is actually using an API key, right? Just a client ID/client secret pair?)

Correct.

> So I think it would be instructive to print the error we're getting with the 403 here. (Sadly, a 403 can be from many causes.) Can we run this all with httr::with_verbose?

OK I might have to prepare a branch for that. I doubt a user can insert the necessary request for verbosity from httr.

**Comment by jennybc** [comment]
OMG that just works though:

``` r
httr::with_verbose(googlesheets::gs_ls())
```

Hopefully some of the sufferers above can drop their problematic commands in there and provide more info.

**Comment by davidpitkin** [comment]
I figured it out, I needed to enable the Drive API in my Google API Dashboard

https://console.developers.google.com/apis/api/drive/overview?project=third-being-157719&duration=PT1H

<img width="347" alt="api_manager_-_dpitkin_googlesheets" src="https://cloud.githubusercontent.com/assets/18124/22799442/c6f4e69e-eed3-11e6-883f-61a0f02fca9a.png">

Here is my output from httr::with_verbose(googlesheets::gs_upload("upgrade_planning.csv", sheet_title="foo", verbose = TRUE)), this is using my Google API credentials and secret against my corporate account or my personal one. 

POST /drive/v2/files HTTP/1.1
-> Host: www.googleapis.com
-> User-Agent: libcurl/7.43.0 r-curl/2.3 httr/1.2.1
-> Accept-Encoding: gzip, deflate
-> Accept: application/json, text/xml, application/xml, */*
-> Content-Type: application/json
-> Authorization: Bearer HIDDEN
-> Content-Length: 68
-> 
>> {"title":"foo","mimeType":"application/vnd.google-apps.spreadsheet"}

<- HTTP/1.1 403 Forbidden
<- Vary: Origin
<- Vary: X-Origin
<- Content-Type: application/json; charset=UTF-8
<- Content-Encoding: gzip
<- Date: Thu, 09 Feb 2017 18:22:01 GMT
<- Expires: Thu, 09 Feb 2017 18:22:01 GMT
<- Cache-Control: private, max-age=0
<- X-Content-Type-Options: nosniff
<- X-Frame-Options: SAMEORIGIN
<- X-XSS-Protection: 1; mode=block
<- Server: GSE
<- Alt-Svc: quic=":443"; ma=2592000; v="35,34"
<- Transfer-Encoding: chunked
<- 
Error in function_list[[k]](value) : Forbidden (HTTP 403).

**Comment by jennybc** [comment]
> Anyway, so is the problem simply that the Drive API must be enabled, not just the Sheets API?

That's the current theory, yes.

**Comment by dsdaveh** [comment]
I was having the same problem, and enabling the Drive API fixed it for me as @davidpitkin suggested.

**Comment by jennybc** [comment]
Yes. I believe Drive API scope will give access to Sheets.

**Comment by tarunparmar** [comment]
We faced the same error with Drive API being already enabled, eventually found out that the colleague had Protected Range which allowed to edit only to himself. Resolved by allowing others to edit in the Protected Range feature.
