### ISSUE TITLE
Read all worksheets in a single request?

### ISSUE THREAD

**Issue by mbojan** [jennybc/googlesheets#289]
Is it possible to read all worksheets from a spreadsheet in a single request?

I have made some spreadsheets with multiple worksheets and now they are cumbersome to read because of the API rate limits :(

**Comment by mbojan** [comment]
OK, I found `gs_download`... :)
Apologies for a hasty issue.
thx

**Comment by jennybc** [comment]
Is `gs_download()` what you wanted or did you ... want to read all worksheets into a list of data frames or something like that?

**Comment by mbojan** [comment]
Yes exactly, a list of data frames. So far it I am managing with `gs_download()` although it seems that importing the worksheets from downloaded XLSX (with XLConnect) gives different results from those I was getting with googlesheets (I'm getting some empty cells).

Being able to get such list of data frames in a single request with googlesheets would be great. Is that possible with the API?

**Comment by jennybc** [comment]
I could make it feel like a single request, but no I don't think the API itself supports that. I think you are always getting the data for, at most, one worksheet at the time. So if rate limit is a problem, perhaps downloading to a local xlsx is a good idea.

Have you tried reading the downloaded xlsx with readxl? I have more interest and influence in making those two packages (googlesheets and readxl) as consistent as possible.

**Comment by mbojan** [comment]
Sure, looping with some `Sys.sleep` is doable, but it is cumbersome.

I use XLConnect because I can define the range upfront. It is easier than reading with readxl and then trim down uneccessary columns or rows (again, empty cells).

**Comment by jennybc** [comment]
Yes, I get it. That will be the next issue I tackle on readxl (https://github.com/hadley/readxl/issues/8).

**Comment by mbojan** [comment]
Great! No more fancy Java dependencies... :)
