### ISSUE TITLE
gs_edit_cells able to export NA as blank cell rather than 'NA'

### ISSUE THREAD

**Issue by m-macaskill** [jennybc/googlesheets#291]
As of 2022-02-03, the googlesheets package has been archived on CRAN.
I'm closing all issues and pull requests prior to archiving this GitHub repo.

Learn more at:

<https://github.com/jennybc/googlesheets#readme>

**Comment by prasoonsrivas** [comment]
gs_edit_cells( ) is no longer is working.

**Comment by jennybc** [comment]
@m-macaskill Good idea.
