### ISSUE TITLE
How to prevent message "No encoding supplied: defaulting to UTF-8."

### ISSUE THREAD

**Issue by ghost** [jennybc/googlesheets#294]
As of 2022-02-03, the googlesheets package has been archived on CRAN.
I'm closing all issues and pull requests prior to archiving this GitHub repo.

Learn more at:

<https://github.com/jennybc/googlesheets#readme>

**Comment by jennybc** [comment]
What version of httr do you have installed? This message originates there and I have some recollection that updating httr might suppress it.

Of course you can always place your requests inside `suppressMessages()` but I realize that is not always attractive.

**Comment by cowlumbus** [comment]
I'am using the latest version of R (3.3.2), Rstudio (1.0.136), and httr (1.2.1). Thank you.

**Comment by cowlumbus** [comment]
@jennybc 
Any attractive solutions?

**Comment by jennybc** [comment]
I just a small change and travis isn't even done checking it yet. Perhaps that will go a long way towards suppressing the message. Maybe try installing the dev version now?

**Comment by jennybc** [comment]
This is definitely not fixed yet for `gs_read()` 😞.

**Comment by cowlumbus** [comment]
Thank you Jenny!
