### ISSUE TITLE
Error in registering a google sheet via R 

### ISSUE THREAD

**Issue by sagar356020** [jennybc/googlesheets#297]
Hey there,

When I am trying to use the below code:``MBS<-gs_key("1HbPQokFvM4AhXh4Ux75M470M5JFuaL5_6E6L575-iJ4",lookup=NULL,visibility=NULL,verbose=TRUE)

It throws the below error:
Worksheets feed constructed with public visibility
Error in stop_for_content_type(req, expected = "application/atom+xml; charset=UTF-8") : 
  Expected content-type:
application/atom+xml; charset=UTF-8
Actual content-type:
text/html; charset=UTF-8

Can you please let me know the bug or issue here?
I have published the googlesheet and also shared it with all within my org.

**Comment by jennybc** [comment]
I have a feeling you've made this Sheet "public on the web" but have not **published it to the web**. This is a common misstep and my package should have a better diagnostic for this. In the meantime please confirm that you have done "File > Publish to the web" and not just set it to public via Sharing settings.

Here's some explanation from the Sheet API docs:

https://developers.google.com/sheets/api/v3/worksheets#sheets_api_urls_visibilities_and_projections

Scroll down and you'll see these big red boxes:

<img width="874" alt="screen shot 2017-02-17 at 2 11 19 am" src="https://cloud.githubusercontent.com/assets/599454/23047207/ebada0e6-f4b6-11e6-8696-e54330289110.png">

**Comment by sagar356020** [comment]
Hey thanks for your response. I assumed that I have already authenticated googlesheets in R, which was missing and giving the error. It is resolved now.
