### ISSUE TITLE
Checking if other users are seeing a degrade in Google API speed in last week

### ISSUE THREAD

**Issue by klittle314** [jennybc/googlesheets#300]
As of 2022-02-03, the googlesheets package has been archived on CRAN.
I'm closing all issues and pull requests prior to archiving this GitHub repo.

Learn more at:

<https://github.com/jennybc/googlesheets#readme>

**Comment by jennybc** [comment]
😔 Nothing has changed here. The Sheets API has always been slow. I guess there is some hope things will speed up when I move the the new API? But it will be interesting to see if you get any other info. I don't use this as intensely as you do, so your best hope is for corroboration from other people.
