### ISSUE TITLE
Writing to multiple cells(not in rectangle) using gs_edit_cells

### ISSUE THREAD

**Issue by vikash6451** [jennybc/googlesheets#301]
I have a data frame which I am getting after running a SQL query in R. It has 4 data points let's say P,Q,R and S. I want to place P at A1, Q at A10, R at B3 and S at C44. Running the SQL multiple times and getting these data points separately involves additional cost so I would run it only once and then place the data points at different places like above. Is this possible with gs_edit_cells?

**Comment by jennybc** [comment]
Nope. Each call to `gs_edit_cells()` can address one rectangle.

**Comment by vikash6451** [comment]
Thank you for the clarification.

**Comment by jennybc** [comment]
When I rework the package to update to the new Sheets API, I will see if there's a way to make this more flexible/faster.
