### ISSUE TITLE
Issues while uploading little bit large data

### ISSUE THREAD

**Issue by abhishekagarrwal** [jennybc/googlesheets#305]
As of 2022-02-03, the googlesheets package has been archived on CRAN.
I'm closing all issues and pull requests prior to archiving this GitHub repo.

Learn more at:

<https://github.com/jennybc/googlesheets#readme>

**Comment by jennybc** [comment]
Which function are you using to write this data? I'm about to do some work on googlesheets and remind myself of how everything works! But the more you can do this as a bulk operation the better (vs sending individual cells or rows).

**Comment by abhishekagarrwal** [comment]
Based on my needs, I need to first delete the sheet with gs_ws_delete function and then after re-registering the sheet and then I am adding new sheet with function gs_ws_new and in the input parameter, I'm specifying the data frame that need to be updated on the newly created sheet.

**Comment by jennybc** [comment]
Ok thanks for the details. Will look into wholesale replacement of the contents in a faster way, w/o changing the items name or ID. I think there's another issue already open about that.

**Comment by jwbenning** [comment]
I too am having this issue. Using gs_ws_new to add a new worksheet (40 col x 8000 rows), and it's hanging up and taking up mucho memory in RStudio, to the point where I have to stop the console operation. It gets here and hangs:
```
Worksheet "Clean" added to sheet "Master_MonicaTrans".
Range affected by the update: "R1C1:R8489C40"
Accessing worksheet titled 'Clean'.
Sheet successfully identified: "Master_MonicaTrans"
Accessing worksheet titled 'Clean'.
Worksheet "Clean" dimensions changed to 8489 x 40.
```

I am able to send the head (7 rows) but that takes about three minutes.

Loving the package tho!

**Comment by jennybc** [comment]
FWIW the googledrive package now has `drive_update()` which allows uploading new content into an existing file id, but it knows nothing about Sheets *per se*. But I am closing in on making wholesale replacement easier, at the file level or worksheet level! It just requires getting this foundation laid re: the full access to the current Drive API.

**Comment by dsdaveh** [comment]
@jwbenning , I ran into a similar issue, I concluded its an inherent issue with a reasonable workaround that I wrote up in [this R Notebook](https://rawgit.com/dsdaveh/talks-and-tutorials/master/googlesheets_BARUG_Presentation/gs_upload_notebook.nb.html).  

I gave a talk on googlesheets recently that included some performance studies ([see tab "5. Performance" of this R Notebook](https://rawgit.com/dsdaveh/talks-and-tutorials/master/googlesheets_BARUG_Presentation/gsheet_oauth.nb.html)). My conclusion is that anything over 2000 rows needs to use `gs_upload(overwrite = TRUE...)`, which wipes out tabs and charts (unless you use the workaround above).

**Comment by jennybc** [comment]
Thanks @dsdaveh! I think the practical limits of the Sheets API are sadly quite different from the technical ones. I also hope that the switch to the the version might help close the gap (fingers crossed).
