### ISSUE TITLE
Error writing shiny output to googlesheet

### ISSUE THREAD

**Issue by ValorNVirtue** [jennybc/googlesheets#306]
Unable to write output values from shiny app to Google sheet with gs_add_row function.  I receive the following error:

Warning: Error in $.shinyoutput: Reading objects from shinyoutput object not allowed.

**Comment by jennybc** [comment]
This sounds like a shiny usage problem, not googlesheets?

**Comment by ValorNVirtue** [comment]
Yes, this is definitely an issue with shiny and not googlesheets.  Thanks
for the prompt response nonetheless!

Respectfully,
--
AJ Thurston

University of South Florida
Doctoral Student, Industrial & Organizational Psychology

4202 E. Fowler Avenue, PCD4118G

Tampa, Florida 33620

Office: PCD3120A
