### ISSUE TITLE
cannot use gs_edit_cells() to upload a large data and how can I assign the specific path when uploading new files to google drive

### ISSUE THREAD

**Issue by tinjuiho** [jennybc/googlesheets#307]
Title. It seems that it gets stuck when I try to upload an array to a specific sheet which is greater than 5 rows (5*7 in this case).
Modifying rows one by one is very slow but it gets stuck when uploading data at once

And how do I set my path in google drive so that uploaded file would appear in specific locations.

Thank you!

**Comment by jennybc** [comment]
I am pushing hard now on a new version that wraps the new v4 API. It will provide better ways to bulk upload data and place in a subdirectory.

Right now, googlesheets is unable to load into a specific subdirectory and at this point I won't change that until I make the big API switch. It will rely on a separate package for Google Drive operations, which is what is required under the hood to create and manage folders.

There is, however, an open PR about this which you might be able to install and use in the meantime: #194.

As for slow upload, this topic has been touched on in several issues. Users and I have discussed various workarounds. So you may want to search the issues to find and read those.

Again, the real solution is to switch to v4 API, which is my current task. Sorry that's not the answer you want to hear.
