### ISSUE TITLE
col_extent Problems 

### ISSUE THREAD

**Issue by KristenCarros** [jennybc/googlesheets#313]
Hello, 
I'm having a hard time successfully loading wide (-ish) data into my googlesheet. After specifying the col_extent parameter, the sheet changes sizes and the modification is acknowledged in R. When attempting to edit the cells, however, I'm getting an error message indicating the worksheet can't be found.  Any help would be greatly appreciated, as I'm a very new user of R. Also, thank you immensely for putting this package together. 
~ I'm trying to repeat the edit cells function a total of 5 times, which should populate 80 columns.
gs_ws_new(ws, ws ="DF", col_extent = 150)
gs_edit_cells(ws, ws = "DF", input = df4, anchor =  "R1C2", byrow =  TRUE, trim = TRUE)
Error: Worksheet DF not found.

**Comment by jennybc** [comment]
I suspect you need to store the return value of `gs_ws_new()` and then provide it as the primary input to the subsequent `gs_edit_cells()` command(s).

The addition of a worksheet is an important change to the sheet and you need to store the returned googlesheet object (which includes info on the available worksheets). Right now your Sheet (confusingly named `ws`) does not reflect the addition of a worksheet named `"DF"`. That would explain the `Error: Worksheet DF not found`.

The flow should look more like this:

``` r
ss <- SOMEHOW REGISTER THE SHEET?
ss <- gs_ws_new(ss, ws ="DF", col_extent = 150)
ss <- gs_edit_cells(ss, ws = "DF", input = df4, anchor = "R1C2", byrow = TRUE, trim = TRUE)
```

**Comment by KristenCarros** [comment]
Thank you so much!
