### ISSUE TITLE
visibility and lookup not propagated, e.g. when editing

### ISSUE THREAD

**Issue by javrucebo** [jennybc/googlesheets#315]
As of 2022-02-03, the googlesheets package has been archived on CRAN.
I'm closing all issues and pull requests prior to archiving this GitHub repo.

Learn more at:

<https://github.com/jennybc/googlesheets#readme>

**Comment by jennybc** [comment]
My main answer is "googlesheets2 will save you" (https://github.com/jennybc/googlesheets/issues/314#issuecomment-301977639).

Yeah the whole visibility thing is an elegant feature of the Sheets v3 API and has been explicitly removed from v4. And then I think I added another layer of inelegant handling of it in this package.

If you can wait for googlesheets2, do that. Or you could patch your local version as you say above. Or I'd be happy to consider a really focused PR here, to provide a solution that lives on in googlesheets(1).

**Comment by javrucebo** [comment]
In order to size the options, two questions:

- what is a *realistic* release date of `googlesheets2`?
- if a PR would be submitted and accepted, would you also release a new version on CRAN or only include in the dev-version?

**Comment by jennybc** [comment]
Realistic release date of googlesheets2 ... summer 2017. More like July/August than June.

Yes I would make a CRAN release if we/you can fix the above problem.

**Comment by javrucebo** [comment]
PR's #316, #317 and #318 will together solve the reported issue.
As I can not run your tests, I only did some simple checks.

- creating two empty sheets: one in my home drive with public visibility and one in the team drive with private visibility.
- then running below test function for each of the sheets.

```r
testsuite <- function(key, visibility=NULL, lookup=NULL) {
  message("*** gs_key")
  gs <- gs_key(key, visibility=visibility, lookup=lookup)
  message("*** gs_read_csv")
  dat <- gs_read_csv(gs)
  message("*** gs_ws_new")
  gs <- gs_ws_new(gs, "Sheet2") 
  message("*** gs_ws_rename")
  gs <- gs_ws_rename(gs, "Sheet2", "Sheet3") # calling gs_ws_modify 
  message("*** gs_edit_cells")
  gs <- gs_edit_cells(gs, "Sheet3", input=data.frame(a=letters[1:10], b=1:10))
  message("*** gs_ws_new + input")
  gs <- gs_ws_new(gs, "Sheet4", input=data.frame(a=letters[1:10], b=1:10)) 
  message("*** gs_ws_delete")
  gs <- gs_ws_delete(gs, "Sheet3") 
  gs <- gs_ws_delete(gs, "Sheet4") 
  message("*** gs_copy")
  gs <- gs_copy(gs, "gs_test2")
  message("gs_rename")
  gs <- gs_rename(gs, "gs_test3")
  message("*** gs_delete")
  gs <- gs_delete(gs)
}

testsuite("key_from_public_sheet")
testsuite("key_from_private_sheet", visibility="private", lookup=FALSE)
```
