### ISSUE TITLE
Read all subsheets from a given sheet

### ISSUE THREAD

**Issue by jimmyodonnell** [jennybc/googlesheets#320]
As of 2022-02-03, the googlesheets package has been archived on CRAN.
I'm closing all issues and pull requests prior to archiving this GitHub repo.

Learn more at:

<https://github.com/jennybc/googlesheets#readme>

**Comment by jennybc** [comment]
This is a totally natural thing to do.

I recently did maintenance of readxl (yes, reads Excel instead of Google Sheets, but same idea) and even wrote a workflows article on how to do this.

http://readxl.tidyverse.org/articles/articles/readxl-workflows.html#iterate-over-multiple-worksheets-in-a-workbook

A very similar workflow works with Google Sheets and is basically what you are doing. I use mapping functions from purrr and you use a for loop, but that's a minor detail.

I'd be happy to merge a PR that added an example of this.

**Comment by jimmyodonnell** [comment]
Bueno! I can take a crack at this in the next few weeks or so.

**Comment by jimmyodonnell** [comment]
> in the next few weeks or so

... weeks * life = months.

@jennybc To clarify, would you prefer I (1) add an example to the examples section of `R/gs_read.R`, or (2) modify the function to accept a range? I'm not terribly well versed with the tidyverse, but I'd guess that because (2) changes the output from a tibble to a list, it might be frowned upon?

**Comment by jennybc** [comment]
I'd want to handle via documentation, so I'll take (1) add an example 😄.

**Comment by Ploulackk** [comment]
Hello Jenny, thank you for the great plugin!

The problem I have is that my sheet has ~10 worksheets, and with this loop:
```
sheets = c("sheet1", ...., "sheet10")
map_dfr(sheets, ~ gs_obj %>% gs_read(ws = .x))
```

I get the infamous:

> Too Many Requests (RFC 6585) (HTTP 429).

Any tip?

PS: actually want to drop another question: why does gs_auth let's me use a token in memory, while drive_auth (from googledrive package) needs a *.rds file ? See, from vignettes:

> gs_auth: 
> token | optional; an actual token object or the path to a valid token stored as an .rdsfile
> 
> drive_auth:
> oauth_token |	Optional; path to an .rds file with a previously stored OAuth token.

**Comment by jimmyodonnell** [comment]
@Ploulackk I'm no pro with the map functions, but incorporating a pause using `Sys.sleep(2)` worked for me in a good old fashioned loop.

**Comment by jimmyodonnell** [comment]
@jennybc I forked the repo but made changes to the master branch. Before I submit a PR -- what branch would you prefer I fork?

**Comment by Ploulackk** [comment]
@jimmyodonnell Thank you for taking the time to point out the trick that was in your code. I was just hoping there was a one request-fetch all solution. 2s...how did you arrive at this value? I'll have to copy-store all my worksheets in one big aggregate, can't have users wait 20s each time they start their shiny app.

**Comment by jennybc** [comment]
@jimmyodonnell The PR should be to master branch here, which is what happens by default. As a general practice, life is better for the person making a PR if they create a branch in their fork when preparing it. It doesn't matter for a one-off PR, but in the long run, it makes it easier to stay in sync with the master repo.

**Comment by jennybc** [comment]
@Ploulackk 

> why does gs_auth let's me use a token in memory, while drive_auth (from googledrive package) needs a *.rds file ?

I regard the auth flow in googlesheets as ok, but still sort of goofy. The one in googledrive is another iteration, moving towards delegating this to a separate package for all Google APIs (see [gargle](https://github.com/r-lib/gargle)). I didn't think "token as object in memory" really came up much, so I eliminated it. The plan is for gargle to make it much easier to switch from one Google identity to another, btw. I suspect that is somehow related to your question.

**Comment by Ploulackk** [comment]
Thank you @jennybc, kind of helps to know there's a 'choice' behind that.

In my case it's much more basic than user switching (my use context is shiny, own app key/secret and auth at each session, no token server-stored).
I just find it, dare I say it, ridiculous that with googlesheet I can just
`gs_auth(token` = get_token())`
Whereas for for googledrive I have to
```
saveRDS(get_token(), "token.rds")
drive_auth(oauth_token = "token.rds")
file.remove("token.rds")
```

**Comment by jennybc** [comment]
So `get_token()` is a function in your app source? Can I see that anywhere, to get a better sense of the workflow? I don't really use these packages with Shiny so it's helpful to get a better understanding of what people are actually doing.

**Comment by Ploulackk** [comment]
Thank you for the offer to have a look at my workflow.
i don't think my sources are clean enough that I can easily share. I'll just pick the relevant part.

When my users come to the part of my shiny app that needs to check their access to some drive resource (both googlesheet access and drive files access), I display an authentification button (you'll recognize code taken from the googlesheet package):

```
        output$button <- renderUI({
                if (is.null(isolate(access_token()))) {

                        actionButton(inputId = "auth_button",
                                label = "Authorize App",
                                onclick = paste0(
                                        "location.href='",
                                        httr::modify_url(httr::oauth_endpoints("google")$authorize,
                                                query = list(response_type = "code", client_id = my_id,
                                                        redirect_uri = shiny_get_url(), scope = my_scopes,
                                                        state = "securitytoken", access_type = "offline",
                                                        approval_prompt = "auto")),
                                        "';")
                                )
                } else {
                        return()}
        })
```
Then, again using code from your package, I get the token from the session url:
```
        access_token  <- reactive({
                ## gets all the parameters in the URL. The auth code should be one of them.
                pars <- parseQueryString(session$clientData$url_search)
                
                if (length(pars$code) > 0) {
                        ## extract the authorization code
                        get_token(auth_code = pars$code,
                                client_id = my_id,
                                client_secret = my_secret,
                                redirect_uri = shiny_get_url(),
                                scope_list = my_scopes)
                } else {
                        NULL
                }
        })

```
with helpers taken also from your package:
```
get_token <- function (auth_code, client_id, 
        client_secret, 
        redirect_uri,
        scope_list) 
{
        my_drive_app <- httr::oauth_app("google",
                key = client_id, 
                secret = client_secret)
        req <- httr::POST("https://accounts.google.com/o/oauth2/token", 
                body = list(code = auth_code, client_id = client_id, 
                        client_secret = client_secret, redirect_uri = redirect_uri, 
                        grant_type = "authorization_code"), verbose = TRUE)
        
        stop_for_content_type(req, "application/json; charset=utf-8")
        
        token <- httr::content(req, type = "application/json")
        
        token_formatted <- httr::Token2.0$new(app = my_drive_app, 
                endpoint = httr::oauth_endpoints("google"),
                credentials = list(access_token = token$access_token, 
                        token_type = token$token_type, expires_in = token$expires_in, 
                        refresh_token = token$refresh_token),
                params = list(scope = scope_list, 
                        type = NULL, use_oob = FALSE, as_header = TRUE), 
                cache_path = FALSE)
        
        token_formatted
}

stop_for_content_type <- function(req, expected) {
        actual <- req$headers$`Content-Type`
        if (actual != expected) {
                stop(
                        sprintf(
                                paste0("Expected content-type:\n%s",
                                        "\n",
                                        "Actual content-type:\n%s"),
                                expected, actual
                        )
                )
        }
        invisible(NULL)
}

shiny_get_url <- function(session){
        
        if(!is.null(session)){
                pathname <- session$clientData$url_pathname
                hostname <- session$clientData$url_hostname
                port <- session$clientData$url_port
                
                url <- paste0(session$clientData$url_protocol,
                        "//",
                        hostname,
                        if(port != "") paste0(":", port),
                        if(pathname != "/") pathname) 
                url
        } else {
                NULL
        }
}
```

And from all this, it's more convenient to directly pass my reactive access_token() to an auth function rather than write the RDS (though it's minor).

A bit more background: originally, I quickly got auth to work with your gs_webapp_auth_url() and gs_webapp_get_token().
Alas, I didn't find those in the googledrive package and never achieved the same with drive_auth_config(), which is why, i ended up picking your functions behind gs_webapp_auth_url and gs_webapp_get_token to make them work but for Google Drive auth...
I hope i made my usage clear and it helps as one more usage reference!

**Comment by jennybc** [comment]
Thanks @Ploulackk. You're correct that googledrive has no provision for Shiny auth right now. That is coming and the hope is to improve upon what's here in googlesheets and to put that in gargle, so it can be used in clients for various APIs.

**Comment by Ploulackk** [comment]
Great info. I'll be watching the updates, ready and happy to remove my code that I hope to never have to maintain in the face of changing Google API syntax :)

**Comment by jimmyodonnell** [comment]
OK, @jennybc , sorry to reroute this thread further, but to clarify whether my understanding of the preferred PR workflow is correct: I fork the repo, make a branch for the fix, commit and push my changes, and submit my *new* branch as a PR against your master branch? Or merge it into my master branch first, and *then* submit a PR?

**Comment by jennybc** [comment]
> I fork the repo, make a branch for the fix, commit and push my changes, and submit my new branch as a PR against your master branch

yes 👆 is the most common workflow

**Comment by jimmyodonnell** [comment]
👌  Roger that.

This is timely advice I can reference while teaching git for Software Carpentry tomorrow!

**Comment by tiernanmartin** [comment]
@jimmyodonnell I just ran into this problem and your function has helped me overcome it - thanks!

> @Ploulackk I'm no pro with the map functions, but incorporating a pause using Sys.sleep(2) worked for me in a good old fashioned loop.

Here's a version of your function that uses `map()` instead of a for loop:

``` r
gs_read_all <- function(ss, delay = 4){ 
  ws_names <- gs_ws_ls(ss)
  
  gs_read_delayed <- function(ss, ws){
    result <- gs_read(ss, ws)
    Sys.sleep(delay)
    return(result) 
  }
 
  worksheets <- map(ws_names, ~ gs_read_delayed(ss, ws = .x))
  
  return(worksheets)
}
```

**Comment by jimmyodonnell** [comment]
@tiernanmartin Cool! Excuse the ignorance, but why might using map be preferred over a loop here? It seems that speed is not something we're trying to optimize, especially given the use of `Sys.sleep`.

A random thought now that this is on my mind: If this functionality were to be incorporated into `gs_read`, backwards compatibility could be maintained by using an argument `all=FALSE`, so that the function would only return a list if this were explicitly asked for. (I think...?)

**Comment by tiernanmartin** [comment]
I think that in this particular case either method of recursion will work just fine.

I shared the map() approach just in case others are (like me) more familiar with the map() verbs than for loops.

The backwards-compatible ’all = FALSE' argument seems like it would work well!

**Comment by jslingsby** [comment]
Any solution to the "Too Many Requests (RFC 6585) (HTTP 429)" problem raised by @Ploulackk? @jennybc?

I tried the Sys.sleep hack (below), but still get the error even with a 5 second delay (I have 57 sheets so it would be 5 minutes even if it worked!!!)

Thanks!

```
gs_delay <- function(ss, ws, sleep,...) {
  Sys.sleep(sleep)
  return(gs_read(ss, ws, ...))
  }
```

**Comment by jennybc** [comment]
Would you ever consider downloading the entire Sheet as a local Excel workbook and using readxl? The googledrive package would make that easy. Once you're trying to access dozens of worksheets, it's worth considering bulk export options, I think, even if it sounds a bit nuts. AFAICT, Google has poured a lot of resources into making Sheets <--> xlsx work quite well.

**Comment by jslingsby** [comment]
Thanks! Somehow the googledrive package had flown under my radar until now. My interim solution has been manually downloading and using your amazing readxl functions in the mean time, but it is inconvenient - I have to repeat it every week (ideally daily) as data come in.

Strange that the call hits limits since the [Google API](https://developers.google.com/sheets/api/limits) suggests 100 requests per 100 seconds per user. Unless gs_read() uses more than one request per worksheet? I'm on a paid organization account too, so you'd think the limit would be higher...

Thanks!
