### ISSUE TITLE
gs_perm_add() fails with Forbidden (HTTP 403)

### ISSUE THREAD

**Issue by dsdaveh** [jennybc/googlesheets#324]
I'm trying to run the example for gs_perm_add(), but I'm getting a permissions error.  I've modified the example below to deal with the fact this function isn't exported.

```
foo <- gs_new("foo")
googlesheets:::gs_perm_ls(foo)
# Add anyone as a reader:
googlesheets:::gs_perm_add(foo, type = "anyone", role = "reader") ## Forbidden (HTTP 403)
googlesheets:::gs_perm_ls(foo)
gs_delete(foo)
```

**Comment by dsdaveh** [comment]
Update: I've discovered this behavior is unique to my corporate Google account, but it works as described for my person google account.  The same is true for drive_share() in the new googledrive package.  Is there something special that needs to be done for corporate google accounts?  I've been using the googlesheets package extensively and this is the first time I've seen an issue with the corporate account.

**Comment by jennybc** [comment]
> Is there something special that needs to be done for corporate google accounts? 

I'm not entirely sure. There's a reason `gs_perm_add()` is not exported 😄. My current work on modifying Drive objects is happening in a new package that wraps the newer Drive API v3:

https://github.com/tidyverse/googledrive

There is already some permission-editing functionality there and it's shown in the README. I suggest you try your task with that package. If it does not work, then open an issue there, as that is where this really needs to be solved. The next reboot of googlesheets will reply on that package for all the Drive work.

**Comment by dsdaveh** [comment]
I saw the same behavior with the googledrive::drive_share().  I'll open an issue there.

**Comment by dsdaveh** [comment]
I figured this out (sort of) before I got around to creating an issue in the googledrive area:  In case anyone runs across it, this worked for me:
`googlesheets:::gs_perm_add(ss, type = "user", email = user_email, role = "owner", with_link=FALSE)`

`with_link` is the secret sauce that got it to work. I still wasn't able to get it to work with `type="anyone"`, but since I didn't need that for my use case, I didn't track it down.

**Comment by jennybc** [comment]
Thanks for the workaround! But googledrive is the real home for this functionality so if you can't do what you want, we'd love to get an issue and example, so we can fix.

**Comment by dsdaveh** [comment]
I was using googledrive a month or so ago, but its breaking for me now.  I'll put details of that over there today.  Unfortunately with regards to this issue, I can't test it anymore since I've left the company where I was seeing the problem. The behavior was different in that domain versus the public domain.

**Comment by jennybc** [comment]
Team Drive support hasn't been merged into googledrive yet but is well underway. That definitely affects how to edit permissions, so perhaps that was the problem.

**Comment by dsdaveh** [comment]
On my way to writing up the problem I figured it out (mostly).  I was working off a faded memory old (perhaps even imaginary)  documentation.  <red face emoji> I was passing the wrong object types to drive_.  I still can't transfer ownership, but the error message gave me a good trail to follow.
