### ISSUE TITLE
...R-32~ZOE.2' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by erickemde** [jennybc/googlesheets#326]
googlesheets fails on install with this error:

'\\mycomputer\R\R-32~ZOE.2' is not recognized as an internal or external command,
operable program or batch file.
Error: Command failed (1)

This is on Windows 10, RStudio 1.0.143, R 3.2.2

**Comment by jennybc** [comment]
What exact installation command did you use to get this error? Is this the output of `install.packages("googlesheets")`.

**Comment by erickemde** [comment]
Hi Jenny. I updated R to 3.4.0 and it worked fine. Thanks for making this. I'm having fun playing with it.
However, in answer to your question, 3.2.2, I tried both install.packages("googlesheets") and devtools::install_github("jennybc/googlesheets") and got the same error.
