### ISSUE TITLE
Other people's Sheets CAN show up in the spreadsheets feed!

### ISSUE THREAD

**Issue by jennybc** [jennybc/googlesheets#33]
@jzhaoo 

I've learned from simple usage that, if you view a Sheet owned by someone else in the browser, that sheet will start to show up in __your__ spreadsheets feed.

This is just a FYI. It has some implications for our understanding of when one must use a key (vs a title) and probably should affect documentation at some point. It means that you can actually access such a sheet by title, although unique key remains the best idea in that situation (and all others, actually). Interesting to know.

**Comment by jennybc** [comment]
I swear Google doesn't explicitly say anywhere which Sheets will appear in the Spreadsheets feed. I'm speaking specifically about those owned but shared by others, where things are quite ambiguous. I'm figuring it out empirically.

Collecting some links here so we can better understand this.

I've been only thinking and talking about Google Drive, but actually this notion of a Sheets home screen is helpful, because I've certainly been to mine but did not know what to call it:

  * Go to your Sheets home screen: <https://docs.google.com/spreadsheets/>
  * [Index of help topics](https://support.google.com/docs/topic/4722291?hl=en&ref_topic=4724123) re: all Google Docs editor home screens, including the Sheet home screen

This link has some good, thought still not definitive info, on sharing:

  * <https://support.google.com/drive/answer/2494886?hl=en>

**Comment by jzhaoo** [comment]
Something to note:

If you view a public ("published to the web") sheet via the link (URL with suffix /pubhtml) in the browser, that sheet will not appear in your Sheets home screen. 

Only sheets shared with you or accessed through a sharing link (URL with suffix /edit?usp=sharing), provided that the sheet is "public on the web", will appear in your Sheets home screen.

**Comment by jennybc** [comment]
Thanks for refining. Yes it seems to be some combination of how the third party Sheet has been shared and whether the authenticated user has actually clicked on the link. Too bad Google doesn't write this down anywhere (?).

**Comment by jennybc** [comment]
I guess we can content to take notes here, but there really is no issue to be addressed. Closing.
