### ISSUE TITLE
Struggling to publish the code to shiny?

### ISSUE THREAD

**Issue by hnhd** [jennybc/googlesheets#331]
As of 2022-02-03, the googlesheets package has been archived on CRAN.
I'm closing all issues and pull requests prior to archiving this GitHub repo.

Learn more at:

<https://github.com/jennybc/googlesheets#readme>

**Comment by hnhd** [comment]
Actually, it looks like it published. Though, there is now an issue whereby whenever the button is pressed it needs to reload the roller.

**Comment by jennybc** [comment]
There's not enough here for me to go on. What exactly goes wrong? Is there an error message? What is your current method of getting and sending a token? That sort of thing.

**Comment by dsdaveh** [comment]
@hnhd use `gs_auth(new_user = TRUE, token=<filename>).  I just published an example app that does what you're describing and it worked without any issues. https://github.com/dsdaveh/talks-and-tutorials/tree/master/googlesheets_BARUG_Presentation/BARUG_Survey_Response. I just published app.R and  my token file (which is not in my GitHub repo for obvious reasons).  You can look in that same repo for some examples of creating the token file, but its also well documented in the package vignettes
