### ISSUE TITLE
token in rds file

### ISSUE THREAD

**Issue by sbohora** [jennybc/googlesheets#332]
@jennybc : We put the `.rds` and `.httr.oauth`  in `.gitignore`. Do we need to put them in the shiny app when we deploy the app using `shinyapp.io`? How do we deal with private sheets? Thanks.

**Comment by jennybc** [comment]
I don't think you should have a token in an `.rds` file AND `.httr-oauth` file. You should have just one. I assume you have a token that gives your Shiny app permission to access a private sheet. This should work, but you want to isolate your (non caching) token in exactly one file. And put that file on Shinyapps.io along with your app source.

This is the exact workflow you should use to store the token:

https://cran.r-project.org/web/packages/googlesheets/vignettes/managing-auth-tokens.html#how-do-i-store-and-retrieve-a-token

It sounds like you may have neglected to do the `cache = FALSE` part.

**Comment by sbohora** [comment]
@jennybc . Thanks. Should the `.rds` file obtained after following procedure be shipped with Shiny app? Which folder/file should this `.rds` be placed if so? Thanks.

```r
library(googlesheets)
token <- gs_auth(cache = FALSE)
gd_token()
saveRDS(token, file = "googlesheets_token.rds")
```

**Comment by jennybc** [comment]
Yes the token file will need to be among the files that you upload. It should be at whatever path you load it from in the app source. The path of least resistance is to have the source file and the token file living together in the top-level directory. I am, unfortunately, not a frequent Shiny app developer, so don't do this myself very often. But I here's an example that worked when I wrote it 2 years ago:

https://github.com/jennybc/googlesheets/tree/master/inst/shiny-examples/10_read-write-private-sheet

**Comment by sbohora** [comment]
@jennybc : Thanks. Yes, I saw and followed this example. I'll let you know should there be any further questions. Thanks a lot again. I am going to close this issue.

**Comment by jennybc** [comment]
Let me know if the example is just completely wrong! It's been "aging" for a while now.

**Comment by sbohora** [comment]
@jennybc Sure. Thanks.

**Comment by jennybc** [comment]
FWIW I've been neglecting this because googlesheets itself will soon get a reboot and the development version of httr has new functionality that should make OAuth + Shiny even easier.

**Comment by sbohora** [comment]
@jennybc : Great. When will that happen?

**Comment by jennybc** [comment]
googledrive is getting ready to go to CRAN, so then the googlesheets reboot comes next! I've started but put it on hold to get googledrive ready.

**Comment by sbohora** [comment]
@jennybc : What does this mean? Is it going to CRAN for `googlesheets` only or there are other advantages as well?
>"googledrive is getting ready to go to CRAN"

**Comment by jennybc** [comment]
[google**drive**](https://tidyverse.github.io/googledrive/) is a package that wraps the Google Drive API. That will go to CRAN soon.

Then, googlesheets can get a reboot that takes advantage of googledrive. Such as the ability to use folders, upload into an existing file id, or access Team Drives. At the same time, googlesheets will be update to the new v3 Sheets API. I think it will be a major upgrade for working with Sheets, yes.

**Comment by sbohora** [comment]
@jennybc: Thanks.
