### ISSUE TITLE
Rstudio Gsheets access - Error in stop_for_content_type

### ISSUE THREAD

**Issue by Suidgeest** [jennybc/googlesheets#333]
Hi all, I'm trying to extract the key of a gsheet by running the following:

library(googlesheets)
library(dplyr)

key1 <- extract_key_from_url("URL")
sheet <- gs_key(key1)

however get this error: 

Sheet-identifying info appears to be a browser URL.
googlesheets will attempt to extract sheet key from the URL.
Putative key: 12HvlEOAmnflm7UXvLcqs6KRWGHhy17eGNgIA5ByQG8c
Worksheets feed constructed with public visibility
Error in stop_for_content_type(req, expected = "application/atom+xml; charset=UTF-8") : 
  Expected content-type:
application/atom+xml; charset=UTF-8
Actual content-type:
text/html; charset=UTF-8

The URL is that of a Gsheet that has been published to the web and set sharing settings to share with others.

What should I do to make this work? Thanks for helping out!!

**Comment by Suidgeest** [comment]
OK figured it out:

Needed to run the below first to authenticate my Google Drive

gs_auth()
token <- gs_auth()
saveRDS(token, "token.rds")

**Comment by jennybc** [comment]
Glad you're sorted out.
