### ISSUE TITLE
gs_download() issue with Google Form Responses sheets??

### ISSUE THREAD

**Issue by cmaene** [jennybc/googlesheets#336]
My apologies first if this is a completely wrong question to ask, but I am having trouble downloading Google Sheets spreadsheets, only if with Google Sheets spreadsheets which is an output from the Google Form. If I use a native Google Sheets spreadsheets (i.e. not from Google Form responses), exactly the same two line codes (below) works, but I have trouble downloading the sheets as CSV (or XLSX) only with the Google Form output (i.e. sheet name ="Form Responses 1"). The first line works without a problem, however, the downloaded documents are not CSV speadsheet data but HTML document information (always 74 kb, no matter which "Form Reponses 1" I tried to download.)

I should be able to download Google Form output Google Sheets data because it is encouraged in the README (i.e. "What the hell do I do with this?" and then "Use a Google Form to conduct a survey, which populates a Google Sheet.") - which is exactly what I was trying to do.. I could well be the only one who is having trouble but I just can't tell what is wrong. If you could assist me, I would greatly appreciate it.

***********************
source1<-gs_url("https://docs.google.com/spreadsheets/d/1B5BQ_oQxThsRJM-XUlCtbhwazTS63BiS6VZ2-87TT7w")
source1 %>% gs_download(ws="Form Responses 1",to="metrics.csv")
***********************

Again, I tried the same code with another Google Sheet document in the same setting (i.e. after simply "Publish on the web" from "File) and it works - downloaded CSV text file is indeed CSV, not HTML. But if I try on Google Sheets data from Google Form (Responses), it wouldn't work, i.e. the output CSV is in fact simply HTML descriptive document ...

**Comment by cmaene** [comment]
In fact, gs_read() error output is simpler. I switched to gs_download() to see why I was getting the "Actual content-type: text/html; charset=UTF-8" error message.

Please change the second line to:
********************
 source1 %>% gs_read(ws="Form Responses 1")
********************

**Comment by jennybc** [comment]
I'm travelling, so not in a good position to try and reproduce this. But, quickly, is there any chance that the sheet holding the form responses has not been "published to the web"? Note this is different from "public on the web" and the v3 Sheets API can only access Sheets that are "published to the web".. This is a long-running annoyance. I could certainly handle it better in the package, but luckily this has been designed away in the new sheets API, which we'll shift over to.

**Comment by cmaene** [comment]
Thank you very much for your prompt reply. I had the issue first (i.e. not doing "published to the web") in creating GS object (gs_url), so I know how to "publish to the web" by now. I also made sure that it is already published (from "File") - i.e. it now show "Stop publishing" option, so I know it is published.

However, strangely now, however I make, a new Google Sheets can be downloaded as HTML only. It doesn't matter if the new sheets are created via Google Form or not, even simply typing in a new document (and then publish to the web, always), it can only be downloaded as HTML, and not be read in a data frame. The old Google Sheets can be still downloaded as CSV, or read as a data frame, so the problem is with the new Sheets only..

I am now convinced that this is not the R package-side issue.. sorry. I think other people had a similar issue (sometimes read/download works, sometimes doesn't.)

For now, I will just manually download the sheets and then process in R without the googlesheets package..

**Comment by jennybc** [comment]
Sorry to hear of your difficulties. Please come back if you begin to think it is a problem with this package.
