### ISSUE TITLE
Unauthorized (HTTP 401). - how to refresh token?

### ISSUE THREAD

**Issue by tarunparmar** [jennybc/googlesheets#337]
I am currently trying to understand the way to code to refresh the token. 
I applied the technique as described in [this vignette ](https://cran.r-project.org/web/packages/googlesheets/vignettes/managing-auth-tokens.html) but after sometime the token saved in rds no longer seems to work even with `new_user = TRUE` . 
And the error I get is this: Unauthorized (HTTP 401) in the browser. 

The setup I have is RStudio Server  where I am creating an RMarkdown document that gets published to Connect. The first time I run this in RStudio, I manually copy paste the token in the commandline from browser popup and then it saves that to rds and I can then use the rds file with gs_auth() and document publishes fine. Here's sample code that is working for me:
```
library(googlesheets)
options(httr_oob_default=TRUE)
gs_token <- gs_auth(cache = FALSE)
gd_token()
saveRDS(gs_token, file = "googlesheets_token.rds")
gs_auth(token = "googlesheets_token.rds", new_user = TRUE)
```

**Comment by jennybc** [comment]
The final gs_auth() call -- the one where you are activating an existing
token stored to .rds -- shouldn't have new_user = TRUE. Although, from the
code, I'm not entirely sure this is harmful. It just doesn't make sense.
You would only want to do that in the first gs_auth() call = the one that
you do very occasionally, when you are requesting a token to store to file.

Any script you run repeatedly should just load the pre-existing token. You
only want to request a new one, do the browser dance, and save to file
occasionally. Not every time you run a script.

If you've been requesting tokens frequently, that will cause others to fall
off the end and become invalid, which could lead to a 401, perhaps. You can
only have 25 tokens at once, so any workflow that constantly requests brand
new tokens will experience that.

You want to request a new token infrequently and store it to file. And then
let it get auto-refreshed. Which is differently from getting a new token.

You might also consider using the default workflow and .httr-oauth and not
managing this yourself, unless you know you must do that.

HTH,
Jenny

**Comment by tarunparmar** [comment]
some things I forgot to mention...

my deployed code is like this: (notice the commented lines)
```
library(googlesheets)
#options(httr_oob_default=TRUE)
#gs_token <- gs_auth(cache = FALSE)
#gd_token()
#saveRDS(gs_token, file = "googlesheets_token.rds")
gs_auth(token = "googlesheets_token.rds", new_user = TRUE)
```
What I do is generated the token first in RStudio environment by manually copy pasting it in the console andsave it as RDS. Then for deploying to ShinyApps.io or Connect I comment those lines and just read the rds. `new_user = TRUE` may be causing the problem here. 

But my question now is how do I overcome the problem of manually copy pasting the token. How can it be achieved for a shiny app to run on ShinyApps or Connect ?
As I believe if I leave those lines uncommented then code my not execute like it does in RStudio where opens and waits for user to paste the token. Sorry if I misunderstood any of the process step, its all new and a bit too complicated for me.

The package works great for adhoc use. Trying to get a use case where it works in fully automated mode.

**Comment by jennybc** [comment]
Yes that final, uncommented line should NOT have `new_user = TRUE`.

> But my question now is how do I overcome the problem of manually copy pasting the token.

What is your OS?

**Comment by tarunparmar** [comment]
I am using Rstudio Server on RedHat 7.

**Comment by jennybc** [comment]
In that case, it's possible you can't avoid manual copy paste to acquire the token initially.

But once you've written it to file with `gs_token <- gs_auth(cache = FALSE, new_user = TRUE); saveRDS(gs_token, file = "googlesheets_token.rds")`, you should be able to use `gs_auth("googlesheets_token.rds")` in scripts that require/have no user interaction.

**Comment by tarunparmar** [comment]
Yeah, I exactly did that but does not seem to work. Not sure if this could be a Connect problem. Going to try this on my personal machine with a Shiny server or may be try to publish something to ShinyApps.io.

**Comment by jennybc** [comment]
Moving to a Shiny context only makes this more difficult. You should probably use a token from a service account. But googlesheets doesn't support that. googledrive (the R package) does and that "upgrade" will be part of the next version of googlesheets.

**Comment by tarunparmar** [comment]
I stumbled across this topic as I was trying to catch up again on this activity (to make the auth process work in auto mode without manually providing token by using a saved token e.g. rds file). 
I was curious to find if there was any new update as I have read [#166](https://github.com/jennybc/googlesheets/issues/166) and [#174](https://github.com/jennybc/googlesheets/issues/174) that the problem is related to corporate google accounts.

**Comment by jennybc** [comment]
Nothing has changed in googlesheets's auth setup. I am actively working on the successor now (https://github.com/tidyverse/googlesheets4) which will make it much easier to use a token from a service account. With googlesheets, if you need to do auth at arm's length, you will still need to go through an interactive process somewhere, capture that token in an `.rds` file and put it on the server.

**Comment by tarunparmar** [comment]
I was probably ignoring the fact that I may not have developer console for corporate account. But I did have it and setup a project in it to setup Client and Secret with "Other" as application type. 
And was able to use these to setup the script to run in auto mode.

**Comment by jennybc** [comment]
A refresh token stored on shinyapps.io can eventually fall off the end and no longer be usable for refreshing and getting a new access token. This can happen because of a period of disuse or the relevant user minting lots of other tokens (e.g. while testing or developing something else). The fix is to get a new token locally and then upload that to shinyapps.io.
