### ISSUE TITLE
gs_read() not working with taskscheduleR

### ISSUE THREAD

**Issue by kevin-dyrland** [jennybc/googlesheets#342]
Hey all,

I'm trying to run a report automatically, and have had great success with taskscheduleR that runs it everyday, even when I am on vacation. Recently, we've moved to having a googlesheet hold the email list--instead of hard coded in the script--so it is people other than me can edit who receives the report. I can run the below code manually and pull email address from the sheet.

```
sheet <-
 gs_url("https://docs.google.com/spreadsheets/d/1JxIEatZckhBpVCk51vFq2BkAG07dSS4FnKRIpnHmpVk/edit#gid=0") %>% gs_read
```

However, when I use taskscheduleR, it bombs out and my error log returns the following.

> Error in stop_for_content_type(req, expected = "application/atom+xml; charset=UTF-8") : 
>   Expected content-type:
> application/atom+xml; charset=UTF-8
> Actual content-type:
> text/html; charset=UTF-8
> Calls: source ... as.googlesheet.ws_feed -> content_as_xml_UTF8 -> stop_for_content_type
> Execution halted

Any thoughts?

**Comment by jennybc** [comment]
How is taskscheduleR getting and sending a token? (I actually don't know exactly what taskscheduleR is, btw.)

What are the publishing settings on this sheet?

**Comment by jennybc** [comment]
BTW I also acknowledge googlesheets is not doing well at transmitting this particular error message to you, due to it's being html and designed for consumption in the browser.

**Comment by kevin-dyrland** [comment]
Huh. I think your first question hits the nail on the head--taskscheduleR is an R addin that I use to run scripts, as I could never get the windows autotask program to work. I've noticed that I get no workspace from it when it is done, however (it feels like an isolated instance of R)...which means I should be forcing a token send?

How do I force a token send? I'm thinking a `gs_webapp_get_token()` command and treating taskscheduleR as if it is a shiny (self contained) app?

Publishing settings are that it is not. I can still see it with `gs_ls()`, though. I guess I'm confused as to why it needs to be published to be read in...

**Comment by kevin-dyrland** [comment]
All right, so I read some documentation (that you wrote?) and found that I just needed to store a token.

```
token <- gs_auth(cache = FALSE)
gd_token()
saveRDS(token, file = "googlesheets_token.rds")
```

Was successful for me. Now to figure out authorizing for gmailr() from a script....but that's another thread!

**Comment by jennybc** [comment]
Great!
