### ISSUE TITLE
httpuv::startServer() -> failed to create server

### ISSUE THREAD

**Issue by beigebrucewayne** [jennybc/googlesheets#343]
Had been using the package with no problems. However, now I keep getting this error. I tried uninstalling and reinstalling the packages - no dice. I even tried using googlesheets4 and got the same error. Not sure what is going on.

<img width="801" alt="screen shot 2017-11-03 at 10 23 46 am" src="https://user-images.githubusercontent.com/25046261/32387317-5b663588-c081-11e7-8a58-710603452e2a.png">

**Comment by jennybc** [comment]
I don't think it's a googlesheets problem. I suspect it lies elsewhere, either in another package or combination of packages or in your system. It's the first report I recall seeing.

That being said, you can get probably back in business by forcing out-of-bound authentication like so:

```
library(googlesheets)
options(httr_oob_default = TRUE)
gs_auth()
gs_ls()
# etc etc
```

The OAuth dance is a bit clunkier but once you've got the token, things should work the same.

**Comment by beigebrucewayne** [comment]
I'm not sure what is going on either, but your suggestion worked. Thank you!

**Comment by jennybc** [comment]
You might want to re-install httr and httpuv.

What OS are you on?

It might also just self-resolve. It could be something intermittent based on your recent behaviour outside of R/googlesheets, like another process interfering with a port or something.

I'm going to close. Good luck!

**Comment by jennybc** [comment]
I just experienced and resolved this myself, so want to leave more notes for future searchers.

Yes this error from httpuv is symptomatic of another process sitting on the port httr uses for auth, which is 1410:

``` r
Error in httpuv::startServer(use$host, use$port, list(call = listen)) : 
  Failed to create server
```

The most minimal fix is this:

``` r
options(httr_oob_default = TRUE)
```

which will cause httr-using packages to use out-of-bounds authentication. This got me back into business immediately and I was able to obtain a token.

That is, however, annoying.

I gather it's likely that the guilty process is a zombie process and you may want to kill it. How? You could reboot. But I used a tip from https://github.com/rstudio/httpuv/issues/34#issuecomment-53093522 to get the PID with `sudo lsof -i :1410` (in my case it *was* a zombie R process) and then `kill -9 PID` to kill it. Problem solved.
