### ISSUE TITLE
gs_ls() returns 500 sheets but very few of which are in my drive or shared with me. 

### ISSUE THREAD

**Issue by alfie-bae** [jennybc/googlesheets#344]
As of 2022-02-03, the googlesheets package has been archived on CRAN.
I'm closing all issues and pull requests prior to archiving this GitHub repo.

Learn more at:

<https://github.com/jennybc/googlesheets#readme>

**Comment by jennybc** [comment]
Re: the large number of sheets ... do you perhaps need to empty the trash?

But if you have the key or url, you should not be looking up anyway. Try putting `lookup = FALSE` in your `gs_key()` call, for example.

I have never had a problem with auto-refresh, so I'd need more details there to speculate on why we're having a different experience. Is it about finding a token to auto-refresh or about succeeding with the refresh effort? You can't have more than 25 valid refresh tokens for an account. So if you're creating new tokens with wild abandon in one project, the tokens cached to file in another project can "fall off the end", which will definitely cause refresh to fail. This I have experienced.

googlesheets is very long in the tooth right now, with a complete reboot coming very soon. It's got some real design flaws (some of what's is bugging you), which I will not repeat again.

**Comment by alfie-bae** [comment]
Hi Jenny,

Thank you for responding to my comment. Having explored setting lookup=FALSE, I found that this did resolve my issue with gs_ls not providing the spreadsheet in question with my returned sheets. However, I found that the sheet had to be "published to the web" for this method to work.

As many of the sheets we're working with contain sensitive information, making these sheets publically accessible isn't a workable solution for us in this case.   

Looking forward to the new version of googlesheets!

**Comment by jennybc** [comment]
What are you using for `visibility`? It should be `"private"`.

You are suffering from a combination of a bad design of the v3 API (this visibility stuff has been removed in v4) and inelegant wrapping by me. But plenty of people use googlesheets to access private sheets, so let's stick with it until we get it working for you.

**Comment by sugottfried** [comment]
I re-installed 'googlesheets' and now things seem to be working.
