### ISSUE TITLE
gs_add_row() skips a line (first sheet only)

### ISSUE THREAD

**Issue by tres-pitt** [jennybc/googlesheets#345]
I'm iterating through 7 sheets, adding a single row. about 50 rows per sheet on average. for the first sheet, gs_add_row() skips line 49 and writes to line 50. line 49 remains blank. all other sheets are written properly.

**Comment by jennybc** [comment]
Hard to say what is going on. If you change the row order of the input, does the blank line happen in a different place? Is there something special about that bit of input?

**Comment by tres-pitt** [comment]
actually it's only a single line of input (one row); my script typically only appends one row per sheet at a time.

it only happened the first time - ie, directly after i called `gs_edit_cells()` to write the headers and initial batch of 40-50 rows per tab. since then I've added about 10 rows and there's never been a gap again

probably not reproducible :( but thanks for your hard work on an amazing package!

**Comment by jennybc** [comment]
OK. Let's hope it was just a glitch in the matrix.

**Comment by tres-pitt** [comment]
So I have an idea what might have happened. I noticed that if I just delete contents of gsheet cells (rather than deleting entire rows, or if they are virgin cells), then the API will bring these rows into r with 'NA' values, even though they appear completely blank/empty in google sheets
