### ISSUE TITLE
curl timeout

### ISSUE THREAD

**Issue by samuel-rosa** [jennybc/googlesheets#346]
Is it possible to set `CONNECTTIMEOUT` when trying to download a google sheet? Specifically, I have found the need to increase the curl timeout setting a bit to avoid getting the following error:
```
Error in curl::curl_fetch_memory(url, handle = handle) : Timeout was reached: Resolving timed out after 10000 milliseconds 
```

**Comment by jennybc** [comment]
There's no direct access to this via googlesheets itself. I (or maybe you) would need to see if there is a curl setting (as in an option or env var) that could be set prior to the call.

**Comment by samuel-rosa** [comment]
I tried using `curl_fetch_memory` and it worked. `download.file` also works. So I guess that the problem is not in `curl` timeout setting. Perhaps something to do with DNS settings and the gs API. I'll let you know if I find the solution.

**Comment by jennybc** [comment]
If you are willing to download the whole sheet, you might also want to look into [googledrive](http://googledrive.tidyverse.org). It is a more modern package and can work with Sheets at the file level.

**Comment by samuel-rosa** [comment]
I have found that using OpenDNS servers solves my problem.
More info here: https://support.opendns.com/hc/en-us/articles/228007087-Ubuntu
