### ISSUE TITLE
Update Contents of Entire Sheet (remove all previous data first)

### ISSUE THREAD

**Issue by kmkmjohnson** [jennybc/googlesheets#350]
I want to update an existing sheet with new data but was running into the problem of older data still existing if the newer data had fewer rows than the older data. I am currently using gs_edit_cells to first remove all existing data by uploading a df with a sufficient number of empty fields before using gs_edit_cells again to upload the newer data. Wondering if there is a more elegant solution already built into the package that I'm missing or perhaps this would be an idea for an enhancement? 

Thanks for your work on this package!

**Comment by jennybc** [comment]
I'm afraid there is no elegant solution right now. A workaround along your lines is probably necessary.

**Comment by kmkmjohnson** [comment]
Thank you.
