### ISSUE TITLE
Way to export R output into googlesheets?

### ISSUE THREAD

**Issue by krphillips** [jennybc/googlesheets#353]
As of 2022-02-03, the googlesheets package has been archived on CRAN.
I'm closing all issues and pull requests prior to archiving this GitHub repo.

Learn more at:

<https://github.com/jennybc/googlesheets#readme>

**Comment by jennybc** [comment]
Please have a look at `gs_new()`, `gs_ws_new()`,`gs_edit_cells()`, `gs_add_row()`. All are various ways to put data from an R object into a Google Sheet.

If my answer suggests I'm misunderstanding you, then hopefully it at least helps us get to a more specific question.
