### ISSUE TITLE
gs_add_row is not working.

### ISSUE THREAD

**Issue by naikabhilash** [jennybc/googlesheets#355]
Hi Jenny,  
  The package was working fine until yesterday. Today while running gs_add_row function I am getting this error message "Error in function_list[[k]](value) : Bad Request (HTTP 400).",  although the gs_ls() function is working perfectly fine. I tried reinstalling the googlesheets package. It didn't make any difference.

Kindly help

Thanks

**Comment by jennybc** [comment]
Has anything changed in your situation?

**Comment by jennybc** [comment]
Glad to hear it.

I'm not sure if Google's error messages contain any info that we don't expose. But I will definitely look into this in the reboot. It can make a huge difference when troubleshooting.
