### ISSUE TITLE
delete row functionality

### ISSUE THREAD

**Issue by reachsalman** [jennybc/googlesheets#357]
As of 2022-02-03, the googlesheets package has been archived on CRAN.
I'm closing all issues and pull requests prior to archiving this GitHub repo.

Learn more at:

<https://github.com/jennybc/googlesheets#readme>

**Comment by jennybc** [comment]
Have you tried setting the value of such cells to `""`?

No, there is no such explicit function. I have just started work in earnest on a reboot of this package, but wrapping the more modern Sheet v4 API. I won't add any functionality here, but you're welcome to open an issue there to remind me of this need.

https://github.com/tidyverse/googlesheets4
