### ISSUE TITLE
Corporate gmail vs standard  

### ISSUE THREAD

**Issue by nospam56** [jennybc/googlesheets#359]
We're on a corporate gmail and use sheets extensively.
I'd like to use R , but seem to run into all kinds of security issues.
Authentication works, but then I can't even get my list.

Authentication complete.
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Couldn't resolve host name

**Comment by jennybc** [comment]
Can see the exact code that leads to your error?

**Comment by nospam56** [comment]
It turns out its not the code, but the local firewall.
The code works from other physical locations.  
gs_auth() was asking for permission, but the token wasn't allowed to download.
The tokens are only valid for a short time, so I will still need to determine how to refresh them.
Some of that apparently needs to be done up on Google first.

**Comment by jennybc** [comment]
OK sounds like it's not a problem to solve inside this package.

Once googlesheets4 is functional, it will be easier to use service accounts and their tokens and to avoid OAuth. It seems possible that will work better for situations like yours, but I can't say for sure.
