### ISSUE TITLE
Can't access authentication page in browser using gs_auth()

### ISSUE THREAD

**Issue by dddyvonne** [jennybc/googlesheets#361]
As of 2022-02-03, the googlesheets package has been archived on CRAN.
I'm closing all issues and pull requests prior to archiving this GitHub repo.

Learn more at:

<https://github.com/jennybc/googlesheets#readme>

**Comment by Richard-Barrett** [comment]
Try putting in the googlesheets client_id from the API Project you made in the google developer console.
