### ISSUE TITLE
Cannot build vignettes

### ISSUE THREAD

**Issue by florisvdh** [jennybc/googlesheets#363]
It appears that `googlesheets_token.rds` does not exist in `../tests/testthat/`. See below output from `devtools::check(document = FALSE)`. This makes `devtools::install_github()` to fail with the `build_vignettes = TRUE` argument set.

```
* preparing ‘googlesheets’:
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ... ERROR
Quitting from lines 37-41 (basic-usage.Rmd) 
Error: processing vignette 'basic-usage.Rmd' failed with diagnostics:
Cannot read token from alleged .rds file:
../tests/testthat/googlesheets_token.rds
Execution halted
Error: Command failed (1)
Execution halted
```

**Comment by jennybc** [comment]
Yes, I cannot ship the package with my OAuth token! I have it in the correct place locally and on Travis. You will not be able to install from GitHub with `build_vignettes = TRUE`.
