### ISSUE TITLE
gs_edit_cells starts to become super slow recently

### ISSUE THREAD

**Issue by WoodyWD** [jennybc/googlesheets#367]
Previously, when I use gs_edit_cells, it only becomes slow when the data set is too big (probably more than 20000 values). Starting from this Monday, I am experiencing a super slow speed using gs_edit_cells even with a small data input. Here're couple examples I got:
1. 125 values
![screen shot 2018-07-11 at 2 06 15 pm](https://user-images.githubusercontent.com/20912625/42599323-b8082b64-8513-11e8-8751-0ee43c980211.png)

2. 375 values
![screen shot 2018-07-11 at 2 06 21 pm](https://user-images.githubusercontent.com/20912625/42599337-c5b24574-8513-11e8-9e4d-14af45a57205.png)

3. 625 values
![screen shot 2018-07-11 at 2 06 32 pm](https://user-images.githubusercontent.com/20912625/42599351-cf5bdf4a-8513-11e8-9349-c35f5085667c.png)

4. 1250 values
![screen shot 2018-07-11 at 2 06 37 pm](https://user-images.githubusercontent.com/20912625/42599360-d7f550aa-8513-11e8-9257-05a16c5f902d.png)

I also want to try my usual input size 5000 values, but the process never ends and I have to forced kill it. However, before when I try to input a 5000 values of empty set, it only takes 2mins top to finish. But right now even with 1250 values, it will take more than 6 mins on user side. Is there anyone experiencing the same issue I have here?

**Comment by jennybc** [comment]
There is a problem with Google Sheets (and Docs and Slides) right now:

https://www.google.com/appsstatus#hl=en&v=status

**Comment by jennybc** [comment]
Let us hope for the best then.

**Comment by WoodyWD** [comment]
Hi Jenny, it seems not to be an issue on Google Sheets side. I test the same thing locally using R version 3.3.3, it only takes 39 secs to edit 1250 values in googlesheets.
![screen shot 2018-07-25 at 3 59 51 pm](https://user-images.githubusercontent.com/20912625/43232026-c73159d8-9023-11e8-9b0d-c2431309094d.png)

However, compare to the result I uploaded before using R 3.5.1 on our R studio server, it took 255 secs which is almost 7 times as what we spend on R 3.3.3

Is there anything happened in R 3.5.1 could slow down this function in googlesheets?

**Comment by WoodyWD** [comment]
I checked the difference between 3.5.1 and 3.3.3 and found nothing would impact on this. However, I did test the same code in local R studio with 3.5.1, it's much faster than our server. I guess it would be something related to our R studio Server. 

Thank you so much Jenny for your help!

**Comment by jennybc** [comment]
I can certainly imagine that the performance in the context of RStudio server is relevant. But I don't have anything specific or constructive to say. If you have RStudio support, perhaps you could ask through that channel if there are known issues re: accessing external APIs and speed.
