### ISSUE TITLE
Register a Sheet expression

### ISSUE THREAD

**Issue by rgaiacs** [jennybc/googlesheets#371]
As a first time user, that skip the tutorial and jump to [Overview of functions](https://github.com/jennybc/googlesheets#overview-of-functions), the term "Register a Sheet" isn't clear to me. Maybe "Connect" would be a better word than "Register".

**Comment by jennybc** [comment]
Thanks for the feedback. This package is being subsetted in favour of <https://github.com/tidyverse/googlesheets4>. So it is very much in minimal maintenance mode.
