### ISSUE TITLE
Use gid to specify worksheet

### ISSUE THREAD

**Issue by rgaiacs** [jennybc/googlesheets#372]
Documentation of `gs_read` says

> Usage
>
> `gs_read(ss, ws = 1, range = NULL, literal = TRUE, ..., verbose = TRUE)`
>
> Arguments
> 
> - `ss`: a registered Google spreadsheet, i.e. a googlesheet object
> - `ws`: positive integer or character string specifying index or title, respectively, of the worksheet

Would be great if `ws` could also be the `gid` that you find in the URL. `gid` is persistent against change in the name of the worksheet.

**Comment by jennybc** [comment]
Thanks for the feedback. This package is being subsetted in favour of <https://github.com/tidyverse/googlesheets4>. So it is very much in minimal maintenance mode.

I encourage you to make this suggestion in <https://github.com/tidyverse/googlesheets4/issues>.
