### ISSUE TITLE
exact match for gs_upload

### ISSUE THREAD

**Issue by smikeecz** [jennybc/googlesheets#373]
Function `gs_upload` is using `gs_ls` which searches the sheet by the `sheet_title` using regex. This is not suitable for updating the sheet whose name is a substring of another sheet in my G account. 
Could you add another option to `gs_upload` function, e.g., `exact_match = FALSE`, to deal with such case? Actually, I expected such behavior (exact matching) from `gs_ls` function too and thus it was quite demanding to investigate the reason of nonfunctional sheet update.

Thanks,
Michal

**Comment by jennybc** [comment]
googlesheets is going into "archival" mode and stuff of this nature falls under "won't fix".

You can accomplish the same now with a more modern package that **is** under active maintenance.

See `googledrive::drive_upload()`. Docs are here:

https://googledrive.tidyverse.org/reference/drive_upload.html

The examples show how to request upload and convert to a Sheet.

BTW the package that will replace googlesheets is here (still dev only, not on CRAN):

https://github.com/tidyverse/googlesheets4
