### ISSUE TITLE
gs_url() curl issue

### ISSUE THREAD

**Issue by MeganBeckett** [jennybc/googlesheets#374]
As of 2022-02-03, the googlesheets package has been archived on CRAN.
I'm closing all issues and pull requests prior to archiving this GitHub repo.

Learn more at:

<https://github.com/jennybc/googlesheets#readme>

**Comment by jennybc** [comment]
I think I would need to see the actual code or package to shed any light on this.

Just so you know, googlesheets (this package) is being sunsetted very soon, in favour of a successor googlesheets4:

https://github.com/tidyverse/googlesheets4

Also, depending on what you're doing, a great deal of googlesheets's functionality (this package) can be accomplished with the already-released and actively-maintained googledrive package:

https://googledrive.tidyverse.org

So, in terms of the development roadmap for your package, I recommend you look towards those packages as dependencies and not googlesheets.
