### ISSUE TITLE
New function suggestion - Clear Cell Contents

### ISSUE THREAD

**Issue by howard-gu** [jennybc/googlesheets#378]
Hi Jenny,

At the moment I am updating GoogleSheets using your (fantastic) package, and the current process is:

1. gs_edit_cells -> add "blank" cell values to clear contents first
2. gs_edit_cells -> add in actual values

The reason I do this is because the overall # of rows of cells could be less, and so clearing ensures that I don't have old, leftover data.

However, this essentially doubles the run-time given the speed of gs_edit_cells. I was wondering if there was a way to clear cells faster? If not, would be great if you could add this feature into any future release/upgrades!

Thanks,
Howard

**Comment by jennybc** [comment]
I would not add anything new to googlesheets at this point. So will open this on googlesheets4 instead? Thanks.

https://github.com/tidyverse/googlesheets4
