### ISSUE TITLE
Feature request: Allow passing a function to `gs_read(..., progress)`

### ISSUE THREAD

**Issue by brianwdavis** [jennybc/googlesheets#380]
I use `gs_read` in some Shiny apps to let users on my team select different sources of data to display and manipulate, but the Google API isn't blazing fast. I find myself frequently wrapping these calls with progress bars from Shiny, but those require hardcoded increments. I poked around and saw that with `gs_read(..., progress = T)` in an interactive session, `httr::progress()` is called, but it would be great if we could pass in some other progress-bar-generating function there.

Would this be a huge pain to find the downstream effects for implementing?

**Comment by jennybc** [comment]
googlesheets will soon be given an old watch and fondly retired (not literally, but it won't see further major development). Suggestions for features should be registered on its successor: [googlesheets4](https://github.com/tidyverse/googlesheets4).
