### ISSUE TITLE
Privacy concerns

### ISSUE THREAD

**Issue by hwsamuel** [jennybc/googlesheets#384]
I'm allowing this package to access my Google Sheets. Does that mean that my data can be viewed by the developers? It's a naive question, but I'm not too clear about the privacy coverage here.

**Comment by jennybc** [comment]
Good question! 

TL;DR
NO, the developers cannot see your data at all.

googlesheets is slated to be replaced by [googlesheets4](https://googlesheets4.tidyverse.org), which is part of a newly-written-down privacy policy:

https://www.tidyverse.org/google_privacy_policy/

Everything we say there is accurate for googlesheets package as well.
