### ISSUE TITLE
What to do when testthat tests depending on googlesheets fail

### ISSUE THREAD

**Issue by DataStrategist** [jennybc/googlesheets#386]
Just hit this bug, my `testthat` run was freezing as soon as it hit a googlesheets test, and I figured it out, so just documenting here.

When you use the RStudio Test button on the UI, the testthat interface will freeze. 
![image](https://user-images.githubusercontent.com/8094091/62286107-fc02c700-b44e-11e9-9653-92ba1b4277ce.png)

You can start seeing what the problem is when you run `devtools::test()`, which will spawn a new authorization window. So clearly, even if you have saved the `.httr-oauth` file in the project, the test run can't find it.

In order to resolve, just copy that file into `/tests/testthat/` that fixes the problem :)

Jenny, feel free to close this or comment/ask whatevs :)

**Comment by jennybc** [comment]
How to rig tokens for googlesheets is documented in the existing vignette: https://cran.r-project.org/web/packages/googlesheets/vignettes/managing-auth-tokens.html

However, I now think that approach is over-wrought and also the auth system can be improved, which leads us to ...

googlesheets is sunsetted now, with googlesheets4 on the horizon. googlesheets4 uses the gargle package for auth, which has detailed instructions for non-interactive auth, such as in testing:

https://gargle.r-lib.org/articles/non-interactive-auth.html

https://gargle.r-lib.org/articles/articles/managing-tokens-securely.html
