### ISSUE TITLE
Export plotly objects into googlesheets

### ISSUE THREAD

**Issue by TeoGJ** [jennybc/googlesheets#388]
Hi Jenny,

I'm currently working with a GS spreadsheet and right now I'm generating a report which I want to include some plotly objects that ideally I'd like to upload to GS again on a worksheet previously created in R. My goal is to do it as much proper and elegant as possible and without need to copy and paste screenshots of each plot, but unfortunately until now I'm trying through gs_edit_cells() but it gives me the following error:

`Error in catch_hopeless_input(input) : 
  Non-data-frame, list-like objects not suitable as input. Maybe pre-process it yourself?`

What should I do to overcome this?

Thanks a lot in advance,

Kind regards,
Teo

**Comment by jennybc** [comment]
This may, in fact, simply fall out of scope for what we're able and willing to push into a Google Sheet from R. I don't have a proper understanding of what is actually necessary to put a plotly object into a Sheet.

Also, googlesheets is sunsetted and no new features will be implemented. So even if this ideas has legs, it will need to be worked out in an issue on googlesheets4, the successor. It does not have write capability yet, but that is coming.

https://github.com/tidyverse/googlesheets4
