### ISSUE TITLE
gs_edit_cells() not working for google sheet more than 100k rows

### ISSUE THREAD

**Issue by litongw** [jennybc/googlesheets#391]
As of 2022-02-03, the googlesheets package has been archived on CRAN.
I'm closing all issues and pull requests prior to archiving this GitHub repo.

Learn more at:

<https://github.com/jennybc/googlesheets#readme>

**Comment by jennybc** [comment]
Looks like this is a problem in the underlying helper package cellranger and it has been fixed on GitHub (https://github.com/rsheets/cellranger/pull/28) but I haven't done a release in a long time.

Try `devtools::install_github("jennybc/cellranger")`, then have another go.
