### ISSUE TITLE
gs_ws_new and gs_ws_delete use different arguments for sheet identification

### ISSUE THREAD

**Issue by jg-ookla** [jennybc/googlesheets#392]
gs_ws_new uses `ws_title` to identify the name of the sheet. 
gs_ws_delete_ uses `ws` to idenfiy the name of the sheet.

For the sake of continuity, wondering if gs_ws_new and gs_ws_delete can _both_ use `ws_title` as an argument?

**Comment by jennybc** [comment]
This is intentional.

`gs_ws_new()` must get a **string** as the title via `ws_title`.

Whereas `gs_ws_delete()` can accept a worksheet title OR an integer identifying its position, which is true for many other functions that accept a `ws` argument.
