### ISSUE TITLE
Writing to sheet from ShinyApp

### ISSUE THREAD

**Issue by melvidoni** [jennybc/googlesheets#393]
When I'm using my shiny app on shinyapps.io, and press the button that should write to the CSV, it freezes. But if I go to the log on shiny, it shows the following:

```
Waiting for authentication in browser...
2019-09-16T22:49:15.140661+00:00 shinyapps[838339]: Press Esc/Ctrl + C to abort
2019-09-16T22:49:15.142753+00:00 shinyapps[838339]: Please point your browser to the following url:
{url goes here}
```

The file is published, and 'anyone with the link can edit', but still does not work. Is there a workaround to fix this?

**Comment by jennybc** [comment]
Does this work when you run the app elsewhere?

It's a fairly nonstandard workflow to write into a Sheet with no authentication whatsoever. I don't have personal experience doing that. The messages in the log suggest you may not able to write via the Sheets API with no token, which would not surprise me. When someone does this in the browser, they still probably have to be logged into Google (?).

I'd also get the code working locally, in an unattended fashion (e.g. script) before adding the extra difficulty of Shiny.

**Comment by melvidoni** [comment]
Hello @jennybc. Yes, I did try it in an script as well, but it that case it just redirected me to a google log-in screen. Shiny does the same locally, but on the shinyapps.io it just doesn't do that. But my problem is that it shouldn't ask to be logged in Google either. It should just write the sheet.

**Comment by jennybc** [comment]
Yeah this is not going to "just work" like this with Shiny. The token flow is different for a web application. googlesheets contains some examples of working Shiny apps. Or at least they did once work.

https://github.com/jennybc/googlesheets/tree/master/inst/shiny-examples

FWIW, we are working on making Shiny auth part of gargle, which is the new auth strategy for googledrive, googlesheets4, bigrquery, gmailr, etc. So this should become easier in the successor to this package.

**Comment by melvidoni** [comment]
Yes, it worked before! No worries, thanks for the replies @jennybc :D
