### ISSUE TITLE
Switching gmail accounts not working in the google sheet page

### ISSUE THREAD

**Issue by anjana7anilkumar** [jennybc/googlesheets#398]
While navigating to the initial google sheet page with the collection of google sheets, when there are two gmail accounts, user can navigate to the google sheet page of the other gmail account only when the user is not performed any scrolling.But, when the page is scrolled to the middle or to the bottom of the list, then the switching is not working

**Comment by jennybc** [comment]
This sounds like an issue in the browser interface for OAuth, which is outside the scope of an R package. We just use the token returned to us by this browser-facilitated process.

Also, this package is essentially deprecated and I would advise switching to googlesheets4 for any new work on Google Sheets from R.
