### ISSUE TITLE
Im getting a lot more errors using sheet_write()

### ISSUE THREAD

**Issue by douglascm** [jennybc/googlesheets#399]
Error: Expected content type 'application/json' not 'text/html'.
<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 408 (Request Timeout)!!1</title>
  <style>...

My other machine running version sith sheets_write() used to work 90% of the time, now its a lot lower than that while also slower.
Data was about 4k rows with 40 cols

**Comment by jennybc** [comment]
The Sheets v3 API googlesheets hits is slowly being turned off and will fully shut down in the next month or so.

My main advice is to shift your work with Google Sheets from R to the replacement package, which wraps the Sheets v4 API that is officially supported:

https://github.com/tidyverse/googlesheets4
