### ISSUE TITLE
Permissions on uploaded sheets

### ISSUE THREAD

**Issue by jennybc** [jennybc/googlesheets#62]
@jzhaoo @ironholds @noamross

We've got basic upload capability here. But it seems to make the Sheet in question private. How feasible is it to set the sharing status programmatically, given [how we are uploading](https://github.com/jennybc/gspreadr/blob/d7227eceac96bfb94721d5bafda6526f74784b21/R/edit-spreadsheets.R#L434-L493)? And is that something we should even get into here in gspreadr? Does `driver` already facilitate that?

**Comment by Ironholds** [comment]
Um. Hmn. So, it should be doable! There's the ability to modify metadata, through a PATCH call - that should include the sharing settings. In [this call](https://github.com/Ironholds/driver/blob/master/R/files.R#L283) for example, I set the title and description of a just-uploaded file.

**Comment by jzhaoo** [comment]
To set the sharing status, we will have to send a POST to the [Permissions feed](https://developers.google.com/drive/v2/reference/permissions) using the [insert method](https://developers.google.com/drive/v2/reference/permissions/insert). Definitely doable!

Will be something like this:

`httr::POST("https://www.googleapis.com/drive/v2/files/sheet_key/permissions/", get_google_token(), body = list("role" = "reader", "type" = "anyone", "withLink" = TRUE), encode = "json")`

Additional info about the [request body properties](https://developers.google.com/drive/web/manage-sharing).

**Comment by jennybc** [comment]
With c77c6736f02c35eff51a5810635dfa4cf9185028, we now have the capability to manipulate permissions (query, add, delete, edit). These functions are not ready for show time yet, however. They are currently ALL unexported.

**Comment by jennybc** [comment]
At some point, we will hook these functions up to user-facing functions for spreadsheet editing or creation. If someone else is interested in programmatically editing spreadsheet permissions, speak up here.

**Comment by 17843** [comment]
Yes, this would be great. And/or an option to specify folder (i.e. parent) as per https://developers.google.com/drive/web/folder#inserting_a_file_in_a_folder for an option allowing me as user to upload files into a folder with already set permissions.

Great package though, thank you!
