### ISSUE TITLE
My gsheet is 'published to the web' but I still get 'Error: oauth_listener() needs an interactive environment' when knitting

### ISSUE THREAD

**Issue by benmarwick** [jennybc/googlesheets#79]
How can I avoid having to authorise when accessing my [google sheet](https://docs.google.com/a/uw.edu/spreadsheets/d/1vFtO8i3zH8pk4RoxkcQw5kFtCDeooYVimUaXGD8n1WY/)?  My sheet is both 'published to the web' and 'public on the web'. 

Here's my R markdown:

```{r}
library(gspreadr)
library(dplyr)

# register sheet
my_gsheet_key <-  "1vFtO8i3zH8pk4RoxkcQw5kFtCDeooYVimUaXGD8n1WY"
my_gsheet <- register_ss(my_gsheet_key, visibility = "public") 
# also tried it without the visibility argument, no difference

# get data
LOI <- my_gsheet %>% get_via_csv(ws = 5)
all_data <- my_gsheet %>% get_via_csv(ws = 1)
```

This works fine interactively (and is super fast!). But when I knit with R-3.1.2, I get:

```
Quitting from lines 2-11 (Preview-1f42c47301a.Rmd) 
Error: oauth_listener() needs an interactive environment.

Execution halted
```

and with R-3.2.0 the error message is slightly different: 

```
Quitting from lines 2-12 (test.Rmd) 
Error: interactive() is not TRUE

Execution halted
```

What am I missing?

```
> sessionInfo()
R version 3.1.2 (2014-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
[1] dplyr_0.4.1    gspreadr_0.1.1

loaded via a namespace (and not attached):
 [1] assertthat_0.1  bitops_1.0-6    DBI_0.3.1       devtools_1.7.0 
 [5] digest_0.6.8    evaluate_0.5.5  formatR_1.0     htmltools_0.2.6
 [9] httpuv_1.3.2    httr_0.6.1.9000 jsonlite_0.9.14 knitr_1.9      
[13] lazyeval_0.1.10 magrittr_1.5    parallel_3.1.2  plyr_1.8.1     
[17] R6_2.0.1        Rcpp_0.11.4     RCurl_1.95-4.5  rmarkdown_0.5.1
[21] stringr_0.6.2   tools_3.1.2     XML_3.98-1.1    yaml_2.1.13 
```

```
> sessionInfo()
R version 3.2.0 alpha (2015-03-25 r68091)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
[1] dplyr_0.4.1    gspreadr_0.1.1

loaded via a namespace (and not attached):
 [1] Rcpp_0.11.5       XML_3.98-1.1      digest_0.6.8     
 [4] assertthat_0.1    bitops_1.0-6      R6_2.0.1         
 [7] plyr_1.8.1        DBI_0.3.1         magrittr_1.5     
[10] httr_0.6.1        lazyeval_0.1.10   rmarkdown_0.5.3.1
[13] devtools_1.7.0    tools_3.2.0       stringr_0.6.2    
[16] RCurl_1.95-4.5    parallel_3.2.0    htmltools_0.2.6  
```

**Comment by jennybc** [comment]
What's the working directory situation? I suspect your working directory was one directory when you did the interactive OAuth dance and its another when you are knitting. The OAuth thing leaves a file called `.httr-oauth` behind and that's what makes the automatic token refresh possible. If it can't be found when knitting, `gspreadr` will try to do the browser thing and fail as you describe above. To see my silly workaround for an Rmd doc in the package go here:

https://github.com/jennybc/gspreadr/blob/master/data-for-demo/01_create-gapminder-gspreadsheet.R

The code right below "damn you …" is the good part :)

**Comment by benmarwick** [comment]
Thanks, yes, if I set the working directory to the location of the source file, and I've previously manually authenticated, then the knit succeeds. 

But I want to be able to knit without _ever_ having authenticated. In the vignette I see 'No authorization is used when visibility is set to "public"'. But is at least one initial authorisation always necessary? How can I avoid that?

**Comment by jennybc** [comment]
Oh that's different. Your request to access with "public" visibility, now that I read your code more carefully, should work. So I will to take a closer look at that. We must be failing to pass that along somewhere.

**Comment by benmarwick** [comment]
Thanks very much, it would be great to be able to get data from a google sheet without having to go to the browser.

I just had a go to knit the chunk above without prior authorisation in my docker container and also got `Error: oauth_listener() needs an interactive environment.`

```
sessionInfo()
R version 3.1.2 (2014-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)

locale:
 [1] LC_CTYPE=en_US.UTF-8 LC_NUMERIC=C        
 [3] LC_TIME=C            LC_COLLATE=C        
 [5] LC_MONETARY=C        LC_MESSAGES=C       
 [7] LC_PAPER=C           LC_NAME=C           
 [9] LC_ADDRESS=C         LC_TELEPHONE=C      
[11] LC_MEASUREMENT=C     LC_IDENTIFICATION=C 

attached base packages:
[1] stats     graphics  grDevices utils     datasets 
[6] methods   base     

other attached packages:
[1] gspreadr_0.1.1         RCurl_1.95-4.5        
[3] bitops_1.0-6           httr_0.6.1            
[5] jsonlite_0.9.14        dplyr_0.4.1           
[7] opencontext_0.0.1.9000

loaded via a namespace (and not attached):
 [1] DBI_0.3.1       Rcpp_0.11.4     assertthat_0.1 
 [4] devtools_1.7.0  digest_0.6.8    evaluate_0.5.5 
 [7] formatR_1.0     htmltools_0.2.6 knitr_1.9      
[10] magrittr_1.5    parallel_3.1.2  rmarkdown_0.5.1
[13] stringr_0.6.2   tools_3.1.2     yaml_2.1.13  
```

**Comment by jennybc** [comment]
Hi @benmarwick,

I can succeed with your example as long as I tell `register_ss()` explicitly that I'm providing the **key**. Like so:

```r
my_gsheet <- register_ss(key = my_gsheet_key, visibility = "public")
```

Will you confirm this works for you? If so, feel free to comment further on usability. I'm trying to balance making it easy to provide almost any identifying info and have it "just work", but also bypassing `list_sheets()` is the user is confident s/he is providing good info. It's the `list_sheets()` call that requires authentication. Maybe I just need to document this better.

**Comment by benmarwick** [comment]
Thanks for looking into it. Working interactively, I don't need to do any authentication with `my_gsheet <- register_ss(key = my_gsheet_key, visibility = "public")` on Windows, but on Linux (ie docker), I am sent to the browser for authentication at the next step:

```
> LOI <- my_gsheet %>% get_via_csv(ws = 5)
Accessing worksheet titled "LOI"
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
```

Knitting the Rmd (where I am most interested in using this package) fails on both platforms with the message: `Error: oauth_listener() needs an interactive environment.` Were you able to knit my example on your machine?

**Comment by jennybc** [comment]
OK I will look into it further.

**Comment by jennybc** [comment]
BTW yes I did knit your example, via Compile Notebook and via Rscript. But I had previously tried interactively, which kicked me to the browser. Although I declined granting any permission to gspreadr, this did leave a .`httr-oauth` file behind (why??). I deleted that and get your experience now. So there is still a problem.

**Comment by jennybc** [comment]
I think this is an `httr` thing I will need to figure out, e.g.:

https://github.com/hadley/httr/issues/90

https://github.com/hadley/httr/blob/master/R/oauth-listener.r#L20-L22

http://stackoverflow.com/questions/24839885/api-call-to-github-while-knitting-error-needs-an-interactive-environment

http://stackoverflow.com/questions/28861891/oauth-listener-needs-an-interactive-environment-execution-halted

**Comment by jennybc** [comment]
Well, I also see a place in `get_via_csv()` where we use the Google token and neglect to check visibility. So it may just be on us still. Working on it.

**Comment by jennybc** [comment]
Will you install from this branch and see if works? Seems to for me now.

```r
devtools::install_github("jennybc/gspreadr", ref = "no-need-token-public-visibility")
```

**Comment by benmarwick** [comment]
Yes! Using that `"no-need-token-public-visibility"` branch I can successfully knit my Rmd file, regardless of the working directory, and without any prior authentication. Thanks so much

**Comment by jennybc** [comment]
Great! I'm going to add some tests inspired by this thread and then merge that branch into master. Glad we got to the bottom of it.

**Comment by jennybc** [comment]
Via 06387ee3af34a047be245d78cd272321b41d22d4, a fix for this has been brought into master, plus some tests.

BTW `gspreadr` has now been renamed `googlesheets`.

I'm closing but please re-open if this does NOT stay resolved when you install from master.

**Comment by benmarwick** [comment]
Thanks again, `googlesheets` works perfectly on windows and linux (docker) with no authentication needed when knitting, so that's fantastic. Thanks so much for the quick fix!

![](http://www.myfacewhen.net/uploads/125-great-success.jpg)

**Comment by jennybc** [comment]
Borat has made it all worthwhile.

**Comment by benmarwick** [comment]
I can't seem to reopen this, but the problem has reappeared... Any thoughts? I try to knit this:

```{r}
library(googlesheets)
library(dplyr)

# register sheet
# authorize(new_user = TRUE)
my_gsheet_key <-  "1vFtO8i3zH8pk4RoxkcQw5kFtCDeooYVimUaXGD8n1WY"
my_gsheet <- register_ss(my_gsheet_key, visibility = "public") 
# also tried it without the visibility argument, no difference

# get data
LOI <- my_gsheet %>% get_via_csv(ws = 5)
all_data <- my_gsheet %>% get_via_csv(ws = 1)
```
 and I get

```
processing file: test.Rmd
Quitting from lines 2-14 (test.Rmd) 
Error: oauth_listener() needs an interactive environment.

Execution halted
```

Here's my session:
```
> sessionInfo()
R version 3.2.0 alpha (2015-03-25 r68091)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
[1] dplyr_0.4.1        googlesheets_0.1.1

loaded via a namespace (and not attached):
[1] magrittr_1.5      assertthat_0.1    parallel_3.2.0   
[4] DBI_0.3.1         htmltools_0.2.6   tools_3.2.0      
[7] Rcpp_0.11.5       rmarkdown_0.5.3.1 digest_0.6.8
```

**Comment by jennybc** [comment]
I'll take another look.  It is possible that our tendency to assume we've working under authorization has crept back in? I'm reworking the sheet registration bits in a branch and will merge soon, which should deal with this once and for all. Can you show me output from `devtools::session_info()`? I'd like to see which commit specifically you are installed from.

**Comment by benmarwick** [comment]
Thanks for your quick reply, here are the further details:
```
> devtools::session_info()
Session info -------------------------------------------------------------------------
 setting  value                                    
 version  R version 3.2.0 alpha (2015-03-25 r68091)
 system   x86_64, mingw32                          
 ui       RStudio (0.99.389)                       
 language (EN)                                     
 collate  English_United States.1252               
 tz       America/Los_Angeles                      

Packages -----------------------------------------------------------------------------
 package      * version  date       source                               
 assertthat   * 0.1      2013-12-06 CRAN (R 3.2.0)                       
 bitops       * 1.0-6    2013-08-17 CRAN (R 3.2.0)                       
 DBI          * 0.3.1    2014-09-24 CRAN (R 3.2.0)                       
 devtools     * 1.7.0    2015-01-17 CRAN (R 3.2.0)                       
 digest       * 0.6.8    2014-12-31 CRAN (R 3.2.0)                       
 dplyr          0.4.1    2015-01-14 CRAN (R 3.2.0)                       
 googlesheets   0.1.1    2015-05-06 Github (jennybc/googlesheets@f008ba6)
 httpuv       * 1.3.2    2014-10-23 CRAN (R 3.2.0)                       
 httr         * 0.6.1    2015-01-01 CRAN (R 3.2.0)                       
 jsonlite     * 0.9.15   2015-03-26 CRAN (R 3.2.0)                       
 lazyeval     * 0.1.10   2015-01-02 CRAN (R 3.2.0)                       
 magrittr     * 1.5      2014-11-22 CRAN (R 3.2.0)                       
 plyr         * 1.8.1    2014-02-26 CRAN (R 3.2.0)                       
 R6           * 2.0.1    2014-10-29 CRAN (R 3.2.0)                       
 Rcpp         * 0.11.5   2015-03-06 CRAN (R 3.2.0)                       
 RCurl        * 1.95-4.5 2014-12-28 CRAN (R 3.2.0)                       
 rstudioapi   * 0.2      2014-12-31 CRAN (R 3.2.0)                       
 stringr      * 0.6.2    2012-12-06 CRAN (R 3.2.0)                       
 xml2         * 0.1.0    2015-04-20 CRAN (R 3.2.0) 
```

**Comment by jennybc** [comment]
@benmarwick 

You just need to say explicitly that you're providing the **key**. It's a subtle thing and my new sheet registration functions will be easier to use!

```
my_gsheet <- register_ss(my_gsheet_key, visibility = "public") 
```

should be

```
my_gsheet <- register_ss(key = my_gsheet_key, visibility = "public") 
```

**Comment by jennybc** [comment]
By telling me it's a key (vs title or whatnot), I won't try to look this up in your list of spreadsheets, which requires authentication.

**Comment by benmarwick** [comment]
Yes, thanks, that's got it working again. I see you mentioned the need for explicit `key = ` previously, sorry to have forgotten! I'm not sure that I've encountered anything like that in other functions I use often, that might be why it didn't stick.

**Comment by jennybc** [comment]
Aaannnnd that would be why I'm reworking the sheet identification/registration functions!

**Comment by benmarwick** [comment]
Ah, I see, sounds good. Can I spam this thread a little to get your thoughts on a PR elsewhere? It's a follow-up to the ropensci unconf, I think you're the sole maintainer of that repo: https://github.com/ropensci/rrrpkg/pull/1

**Comment by benmarwick** [comment]
Thanks! :)

**Comment by lawwu** [comment]
@jennybc where is the register_ss function defined? I don't see it in the version of googlesheets on CRAN

**Comment by jennybc** [comment]
@lawwu That function only existed in a very early version of this package, long before it was submitted to CRAN. If you look at the README or the vignette, you'll see the different ways to register a sheet now, which are, I hope, even more intuitive.

**Comment by nicw4ves** [comment]
@jennybc I'm currently trying to deploy a shiny app that connect to googlesheets. I was able to successfully run the gs_webapp_get_token() function with the code that gs_webapp_get_url() spits out. So my google acount is authenticated at this point. However, whenever I try to use the other functions in the package (e.g. gs_ls) I get the error saying "oauth_listener() needs an interactive environment".
What am I doing wrong???

Thanks!

**Comment by nicw4ves** [comment]
@jennybc I'm having problems setting up my google api console. I followed every step on your instructions. Can you provide me more information on how to set up the google api console please?
