### ISSUE TITLE
Rename pkg to googlesheets

### ISSUE THREAD

**Issue by jennybc** [jennybc/googlesheets#82]
@craigcitro @baogorek 

What do you think about also renaming the `gspreadsheet` class to `googlesheet` or `sheet` at the same time? Other ideas re: the class name?

**Comment by jennybc** [comment]
@baogorek mangled your github username initially :(

**Comment by craigcitro** [comment]
i like changing the class name, too -- i think `googlesheet` works pretty well, esp. given that the user isn't likely to type it a whole lot.

(it seems like the docs at least aim for consistency around `worksheet` being a single tab, and `spreadsheet` or `sheet` being a collection of `worksheet`s.)
