### ISSUE TITLE
Error when using edit_cells

### ISSUE THREAD

**Issue by petersmp** [jennybc/googlesheets#83]
I am getting an odd error message when using the `edit_cells()` function. When using both the code from the README and my own code (identical, but changing exact data being loaded), I get the following error:

```
foo <- new_ss("foo")
foo <- foo %>% edit_cells(input = head(iris), header = TRUE, trim = TRUE)
```

```
Error: x <= letter_to_num("ZZ") are not all TRUE
In addition: Warning message:
In function_list[[i]](value) : NAs introduced by coercion
```

The function is in utils.R, and from the documentation and the source code for edit_cells() I can not  figure out where the function is being used or what is causing the error. Any help would be great. Thanks.

**Comment by jennybc** [comment]
I'm pretty sure I have fixed this. See #72.

Basically I was originally using the development version of `stringr` from GitHub.

I've changed my package to work with just the CRAN version of `stringr`.

So please re-install `gspreadr` and things should work. Please close this if so or let me know if still a problem.

**Comment by petersmp** [comment]
Thanks and that solved it. Sorry that I missed the other open issue -- I had searched for "letter_to_num" and that issue didn't pop up. Thanks for the quick reply and fix.
