### ISSUE TITLE
get_via_csv() 'bug'

### ISSUE THREAD

**Issue by davidorme** [jennybc/googlesheets#92]
I think this bug is just about whether a given worksheet provides the export_csv interface. Basically, I've tried to access a worksheet and get this:

```
> dat <- get_via_csv(ss=sheet2, ws=1)
Accessing worksheet titled "Form Responses"
Error in handle_url(handle, url, ...) : 
  Must specify exactly one of url or handle
```

If I look back through the code, it is simply that ```get_via_csv()``` expects that a worksheet provides an  ```exportcsv```  link:
```
req <- httr::GET(this_ws$exportcsv)
``` 

If the worksheet doesn't have this link, then the ```GET``` function is passed a ```NULL``` and breaks. The fix might only need a test for the link, but I'm not sure whether a missing ```exportcsv``` link suggests some other kind of problem.

More expansive code, showing my (non-reproducible, sorry!) test cases is below

David

```
> library(googlesheets)
> 
> sheet1 <- register_ss('Projects_2013_14')
Sheet identified!
sheet_title: Projects_2013_14
sheet_key: [redacted]

> dat <- get_via_csv(ss=sheet1, ws=1)
Accessing worksheet titled "Form Responses"
> # SUCCESS 
>
> 
> sheet2 <- register_ss('Silwood MSc Project marking form (Responses)')
Sheet identified!
sheet_title: Silwood MSc Project marking form (Responses)
sheet_key: [redacted]

> dat <- get_via_csv(ss=sheet2, ws=1)
Accessing worksheet titled "Form Responses"
Error in handle_url(handle, url, ...) : 
  Must specify exactly one of url or handle
> # FAIL


> str(sheet1$ws)
'data.frame':	1 obs. of  11 variables:
 $ ws_id           : chr "https://spreadsheets.google.com/feeds/worksheets/[redacted]/private/full/od6"
 $ ws_key          : chr "od6"
 $ ws_title        : Named chr "Form Responses"
  ..- attr(*, "names")= chr "1"
 $ row_extent      : int 271
 $ col_extent      : int 21
 $ listfeed        : chr "https://spreadsheets.google.com/feeds/list/[redacted]/od6/private/full"
 $ cellsfeed       : chr "https://spreadsheets.google.com/feeds/cells/[redacted]/od6/private/full"
 $ visualizationApi: chr "https://docs.google.com/spreadsheets/d/[redacted]/gviz/tq?gid=0"
 $ exportcsv       : chr "https://docs.google.com/spreadsheets/d/[redacted]/export?gid=0&format=csv"
 $ self            : chr "https://spreadsheets.google.com/feeds/worksheets/[redacted]/private/full/od6"
 $ edit            : chr "https://spreadsheets.google.com/feeds/worksheets/[redacted]/private/full/od6/-w9btpc"
> str(sheet2$ws)
'data.frame':	1 obs. of  10 variables:
 $ ws_id           : chr "https://spreadsheets.google.com/feeds/worksheets/[redacted]/private/full/od6"
 $ ws_key          : chr "od6"
 $ ws_title        : Named chr "Form Responses"
  ..- attr(*, "names")= chr "1"
 $ row_extent      : int 196
 $ col_extent      : int 31
 $ listfeed        : chr "https://spreadsheets.google.com/feeds/list/[redacted]/od6/private/full"
 $ cellsfeed       : chr "https://spreadsheets.google.com/feeds/cells/[redacted]/od6/private/full"
 $ visualizationApi: chr "https://spreadsheets.google.com/tq?key=[redacted]&sheet=od6"
 $ self            : chr "https://spreadsheets.google.com/feeds/worksheets/[redacted]/private/full/od6"
 $ edit            : chr "https://spreadsheets.google.com/feeds/worksheets/[redacted]/private/full/od6/e2535b7diw"
[redacted]
```

**Comment by jennybc** [comment]
Ok just to confirm: you cannot reproduce the lack of an `exportcsv` link? Or you can but you can't share that sheet w/ me? Like the other issue, I am looking for more info or access to an actual example of a sheet where we cannot get our hands on the `exportcsv` link. Again we can just write more checks for this, but that's much easier with a live example to play with.

Just to check: are any of these sheets giving us trouble "old" sheets?

**Comment by davidorme** [comment]
The lack of ```exportcsv``` is persistent for that sheet and I can't share the sheet. 

I've tried running ```register_ss``` and then ```get_via_csv``` across nine spreadsheets that I have access to in my drive. Four out of nine show the same error and the only obvious pattern is they are all filled from forms. 

The problem sheets have all existed for a couple of years though - I've just created a new form and the sheet for that _can_ be read using ```get_via_csv()```. 

This is a link to a problem sheet without confidential information:

https://docs.google.com/spreadsheet/ccc?key=0AphiLdjs9wK0dDJua1RjeHhXb3NRYkVwSWhGMnVkWUE&usp=sharing

**Comment by jennybc** [comment]
Hi @davidorme,

@jzhaoo has figured out this is due to Old Sheets vs New Sheets stuff. We suspected there would be such glitches. We'll see how hard it is to fix it up. How badly do you want to use this package with Old Sheets? I don't have a good sense for how prevalent they are. Would it be impractical for me to say: "convert to a New Sheet" and then googlesheets will work?

**Comment by jennybc** [comment]
There is no way to access old sheets the way we need to in `get_via_csv()`. So this is never going to work. I've added a check for this and an error message that suggests alternatives. We may try to accommodate old sheets in other functions, but there's simply no way to do it in this case.
