### ISSUE TITLE
Old Style Sheets vs New Sheets  - Keys

### ISSUE THREAD

**Issue by jzhaoo** [jennybc/googlesheets#96]
This is a realization from #92 .

Apparently, old style sheets have 2 keys. A shorter key is stored in the `id` element `<id>https://spreadsheets.google.com/feeds/spreadsheets/private/full/SHORT_KEY</id>` and a longer key is stored in a link element `<link rel="alternate" type="text/html" href="https://spreadsheets.google.com/ccc?key=LONG_KEY”/>`. The longer key is displayed in the browser url when the sheet is open. 

`googlesheets` extracts keys from the id element so the shorter key is stored. Google Drive identifies files by the longer key. So using the shorter key for `download_ss()` and `copy_ss()` (the Drive functions) results in `Error in gdrive_GET(the_url) : client error: (404) Not Found`. 

Maybe we should just store the longer key? Since they both point to the same sheet? But then it would be harder to identify the old style sheets (but maybe there isn't even a need to).

**Comment by jennybc** [comment]
Thanks @jzhaoo for the precise description of the "multiple keys" situation with old sheets. Even though it seems they are on the way out, I went ahead and grabbed the alternate key and put it to use in the functions to download, delete, and copy a sheet.
